### ISSUE TITLE
TypeError: Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by rsryanstephen** [SOHU-Co/kafka-node#1001]
### Environment

* Node version: v8.9.4
* Kafka-node version: ^2.2.3
* Kafka version:

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 1

### Sample Code to reproduce behavior:

'use strict';
const Config = require('./config');
const config = Config.getConfigVariables();

function consoleLoggerProvider(name) {
    // do something with the name
    return {
        debug: console.debug.bind(console),
        info: console.info.bind(console),
        warn: console.warn.bind(console),
        error: console.error.bind(console)
    };
}

function sendKafkaMessage(req, res) {
    console.log('Kafka::sendKafkaMessage');

    const message = req.body.message;
    const topic = req.body.topic;
    let partition = req.body.partition;
    let attributes = 0;

    const kafkaLogging = require('kafka-node/logging');
    kafkaLogging.setLoggerProvider(consoleLoggerProvider);

    const kafka = require('kafka-node');
    const Producer = kafka.Producer;

    const Client = kafka.Client;
    const options = {
        connectionString: config.kafka_zookeepers,
        zkOptions: {
            sessionTimeout: 5000
        }
    };

    const client = new Client(config.kafka_zookeepers, 'batch-monitor', options);

    try {
        console.log('Kafka Client connecting');
        client.connect();

        const producer = new Producer(client, {
            requireAcks: 1
        });

        producer.on('ready', () => {
            console.log('Kafka Producer ready.');
            
            if (!partition) {
                partition = 0;
            }

            if (!attributes) {
                attributes = 0;
            }

            let producerRequest = {
                topic: topic,
                partition: partition,
                messages: [message]
            };

            console.log('Kafka::producer Sending', JSON.stringify(producerRequest));

            producer.send([producerRequest], (err, data) => {

                if (err) {
                    // res.status(408)
                    //     .json({
                    //         status: 'failure',
                    //         data: 'Request timeout'
                    //     });
                    console.log('Kafka::producer sent - err', JSON.stringify(err));
                    client.close(function () {
                    console.log('Kafka::client - Closing connection');
                    });
                } else {
                    // res.status(200)
                    //     .json({
                    //         status: 'success',
                    //         data: data
                    //     });

                    console.log('Kafka::producer sent - data', JSON.stringify(data));
                }
            });
        });

        producer.on('error', err => {
            console.log('Kafka::producer on error', JSON.stringify(err));
            client.close(function () {
            console.log('Kafka::client - Closing connection');
            });
        });
    } catch (e) {
        console.log('Kafka::producer on connect error', JSON.stringify(e));
    } finally {
        client.close(function () {
            console.log('Kafka::client - Closing connection');
        });
    }
}

module.exports = {
    sendKafkaMessage: sendKafkaMessage
};

### Output:

TypeError: Cannot read property 'write' of undefined
application.js:630
    at ConnectionManager.onPacketQueueReadable (c:\Code-Repository\homestead-dashboard\backend\node_modules\node-zookeeper-client\lib\ConnectionManager.js:624:26)
    at emitNone (events.js:106:13)
    at PacketQueue.emit (events.js:208:7)
    at PacketQueue.push (c:\Code-Repository\homestead-dashboard\backend\node_modules\node-zookeeper-client\lib\PacketQueue.js:35:10)
    at ConnectionManager.queue (c:\Code-Repository\homestead-dashboard\backend\node_modules\node-zookeeper-client\lib\ConnectionManager.js:711:30)
    at ConnectionManager.close (c:\Code-Repository\homestead-dashboard\backend\node_modules\node-zookeeper-client\lib\ConnectionManager.js:248:10)
    at Client.close (c:\Code-Repository\homestead-dashboard\backend\node_modules\node-zookeeper-client\index.js:229:28)

**Comment by rsryanstephen** [comment]
updated kafka-node to the latest version: @2.6.1
Same error

**Comment by rsryanstephen** [comment]
Ok I've fixed my own issue here, it is not a bug per se, but the problem no longer occurs when you remove all instances of:
"client.close(function () {"
