### ISSUE TITLE
Error: Unable to assemble data

### ISSUE THREAD

**Issue by thynson** [SOHU-Co/kafka-node#1002]
## Questions?

- [x] Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
- [x] Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

We recently struggled with a HighLevelComsumer error, with message `"Unable to assemble data"`,
raised from [here](https://github.com/SOHU-Co/kafka-node/blob/v2.6.1/lib/zookeeper.js#L163). What could be the reason cause such error, or it's a bug of this library?
stacktrace:
```
FailedToRebalanceConsumerError
    at new FailedToRebalanceConsumerError (/home/git/xxxxxxxxxxxx/node_modules/_kafka-node@2.6.1@kafka-node/lib/errors/FailedToRebalanceConsumerError.js:11:9)
    at /home/git/xxxxxxxxxxxx/node_modules/_kafka-node@2.6.1@kafka-node/lib/highLevelConsumer.js:190:39
    at /home/git/xxxxxxxxxxxx/node_modules/_kafka-node@2.6.1@kafka-node/lib/highLevelConsumer.js:490:9
    at /home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:3888:9
    at /home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:473:16
    at iterateeCallback (/home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:988:17)
    at /home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:969:16
    at /home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:3885:13
    at /home/git/xxxxxxxxxxxx/node_modules/_kafka-node@2.6.1@kafka-node/lib/highLevelConsumer.js:381:11
    at /home/git/xxxxxxxxxxxx/node_modules/_kafka-node@2.6.1@kafka-node/lib/zookeeper.js:217:9
    at /home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:3888:9
    at /home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:473:16
    at iterateeCallback (/home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:988:17)
    at /home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:969:16
    at /home/git/xxxxxxxxxxxx/node_modules/_async@2.6.1@async/dist/async.js:3885:13
    at /home/git/xxxxxxxxxxxx/node_modules/_kafka-node@2.6.1@kafka-node/lib/zookeeper.js:170:19

```

### Environment

* Node version: 8.6.0
* Kafka-node version: 2.6.1
* Kafka version: 0.10

### For specific cases also provide
* Number of Brokers:
* Number partitions for topic: 2

### Include Sample Code to reproduce behavior

Thanks for your contribution!

**Comment by hyperlink** [comment]
Have you tried using `KafkaClient` instead of `Client`?
