### ISSUE TITLE
Request timed out after 30000ms with increased load

### ISSUE THREAD

**Issue by skumar568** [SOHU-Co/kafka-node#1019]
Hi,

Our code works fine until 100 hits per 60 seconds, but fails with 200 hits per 60 seconds with below exception:-
Fri, 06 Jul 2018 10:58:41 GMT ctools     Exception occured in sendToProducer function { TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/* /node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout [as _onTimeout] (/*/node_modules/kafka-node/lib/kafkaClient.js:389:14)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) message: 'Request timed out after 30000ms' }

### Environment
* Node version: 8.10.0
* Kafka-node version: 2.4.1
* Kafka version: 

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 0

### Include Sample Code to reproduce behavior
Code snippet used for creating connection and producer is attached,
[KafkaClient.txt](https://github.com/SOHU-Co/kafka-node/files/2174817/KafkaClient.txt)

Any suggestions/references/pointers are helpful to resolve this issue.

Thanks,
Sanjeev

**Comment by jnotnull** [comment]
Maybe you should open the debug mode and attach the debug.log

**Comment by robertjamesmiller** [comment]
we have a similar issue with publishing throughput from a single NodeJS process

**Comment by JsonMa** [comment]
I also have this problem, 1000 hits per second

**Comment by kabaluyot** [comment]
Any solution?

**Comment by dbelieves** [comment]
Does anybody have a solution for this?

**Comment by mshauny** [comment]
Has anyone being able to find a workaround this yet?
