### ISSUE TITLE
why this error  and how to deal width

### ISSUE THREAD

**Issue by lyz1991** [SOHU-Co/kafka-node#1087]
Error: UnknownTopicOrPartition
    at Object.<anonymous> (/asimov/node_modules/kafka-node/lib/protocol/protocol.js:788:17)
    at Object.self.tap (/asimov/node_modules/binary/index.js:248:12)
    at Object.decodePartitions (/asimov/node_modules/kafka-node/lib/protocol/protocol.js:786:95)
    at Object.self.loop (/asimov/node_modules/binary/index.js:267:16)
    at Object.<anonymous> (/asimov/node_modules/kafka-node/lib/protocol/protocol.js:163:8)
    at Object.self.loop (/asimov/node_modules/binary/index.js:267:16)
    at decodeProduceV2Response (/asimov/node_modules/kafka-node/lib/protocol/protocol.js:780:6)
    at KafkaClient.Client.invokeResponseCallback (/asimov/node_modules/kafka-node/lib/client.js:823:18)
    at KafkaClient.Client.handleReceivedData (/asimov/node_modules/kafka-node/lib/client.js:803:10)
    at KafkaClient.handleReceivedData (/asimov/node_modules/kafka-node/lib/kafkaClient.js:1226:48)
    at Socket.<anonymous> (/asimov/node_modules/kafka-node/lib/kafkaClient.js:782:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Socket.wrapped (/asimov/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)
    at Socket.wrapped [as emit] (/asimov/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
    at TCP.wrapped [as onread] (/asimov/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)

**Comment by lyz1991** [comment]
@hyperlink

**Comment by aikar** [comment]
there is a broker setting to auto create topics, do you have it off?

**Comment by lyz1991** [comment]
> Looks like the topic or partition you're trying to publish to does not exist.

when I run the project on localhost，there is no problem and error， but when online the kafka-node send this error, my project is only use the producer of kafka-node.
