### ISSUE TITLE
using encoding of 'buffer' does not work with ConsumerStream

### ISSUE THREAD

**Issue by alf5** [SOHU-Co/kafka-node#1111]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

## Bug Report
Trying to read a Kafka binary topic using ConsumerStream. According to the documentation use 'buffer' as encoding throws and error.

NOTE: this error happens even if there is no kafka running

### Environment

* Node version: 10.11.0
* Kafka-node version: 3.0.1
* Kafka version: 2.0.0

### For specific cases also provide

* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

```js
const fs = require('fs')
const Kafka = require('kafka-node')
const kclient = new Kafka.KafkaClient({kafkaHost: 'localhost:9092'})
const kstream = new Kafka.ConsumerStream(kclient, [{topic: 'sometopic', offset: 0}],{autoCommit: false, encoding: 'buffer'})
kstream.on('data', data => console.log(`KSTREAM:${(data.value && data.value.length) || data.length || '??'}`))
const fstream = fs.createWriteStream('/dev/null', {flags: 'w', encoding:'binary'})
kstream.pipe(fstream)
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

```
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +4ms
string_decoder.js:52
      throw new ERR_UNKNOWN_ENCODING(enc);
      ^

TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: buffer
    at normalizeEncoding (string_decoder.js:52:13)
    at new StringDecoder (string_decoder.js:66:19)
    at new ReadableState (_stream_readable.js:139:20)
    at ConsumerStream.Readable (_stream_readable.js:152:25)
    at new ConsumerStream (/root/node_modules/kafka-node/lib/consumerStream.js:29:12)
    at Object.<anonymous> (/root/k4.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

Thanks for your contribution!

**Comment by alf5** [comment]
I was able to get it to work by setting `encoding: undefined` in the options object passed to [Reader()](https://github.com/SOHU-Co/kafka-node/blob/e546072039b1130c77c2760cd1665f00234c701a/lib/consumerStream.js#L29) initialiser
then setting it back after the call so the rest of the logic could work.

**Comment by JosephP91** [comment]
Will this be fixed one day? @alf5
