### ISSUE TITLE
MessageSizeTooLarge: Found a message larger than the maximum fetch size of this consumer on topic XXX partition 27 at fetch offset 53734109. Increase the fetch size, or decrease the maximum message size the broker will allow.

### ISSUE THREAD

**Issue by Vijendra07Kulhade** [SOHU-Co/kafka-node#1137]
## Questions?

* I am using consumerGroup, how can we make consumer to move to next offset if it encounter error saying MessageSizeTooLarge: Found a message larger than the maximum fetch size of this consumer on topic XXXX partition 27 at fetch offset 53734109. Increase the fetch size, or decrease the maximum message size the broker will allow.?
* We want to ignore this specific message and move ahead. But current consumerGroup doesn't move forward it keeps on sending the same error again and again.

## Bug Report
Error is thrown from protocol.js and it is converted into error from MessageSizeTooLarge.js.
MessageSizeTooLarge: Found a message larger than the maximum fetch size of this consumer on topic XXXX partition 27 at fetch offset 53734109. Increase the fetch size, or decrease the maximum message size the broker will allow.
### Environment

* Node version: 9.11.2 and 10.7.0
* Kafka-node version: 2.4.1 and 2.6.1
* Kafka version: 0.10.2

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 50

### Include Sample Code to reproduce behavior
Reduce the message size in consumer configuration and issue can be reproduced.

**Comment by hyperlink** [comment]
Looks like it's trying from the last committed offset again so likely this is why you're seeing the same issue. Can you just create a new instance of the group with a larger fetch size? You could advance the committed offset but that requires some poking around the internals of ConsumerGroup.

**Comment by Vijendra07Kulhade** [comment]
Thank for the reply. I kind of caught this error in the error event and tried to use setOffset to the next offset. and commit the offset on done event. 
I see the documentation about committing the offset manually and followed that. It seems like when I pause the consumerGroup it doesn't send the heartbeat and I see heartbeat timeout.
```kafka-node:ConsumerGroup kafka-node-client Heartbeat error: { HeartbeatTimeout: Heartbeat timed out
    at new HeartbeatTimeout (/app/node_modules/kafka-node/lib/errors/HeartbeatTimeoutError.js:6:9)
    at Heartbeat.verifyResolved (/app/node_modules/kafka-node/lib/consumerGroupHeartbeat.js:28:20)
    at Timeout.heartbeatInterval.setInterval [as _onTimeout] (/app/node_modules/kafka-node/lib/consumerGroup.js:584:19)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5) message: 'Heartbeat timed out' } +1ms```

**Comment by hyperlink** [comment]
Where is their documentation to commit offsets manually?

I would keep autocommit on and then just create a new instance of the ConsumerGroup with a larger fetch size when this happens or specify a large enough fetch size that this isn't an issue.

**Comment by Vijendra07Kulhade** [comment]
You are right, there is no documentation for committing offsets manually. From the API I tried this
1. Add a listener to `done` 
2. Pause consumer and call consumer.commit
3. Resume the consumer again.

It works. 

Let me know if there is any other ways to commit the offset manually. We use both consumer and producer together and we want to commit only those offsets which we produced successfully.
