### ISSUE TITLE
Kafka SASL Error

### ISSUE THREAD

**Issue by Mahesh50051** [SOHU-Co/kafka-node#1150]
kafkaHost: `${KAFKA_HOST}:${KAFKA_PORT}`,  
  sasl: {
      mechanism: 'plain',
      username:'username as my principle name',
      password: 'jaas.conf',   
    }
});
below is the error, please let me know the solution for this 

SaslAuthenticationError: Handshake failed.
     at new SaslAuthenticationError (/usr/src/app/node_modules/kafka-node/lib/errors/SaslAuthenticationError.js:12:9)
     at decodeSaslHandshakeResponse (/usr/src/app/node_modules/kafka-node/lib/protocol/protocol.js:76:10)
     at KafkaClient.Client.invokeResponseCallback (/usr/src/app/node_modules/kafka-node/lib/client.js:823:18)
     at KafkaClient.Client.handleReceivedData (/usr/src/app/node_modules/kafka-node/lib/client.js:803:10)
     at KafkaClient.handleReceivedData (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:1226:48)
     at Socket.<anonymous> (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:782:10)
     at emitOne (events.js:116:13)
     at Socket.emit (events.js:211:7)
     at addChunk (_stream_readable.js:263:12)
     at readableAddChunk (_stream_readable.js:250:11)

**Comment by hansolosoami** [comment]
Hey, add values of username and password as string not conf file which could be for EX: 
client = new kafka.KafkaClient({
        kafkaHost: 'localhost:9092',
        sasl: {
            mechanism: "plain",
            username: 'nodeuser',
            password: 'nodeuserpassword'
        },
});
