### ISSUE TITLE
I am getting a TopicsNotExistError even when the topic does exist

### ISSUE THREAD

**Issue by jrop** [SOHU-Co/kafka-node#1152]
## Bug Report

I am getting a TopicsNotExistError even when the topic does exist:

```
$ kafka-topics.sh --list --zookeeper zookeeper:2181
ttest
...other topics...
```

### Environment

* Node version: v8.10.0
* Kafka-node version: v3.0.1
* Kafka version: 2.12-2.1.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

```js
const kafka = require('kafka-node');

const client = new kafka.KafkaClient({kafkaHost:'kafka:9092'});
const consumer = new kafka.Consumer(client, [{topic: 'ttest', partition: 1}], {autoCommit: false});
consumer.on('message', console.log)
consumer.on('error', console.log)
```

The above prints:

```
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: kafka port: 9092 +2ms
  kafka-node:KafkaClient Sending versions request to kafka:9092 +7ms
  kafka-node:KafkaClient broker socket connected {"host":"kafka","port":"9092"} +2ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +2ms
  kafka-node:KafkaClient Received versions response from kafka:9092 +6ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":1,"usable":false},"22":{"min":0,"max":1,"usable":false},"23":{"min":0,"max":2,"usable":false},"24":{"min":0,"max":1,"usable":false},"25":{"min":0,"max":1,"usable":false},"26":{"min":0,"max":1,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":2,"usable":false},"29":{"min":0,"max":1,"usable":false},"30":{"min":0,"max":1,"usable":false},"31":{"min":0,"max":1,"usable":false},"32":{"min":0,"max":2,"usable":false},"33":{"min":0,"max":1,"usable":false},"34":{"min":0,"max":1,"usable":false},"35":{"min":0,"max":1,"usable":false},"37":{"min":0,"max":1,"usable":false},"38":{"min":0,"max":1,"usable":false},"39":{"min":0,"max":1,"usable":false},"40":{"min":0,"max":1,"usable":false},"41":{"min":0,"max":1,"usable":false},"42":{"min":0,"max":1,"usable":false},"produce":{"min":0,"max":7,"usable":2},"fetch":{"min":0,"max":10,"usable":2},"offset":{"min":0,"max":4,"usable":0},"metadata":{"min":0,"max":7,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":6,"usable":2},"offsetFetch":{"min":0,"max":5,"usable":1},"groupCoordinator":{"min":0,"max":2,"usable":0},"joinGroup":{"min":0,"max":3,"usable":0},"heartbeat":{"min":0,"max":2,"usable":0},"leaveGroup":{"min":0,"max":2,"usable":0},"syncGroup":{"min":0,"max":2,"usable":0},"describeGroups":{"min":0,"max":2,"usable":0},"listGroups":{"min":0,"max":2,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":2,"usable":0},"createTopics":{"min":0,"max":3,"usable":false},"deleteTopics":{"min":0,"max":3,"usable":false},"saslAuthenticate":{"min":0,"max":0,"usable":0}} +1ms
  kafka-node:KafkaClient broker is now ready +0ms
  kafka-node:KafkaClient updating metadatas +2ms
  kafka-node:Consumer consumer ready +1ms
  kafka-node:KafkaClient updating metadatas +2ms
{ TopicsNotExistError: The topic(s) ttest do not exist
    at new TopicsNotExistError (/root/kafka/node_modules/kafka-node/lib/errors/TopicsNotExistError.js:11:9)
    at loadMetadataForTopics (/root/kafka/node_modules/kafka-node/lib/kafkaClient.js:916:14)
    at async.series (/root/kafka/node_modules/kafka-node/lib/kafkaClient.js:885:5)
    at /root/kafka/node_modules/async/dist/async.js:3888:9
    at /root/kafka/node_modules/async/dist/async.js:473:16
    at replenish (/root/kafka/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/root/kafka/node_modules/async/dist/async.js:995:17)
    at /root/kafka/node_modules/async/dist/async.js:969:16
    at /root/kafka/node_modules/async/dist/async.js:3885:13
    at KafkaClient.wrappedFn (/root/kafka/node_modules/kafka-node/lib/kafkaClient.js:471:14)
  topics: [ 'ttest' ],
  message: 'The topic(s) ttest do not exist' }
```

Interestingly, if I try to get a list of topics, none is returned:

```js
const kafka = require('kafka-node');

const client = new kafka.KafkaClient({kafkaHost:'kafka:9092'});
client.once('connect', function () {
    client.loadMetadataForTopics([], function (error, results) {
      if (error) return console.error(error);
      console.log(results);
    });
});
client.on('error', console.error);
// prints: [ {}, { metadata: {}, clusterMetadata: { controllerId: -1 } } ]
```

**Comment by rorysavage77** [comment]
I believe this is a timing issue perhaps.   You may need a +2ms delay.

**Comment by Littly** [comment]
Same issue.
For me, it's because the nameserver I'm using doesn't support querying metadata using `[]`, which causes the internally cached metadata to be empty.
So I replace the `[]` with the topic I wanted to subscribe to in the [initial query](
https://github.com/SOHU-Co/kafka-node/blob/fcc8aefc7798f6e4b79d9b5c31f047c1933329e6/lib/kafkaClient.js#L146) and the error disappeared.
