### ISSUE TITLE
HighLevelProducer with requireAcks=all times out after 30 seconds

### ISSUE THREAD

**Issue by agrapsas** [SOHU-Co/kafka-node#1162]
## Bug Report
- When attempting to call `send()` on `HighLevelProducer` with `requireAcks` set to `"all"` connection times out after 30 seconds.
- Using the command line consumer, I can see the messages immediately arrive.
- The same code with acks `0` or `1` operates as expected.

### Environment

* Node version: v8.11.3
* Kafka-node version: 3.0.1
* Kafka version: 2.12-1.0.0

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 1
* Replication factor for topic: 3

### Code

```javascript
const config =
{
    requireAcks : "all",
    ackTimeoutMs : 100
};

producer = new Kafka.HighLevelProducer( connection, config );
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

```javascript
2019-1-7 14:19:32 [INFO] script.js:220: Connecting event queue
{
  "kafkaHost": "localhost:9092"
}
2019-1-7 14:19:32 [INFO] EventQueue.js:78: Connecting to Kafka
{
  "brokerHost": "localhost:9092"
}
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +2ms
  kafka-node:KafkaClient Sending versions request to localhost:9092 +7ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +3ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +1ms
  kafka-node:KafkaClient Received versions response from localhost:9092 +4ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":0,"usable":false},"22":{"min":0,"max":0,"usable":false},"23":{"min":0,"max":0,"usable":false},"24":{"min":0,"max":0,"usable":false},"25":{"min":0,"max":0,"usable":false},"26":{"min":0,"max":0,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":0,"usable":false},"29":{"min":0,"max":0,"usable":false},"30":{"min":0,"max":0,"usable":false},"31":{"min":0,"max":0,"usable":false},"32":{"min":0,"max":0,"usable":false},"33":{"min":0,"max":0,"usable":false},"34":{"min":0,"max":0,"usable":false},"35":{"min":0,"max":0,"usable":false},"37":{"min":0,"max":0,"usable":false},"produce":{"min":0,"max":5,"usable":2},"fetch":{"min":0,"max":6,"usable":2},"offset":{"min":0,"max":2,"usable":0},"metadata":{"min":0,"max":5,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":3,"usable":2},"offsetFetch":{"min":0,"max":3,"usable":1},"groupCoordinator":{"min":0,"max":1,"usable":0},"joinGroup":{"min":0,"max":2,"usable":0},"heartbeat":{"min":0,"max":1,"usable":0},"leaveGroup":{"min":0,"max":1,"usable":0},"syncGroup":{"min":0,"max":1,"usable":0},"describeGroups":{"min":0,"max":1,"usable":0},"listGroups":{"min":0,"max":1,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":1,"usable":0},"createTopics":{"min":0,"max":2,"usable":false},"deleteTopics":{"min":0,"max":1,"usable":false},"saslAuthenticate":{"min":0,"max":0,"usable":0}} +0ms
  kafka-node:KafkaClient broker is now ready +0ms
  kafka-node:KafkaClient updating metadatas +6ms
2019-1-7 14:19:32 [INFO] EventQueue.js:92: Connected to kafka
2019-1-7 14:19:32 [INFO] publish-kafka.js:98: Repeat publishing
{
  "topic": "user_events",
  "payload": {
    "type": "HEALTH",
    "userId": "abc"
  },
  "repeatIntervalMs": 500
}
2019-1-7 14:19:32 [INFO] EventQueue.js:188: Publishing to Kafka
{
  "payloads": [
    {
      "topic": "user_events",
      "messages": "{\"data\":{\"type\":\"HEALTH\",\"userId\":\"abc\"},\"id\":\"2bd49cfd-5b35-99df-d61f-9f51779ea7c2\",\"origin\":\"unnamed\",\"timestampMs\":1546888772933}"
    }
  ]
}
  kafka-node:KafkaClient compressing messages if needed +506ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +3ms
  kafka-node:KafkaClient Sending versions request to nightgoat:9093 +0ms
  kafka-node:KafkaClient Received versions response from nightgoat:9093 +2ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":0,"usable":false},"22":{"min":0,"max":0,"usable":false},"23":{"min":0,"max":0,"usable":false},"24":{"min":0,"max":0,"usable":false},"25":{"min":0,"max":0,"usable":false},"26":{"min":0,"max":0,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":0,"usable":false},"29":{"min":0,"max":0,"usable":false},"30":{"min":0,"max":0,"usable":false},"31":{"min":0,"max":0,"usable":false},"32":{"min":0,"max":0,"usable":false},"33":{"min":0,"max":0,"usable":false},"34":{"min":0,"max":0,"usable":false},"35":{"min":0,"max":0,"usable":false},"37":{"min":0,"max":0,"usable":false},"produce":{"min":0,"max":5,"usable":2},"fetch":{"min":0,"max":6,"usable":2},"offset":{"min":0,"max":2,"usable":0},"metadata":{"min":0,"max":5,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":3,"usable":2},"offsetFetch":{"min":0,"max":3,"usable":1},"groupCoordinator":{"min":0,"max":1,"usable":0},"joinGroup":{"min":0,"max":2,"usable":0},"heartbeat":{"min":0,"max":1,"usable":0},"leaveGroup":{"min":0,"max":1,"usable":0},"syncGroup":{"min":0,"max":1,"usable":0},"describeGroups":{"min":0,"max":1,"usable":0},"listGroups":{"min":0,"max":1,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":1,"usable":0},"createTopics":{"min":0,"max":2,"usable":false},"deleteTopics":{"min":0,"max":1,"usable":false},"saslAuthenticate":{"min":0,"max":0,"usable":0}} +0ms
  kafka-node:KafkaClient broker is now ready +0ms
2019-1-7 14:20:02 [ERROR] EventQueue.js:193: Error publishing to Kafka
{
  "payloads": [
    {
      "topic": "user_events",
      "messages": "{\"data\":{\"type\":\"HEALTH\",\"userId\":\"abc\"},\"id\":\"2bd49cfd-5b35-99df-d61f-9f51779ea7c2\",\"origin\":\"unnamed\",\"timestampMs\":1546888772933}",
      "partition": 0,
      "attributes": 0
    }
  ],
  "kafkaPublishError": {
    "stack": "TimeoutError: Request timed out after 30000ms\n    at new TimeoutError (REDACTED/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)\n    at Timeout.setTimeout [as _onTimeout] (REDACTED/node_modules/kafka-node/lib/kafkaClient.js:481:14)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)",
    "message": "Request timed out after 30000ms"
  }
}
```

**Comment by agrapsas** [comment]
I just tested this on our development cluster, as well (just in case my local configuration was somehow at fault), and the outcome was exactly the same as above (timeout, but message got to its destination).

**Comment by hyperlink** [comment]
I have only seen values of 0 and 1 used for `requireAcks`. I don't believe a string is supported.

**Comment by agrapsas** [comment]
The supported Kafka values for `acks` are `0`, `1`, and `all` for producers.

`0` should mean the producer will not wait for acknowledgement.
`1` should mean the leader will write to its local log but will not wait for acknowledgement from followes
`all` should mean the leader will wait for full set of in-sync replicas to acknowledge

http://kafka.apache.org/documentation.html#producerconfigs

**Comment by agrapsas** [comment]
Oh, code in `baseProducer` (https://github.com/SOHU-Co/kafka-node/blob/master/lib/baseProducer.js#L45) does say this:

```javascript
<li>0 = No ack required</li>
 *      <li>1 = Leader ack required</li>
 *      <li>-1 = All in sync replicas ack required</li>
```

**Comment by agrapsas** [comment]
I tried with `-1`, but, i don't think I had some other settings configured when I was testing at the time. I will retry with this and let you know if it behaves as expected. If it does, I will close the card.

**Comment by agrapsas** [comment]
With `-1` it appears that messages reliably arrive at the consumers in my test. When I take down enough brokers to get the `NotEnoughReplicas`'s error, after bringing brokers up, those messages are lost. Is this expected?

**Comment by hyperlink** [comment]
> When I take down enough brokers to get the `NotEnoughReplicas`'s error, after bringing brokers up, those messages are lost. Is this expected?

That seems like a reasonable response from the broker.

> Actually, even when I get `Broker not available (sendRequest)` I lose the message with `-1`. Do I need to manually implement recovery on the publisher?

You need to manually retry sending the message if it's not successful. KafkaClient will schedule a metadata fetch to update it's broker's list.
