### ISSUE TITLE
4.0.1 keeps throwing offsetOutOfRange error.

### ISSUE THREAD

**Issue by bobzsj87** [SOHU-Co/kafka-node#1190]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version: 10.13.0
* Kafka-node version: 4.0.1
* Kafka version: 2.1.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 100

It happens with consumer created without supplying options (so default options).

The code is OK in kafka-node 3.0.1, but after upgrading to 4.0.1 with the same code base and subscribe to a partition whose messages is too old and was cleaned. The consumer infinitely throws offsetOutOfRange error.

**Comment by thynson** [comment]
Maybe it's same bug with #1179.

**Comment by hyperlink** [comment]
Which type of consumer is this?

**Comment by bobzsj87** [comment]
Consumer, not ConsumerGroup

**Comment by bobzsj87** [comment]
I tested more and found it is related to compression. When messages are not compressed (either gzip or snappy), it is ok. When it is compressed, the first message the consumer gets is ok, then it keeps throwing

rror: OffsetOutOfRange
    at events.push (/Users/bobzhou/dev/speech_request_service/node_modules/kafka-node/lib/protocol/protocol.js:267:25)
    at /Users/bobzhou/dev/speech_request_service/node_modules/async/dist/async.js:3880:24
    at replenish (/Users/bobzhou/dev/speech_request_service/node_modules/async/dist/async.js:1011:17)
    at /Users/bobzhou/dev/speech_request_service/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/Users/bobzhou/dev/speech_request_service/node_modules/async/dist/async.js:1041:24)
    at /Users/bobzhou/dev/speech_request_service/node_modules/async/dist/async.js:1046:16
    at _parallel (/Users/bobzhou/dev/speech_request_service/node_modules/async/dist/async.js:3879:5)
    at Object.series (/Users/bobzhou/dev/speech_request_service/node_modules/async/dist/async.js:4735:5)
    at _decodeFetchResponse (/Users/bobzhou/dev/speech_request_service/node_modules/kafka-node/lib/protocol/protocol.js:244:9)
    at /Users/bobzhou/dev/speech_request_service/node_modules/kafka-node/lib/protocol/protocol.js:193:12
    at KafkaClient.Client.invokeResponseCallback (/Users/bobzhou/dev/speech_request_service/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/Users/bobzhou/dev/speech_request_service/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/Users/bobzhou/dev/speech_request_service/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/Users/bobzhou/dev/speech_request_service/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)

**Comment by bobzsj87** [comment]
Further more, the consumer only subscribes to one topic on ONE partition. Is it related to #1072?

**Comment by aikar** [comment]
@bobzsj87 yes it is related to my change. its technically now 'fixed' in some cases, but see: https://github.com/SOHU-Co/kafka-node/issues/1225
While this issue is now fixed, other scenarios are now broken.

**Comment by tvvignesh** [comment]
@hyperlink @aikar @bobzsj87 I am facing this issue too - Getting an infinite loop in both version 4.0.1 as well as 4.1.1 (did not have this problem with 3.x versions earlier). Please find the screenshot of the same below. Kindly help - this is the only place where I am currently stuck.

![Screenshot from 2019-04-18 23-31-00](https://user-images.githubusercontent.com/1165845/56381380-51192500-6232-11e9-97d3-fa1e6a8f80f0.png)

**Comment by hyperlink** [comment]
@tvvignesh has the consumer been down for a period of time and the committed is out of retention? Does this still happen with new groupid?

**Comment by tvvignesh** [comment]
@hyperlink: Thanks for your response. Yup, the consumer was shut down for a period of time and the topics had expired. It doesn't happen with new group IDs - I have temporarily come over this by setting the retention period to 1 year.

**Comment by hyperlink** [comment]
> Yup, the consumer was shut down for a period of time and the topics had expired.

There's nothing kafka-node can do to fetch from those offsets again. If you are using ConsumerGroup it should automatically recover from this issue through `outOfRangeOffset` configuration and start fetching from the earliest or latest.
