### ISSUE TITLE
ConsumerGroupStream not consuming messages with read() after call to resume()

### ISSUE THREAD

**Issue by zignd** [SOHU-Co/kafka-node#1197]
### Environment

* Node version: 8.10.0
* Kafka-node version: 4.0.2
* Kafka version: 2.1.1

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

#### Setting up the environment with Docker containers

```
$ docker run -d --net host --name zookeeper -e ZOOKEEPER_CLIENT_PORT=2181 -e ZOOKEEPER_TICK_TIME=2000 confluentinc/cp-zookeeper:latest
$ docker run -d --net host --name kafka -e ZOOKEEPER_CLIENT_PORT=2181 -e KAFKA_BROKER_ID=1 -e KAFKA_ZOOKEEPER_CONNECT=localhost:2181 -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2 confluentinc/cp-kafka:latest
```
#### Code that is not working as expected

```js
'use strict';

const kafka = require('kafka-node');

function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

async function init() {
    console.log('creating consumer');
    const consumer = new kafka.ConsumerGroupStream({
        kafkaHost: 'localhost:9092',
        groupId: 'testing',
        autoCommit: false
    }, 'testing-consumption');
    
    console.log('resuming', consumer._readableState.flowing);
    consumer.readable = true;
    consumer.resume();
    
    console.log('while true begins', consumer._readableState.flowing);
    while (true) {
        const chunk = consumer.read();
        if (!chunk) {
            console.log('nothing...', new Date());
            await sleep(3000); 
            continue;
        }
        console.log('>>>>>>>>>>>>>>>>>>>>>>>>>');
        console.log(chunk);
        console.log('<<<<<<<<<<<<<<<<<<<<<<<<<');
    }
}

init().catch((err) => console.error(err));
```
#### Expected behavior

I'd like to use the ConsumerGroupStream through the read() function, I think I implemented it correctly, but I can't get it to work, that is, to read messages and log them.

#### Current behavior

The consumer is not reading any messages, neither old nor new ones.

### Output with debug turned on

```
$ DEBUG=* node index.js
creating consumer
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +1ms
  kafka-node:KafkaClient createBroker localhost 9092 +0ms
resuming null
while true begins true
  kafka-node:ConsumerGroupStream _read called +4ms
  kafka-node:ConsumerGroupStream consumerGroup is not ready, calling consumerGroup.connect +0ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +0ms
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +1ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper localhost:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)] +1ms
nothing... 2019-02-24T07:25:02.960Z
  kafka-node:KafkaClient Sending versions request to localhost:9092 +3ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +1ms
  kafka-node:KafkaClient connected to socket, trying to load initial metadata +1ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +0ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper localhost:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)] +0ms
  kafka-node:KafkaClient Received versions response from localhost:9092 +4ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":1,"usable":false},"22":{"min":0,"max":1,"usable":false},"23":{"min":0,"max":2,"usable":false},"24":{"min":0,"max":1,"usable":false},"25":{"min":0,"max":1,"usable":false},"26":{"min":0,"max":1,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":2,"usable":false},"29":{"min":0,"max":1,"usable":false},"30":{"min":0,"max":1,"usable":false},"31":{"min":0,"max":1,"usable":false},"33":{"min":0,"max":1,"usable":false},"34":{"min":0,"max":1,"usable":false},"35":{"min":0,"max":1,"usable":false},"37":{"min":0,"max":1,"usable":false},"38":{"min":0,"max":1,"usable":false},"39":{"min":0,"max":1,"usable":false},"40":{"min":0,"max":1,"usable":false},"41":{"min":0,"max":1,"usable":false},"42":{"min":0,"max":1,"usable":false},"produce":{"min":0,"max":7,"usable":2},"fetch":{"min":0,"max":10,"usable":2},"offset":{"min":0,"max":4,"usable":0},"metadata":{"min":0,"max":7,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":6,"usable":2},"offsetFetch":{"min":0,"max":5,"usable":1},"groupCoordinator":{"min":0,"max":2,"usable":0},"joinGroup":{"min":0,"max":3,"usable":0},"heartbeat":{"min":0,"max":2,"usable":0},"leaveGroup":{"min":0,"max":2,"usable":0},"syncGroup":{"min":0,"max":2,"usable":0},"describeGroups":{"min":0,"max":2,"usable":0},"listGroups":{"min":0,"max":2,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":2,"usable":0},"createTopics":{"min":0,"max":3,"usable":1},"deleteTopics":{"min":0,"max":3,"usable":false},"describeConfigs":{"min":0,"max":2,"usable":0},"saslAuthenticate":{"min":0,"max":0,"usable":0}} +0ms
  kafka-node:KafkaClient broker is now ready +1ms
  kafka-node:KafkaClient broker is now ready +2ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +2ms
  kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 1000 ms { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +5ms
  kafka-node:KafkaClient updating metadatas +4ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +997ms
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +0ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +2ms
  kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 1800 ms { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +0ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +2s
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +1ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +3ms
  kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 3240 ms { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +1ms
nothing... 2019-02-24T07:25:05.961Z
nothing... 2019-02-24T07:25:08.964Z
  kafka-node:ConsumerGroup Connecting kafka-node-client +3s
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +0ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +3ms
  kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 5832 ms { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +1ms
nothing... 2019-02-24T07:25:11.967Z
  kafka-node:ConsumerGroup Connecting kafka-node-client +6s
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +0ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +3ms
  kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 10498 ms { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +1ms
nothing... 2019-02-24T07:25:14.968Z
nothing... 2019-02-24T07:25:17.970Z
nothing... 2019-02-24T07:25:20.972Z
nothing... 2019-02-24T07:25:23.974Z
  kafka-node:ConsumerGroup Connecting kafka-node-client +10s
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +1ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +3ms
  kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 18896 ms { GroupCoordinatorNotAvailable: Kafka Error Code: 15
    at new GroupCoordinatorNotAvailable (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
    at createGroupError (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1148:18)
    at Object.self.tap (/home/zignd/code/kafka-consuming-messages/node_modules/binary/index.js:248:12)
    at decodeGroupCoordinatorResponse (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/protocol/protocol.js:1146:6)
    at KafkaClient.Client.invokeResponseCallback (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/home/zignd/code/kafka-consuming-messages/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 15', errorCode: 15 } +1ms
nothing... 2019-02-24T07:25:26.975Z
```

**Comment by hyperlink** [comment]
The consumer is getting COORDINATOR_NOT_AVAILABLE error from the broker. What does the kafka container logs say?

**Comment by zignd** [comment]
Thanks for the help, indeed there was a problem in the Kafka container, a configuration problem. The KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2 was causing a few errors, once I set it to 1 it worked.
