### ISSUE TITLE
Attempting to produce a big batch - Error: MessageSizeTooLarge

### ISSUE THREAD

**Issue by netofri** [SOHU-Co/kafka-node#1199]
## Bug Report
Trying to produce a batch of 40k messages and getting an error - Error: MessageSizeTooLarge.
I was unable to find documentation / configuration for size limits for producing data in a batch.

I am producing each message with a different key, and using a keyed partitioner  configuration in order for kafka to shard the data to all partitions on the topic.

I think this issue also relates to  #1178, because I also have to separate each payload with its own key, and if I batch all messages on the same `messages` attribute, kafka will not shard the messages on all partitions.

### Environment
* Node version: 10.15.0
* Kafka-node version: 4.0.2
* Kafka version: kafka_2.11-2.0.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 4

Typescript code:
```ts
import * as kafka from 'kafka-node';
import * as uuid from 'uuid';


// generate some fake messages
const keys: string[] = [];
const values: any[] = [];

const message = {
    token: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb",
    id: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb",
    query: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb",
    correlationId: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb",
    correlationData: {id: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb"},
    replyTo: "reps"
};

for (let i = 40000; i > 0; i--) {
    const id = uuid.v4();
    message.query = message.correlationId = message.correlationData.id = id;
    
    keys.push(id);
    values.push(message);
}


// create a producer
const clientOptions: kafka.KafkaClientOptions = {
    kafkaHost: 'localhost:9092'
};

const client = new kafka.KafkaClient(clientOptions);
const producer = new kafka.Producer(client, {
    partitionerType: 3
});

producer.on('ready', function () {
    // generate an array of ProduceRequest objects
    const payload: kafka.ProduceRequest[] = values.map((value, index) => {
        return {
            topic: 'test',
            messages: JSON.stringify(value),
            key: keys[index]
        }
    });

    // produce
    producer.send(payload, (error, data) => {
        console.log(error);
    });
});
```

Javascript code:
```js
"use strict";

var kafka = require("kafka-node");
var uuid = require("uuid");
// generate some fake messages
var keys = [];
var values = [];
var message = {
    token: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb",
    id: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb",
    query: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb",
    correlationId: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb",
    correlationData: { id: "8f98fa09-30b4-4148-a678-4e00e6dbb7fb" },
    replyTo: "reps"
};
for (var i = 40000; i > 0; i--) {
    var id = uuid.v4();
    message.query = message.correlationId = message.correlationData.id = id;
    keys.push(id);
    values.push(message);
}
// create a producer
var clientOptions = {
    kafkaHost: 'localhost:9092'
};
var client = new kafka.KafkaClient(clientOptions);
var producer = new kafka.Producer(client, {
    partitionerType: 3
});
producer.on('ready', function () {
    // generate an array of ProduceRequest objects
    var payload = values.map(function (value, index) {
        return {
            topic: 'test',
            messages: JSON.stringify(value),
            key: keys[index]
        };
    });
    // produce
    producer.send(payload, function (error, data) {
        console.log(error);
    });
});

```

### Debug log
```
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +3ms
  kafka-node:KafkaClient Sending versions request to localhost:9092 +7ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +4ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +1ms
  kafka-node:KafkaClient Received versions response from localhost:9092 +6ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":1,"usable":false},"22":{"min":0,"max":1,"usable":false},"23":{"min":0,"max":1,"usable":false},"24":{"min":0,"max":1,"usable":false},"25":{"min":0,"max":1,"usable":false},"26":{"min":0,"max":1,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":1,"usable":false},"29":{"min":0,"max":1,"usable":false},"30":{"min":0,"max":1,"usable":false},"31":{"min":0,"max":1,"usable":false},"32":{"min":0,"max":2,"usable":false},"33":{"min":0,"max":1,"usable":false},"34":{"min":0,"max":1,"usable":false},"35":{"min":0,"max":1,"usable":false},"37":{"min":0,"max":1,"usable":false},"38":{"min":0,"max":1,"usable":false},"39":{"min":0,"max":1,"usable":false},"40":{"min":0,"max":1,"usable":false},"41":{"min":0,"max":1,"usable":false},"42":{"min":0,"max":1,"usable":false},"produce":{"min":0,"max":6,"usable":2},"fetch":{"min":0,"max":8,"usable":2},"offset":{"min":0,"max":3,"usable":0},"metadata":{"min":0,"max":6,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":4,"usable":2},"offsetFetch":{"min":0,"max":4,"usable":1},"groupCoordinator":{"min":0,"max":2,"usable":0},"joinGroup":{"min":0,"max":3,"usable":0},"heartbeat":{"min":0,"max":2,"usable":0},"leaveGroup":{"min":0,"max":2,"usable":0},"syncGroup":{"min":0,"max":2,"usable":0},"describeGroups":{"min":0,"max":2,"usable":0},"listGroups":{"min":0,"max":2,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":2,"usable":0},"createTopics":{"min":0,"max":3,"usable":false},"deleteTopics":{"min":0,"max":2,"usable":false},"saslAuthenticate":{"min":0,"max":0,"usable":0}} +1ms
  kafka-node:KafkaClient broker is now ready +0ms
  kafka-node:KafkaClient updating metadatas +7ms
  kafka-node:KafkaClient compressing messages if needed +157ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +40ms
  kafka-node:KafkaClient Sending versions request to echo-kafka:9092 +5ms
  kafka-node:KafkaClient Received versions response from echo-kafka:9092 +1ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":1,"usable":false},"22":{"min":0,"max":1,"usable":false},"23":{"min":0,"max":1,"usable":false},"24":{"min":0,"max":1,"usable":false},"25":{"min":0,"max":1,"usable":false},"26":{"min":0,"max":1,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":1,"usable":false},"29":{"min":0,"max":1,"usable":false},"30":{"min":0,"max":1,"usable":false},"31":{"min":0,"max":1,"usable":false},"32":{"min":0,"max":2,"usable":false},"33":{"min":0,"max":1,"usable":false},"34":{"min":0,"max":1,"usable":false},"35":{"min":0,"max":1,"usable":false},"37":{"min":0,"max":1,"usable":false},"38":{"min":0,"max":1,"usable":false},"39":{"min":0,"max":1,"usable":false},"40":{"min":0,"max":1,"usable":false},"41":{"min":0,"max":1,"usable":false},"42":{"min":0,"max":1,"usable":false},"produce":{"min":0,"max":6,"usable":2},"fetch":{"min":0,"max":8,"usable":2},"offset":{"min":0,"max":3,"usable":0},"metadata":{"min":0,"max":6,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":4,"usable":2},"offsetFetch":{"min":0,"max":4,"usable":1},"groupCoordinator":{"min":0,"max":2,"usable":0},"joinGroup":{"min":0,"max":3,"usable":0},"heartbeat":{"min":0,"max":2,"usable":0},"leaveGroup":{"min":0,"max":2,"usable":0},"syncGroup":{"min":0,"max":2,"usable":0},"describeGroups":{"min":0,"max":2,"usable":0},"listGroups":{"min":0,"max":2,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":2,"usable":0},"createTopics":{"min":0,"max":3,"usable":false},"deleteTopics":{"min":0,"max":2,"usable":false},"saslAuthenticate":{"min":0,"max":0,"usable":0}} +0ms
  kafka-node:KafkaClient broker is now ready +1ms
Error: MessageSizeTooLarge
    at Object.<anonymous> (node_modules\kafka-node\lib\protocol\protocol.js:788:17)
    at Object.self.tap (node_modules\binary\index.js:248:12)
    at Object.decodePartitions (node_modules\kafka-node\lib\protocol\protocol.js:786:95)
    at Object.self.loop (node_modules\binary\index.js:267:16)
    at Object.<anonymous> (node_modules\kafka-node\lib\protocol\protocol.js:163:8)
    at Object.self.loop (node_modules\binary\index.js:267:16)
    at decodeProduceV2Response (node_modules\kafka-node\lib\protocol\protocol.js:780:6)
    at KafkaClient.Client.invokeResponseCallback (node_modules\kafka-node\lib\client.js:823:18)
    at KafkaClient.Client.handleReceivedData (node_modules\kafka-node\lib\client.js:803:10)
    at KafkaClient.handleReceivedData (node_modules\kafka-node\lib\kafkaClient.js:1226:48)
```

I hope this is clear enough, please let me know if you need more info. 
Thanks.

**Comment by hyperlink** [comment]
This error comes from  the broker. Looks like you're hitting a limit on the broker. According to the [kafka docs](https://kafka.apache.org/protocol#protocol_error_codes): 

> The request included a message larger than the max message size the server will accept.

**Comment by netofri** [comment]
> This error comes from the broker. Looks like you're hitting a limit on the broker. According to the [kafka docs](https://kafka.apache.org/protocol#protocol_error_codes):
> 
> > The request included a message larger than the max message size the server will accept.

Thanks, that was it.
I guess I can either increase the max.message.bytes on the topic, or chunk my batch into smaller batches.

**Comment by Albinzr** [comment]
In HighLevelProducer how can I increase the message limit size, Can anyone give an example snippet?.
