### ISSUE TITLE
Passing `groupId` to `ConsumerStream` has no effect

### ISSUE THREAD

**Issue by cjohansen** [SOHU-Co/kafka-node#1207]
## Bug Report

Using the `ConsumerStream` with `groupId` seems to not commit the offset - restarting the process always starts consumption from the beginning.

### Environment

* Node version: 8.9.1
* Kafka-node version: 4.0.2
* Kafka version: 2.1.1

### Include Sample Code to reproduce behavior

```js
const {KafkaClient, ConsumerStream} = require('kafka-node');

const client = new KafkaClient({});

const consumer = new ConsumerStream(
  client,
  [{topic: "some-topic", partition: 0}],
  {
    groupId: "test-bug-group",
    autoCommit: true
  });

function poll() {
  const msg = consumer.read();

  if (msg) {
    console.log("Got message", msg);
    setImmediate(poll);
  } else {
    console.log("No message");
    setTimeout(poll, 1000);
  }
}

poll();
console.log('Started Consumer');
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

```
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +5ms
  kafka-node:KafkaClient createBroker localhost 9092 +1ms
No message
Started Consumer
  kafka-node:KafkaClient Sending versions request to localhost:9092 +12ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +3ms
  kafka-node:KafkaClient connected to socket, trying to load initial metadata +2ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +1ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper localhost:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)] +0ms
  kafka-node:KafkaClient Received versions response from localhost:9092 +8ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":1,"usable":false},"22":{"min":0,"max":1,"usable":false},"23":{"min":0,"max":2,"usable":false},"24":{"min":0,"max":1,"usable":false},"25":{"min":0,"max":1,"usable":false},"26":{"min":0,"max":1,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":2,"usable":false},"29":{"min":0,"max":1,"usable":false},"30":{"min":0,"max":1,"usable":false},"31":{"min":0,"max":1,"usable":false},"33":{"min":0,"max":1,"usable":false},"34":{"min":0,"max":1,"usable":false},"35":{"min":0,"max":1,"usable":false},"37":{"min":0,"max":1,"usable":false},"38":{"min":0,"max":1,"usable":false},"39":{"min":0,"max":1,"usable":false},"40":{"min":0,"max":1,"usable":false},"41":{"min":0,"max":1,"usable":false},"42":{"min":0,"max":1,"usable":false},"produce":{"min":0,"max":7,"usable":2},"fetch":{"min":0,"max":10,"usable":2},"offset":{"min":0,"max":4,"usable":0},"metadata":{"min":0,"max":7,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":6,"usable":2},"offsetFetch":{"min":0,"max":5,"usable":1},"groupCoordinator":{"min":0,"max":2,"usable":0},"joinGroup":{"min":0,"max":3,"usable":0},"heartbeat":{"min":0,"max":2,"usable":0},"leaveGroup":{"min":0,"max":2,"usable":0},"syncGroup":{"min":0,"max":2,"usable":0},"describeGroups":{"min":0,"max":2,"usable":0},"listGroups":{"min":0,"max":2,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":2,"usable":0},"createTopics":{"min":0,"max":3,"usable":1},"deleteTopics":{"min":0,"max":3,"usable":false},"describeConfigs":{"min":0,"max":2,"usable":0},"saslAuthenticate":{"min":0,"max":0,"usable":0}} +0ms
  kafka-node:KafkaClient broker is now ready +1ms
  kafka-node:KafkaClient updating metadatas +29ms
  kafka-node:ConsumerStream consumer ready +2ms
  kafka-node:KafkaClient updating metadatas +12ms
  kafka-node:KafkaClient createBroker 192.168.1.9 9092 +3ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper 192.168.1.9:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)] +1ms
  kafka-node:KafkaClient Sending versions request to 192.168.1.9:9092 +1ms
  kafka-node:KafkaClient Received versions response from 192.168.1.9:9092 +3ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":1,"usable":false},"22":{"min":0,"max":1,"usable":false},"23":{"min":0,"max":2,"usable":false},"24":{"min":0,"max":1,"usable":false},"25":{"min":0,"max":1,"usable":false},"26":{"min":0,"max":1,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":2,"usable":false},"29":{"min":0,"max":1,"usable":false},"30":{"min":0,"max":1,"usable":false},"31":{"min":0,"max":1,"usable":false},"33":{"min":0,"max":1,"usable":false},"34":{"min":0,"max":1,"usable":false},"35":{"min":0,"max":1,"usable":false},"37":{"min":0,"max":1,"usable":false},"38":{"min":0,"max":1,"usable":false},"39":{"min":0,"max":1,"usable":false},"40":{"min":0,"max":1,"usable":false},"41":{"min":0,"max":1,"usable":false},"42":{"min":0,"max":1,"usable":false},"produce":{"min":0,"max":7,"usable":2},"fetch":{"min":0,"max":10,"usable":2},"offset":{"min":0,"max":4,"usable":0},"metadata":{"min":0,"max":7,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":6,"usable":2},"offsetFetch":{"min":0,"max":5,"usable":1},"groupCoordinator":{"min":0,"max":2,"usable":0},"joinGroup":{"min":0,"max":3,"usable":0},"heartbeat":{"min":0,"max":2,"usable":0},"leaveGroup":{"min":0,"max":2,"usable":0},"syncGroup":{"min":0,"max":2,"usable":0},"describeGroups":{"min":0,"max":2,"usable":0},"listGroups":{"min":0,"max":2,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":2,"usable":0},"createTopics":{"min":0,"max":3,"usable":1},"deleteTopics":{"min":0,"max":3,"usable":false},"describeConfigs":{"min":0,"max":2,"usable":0},"saslAuthenticate":{"min":0,"max":0,"usable":0}} +0ms
  kafka-node:KafkaClient broker is now ready +0ms
  kafka-node:KafkaClient createBroker 192.168.1.9 9092 +4ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper 192.168.1.9:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)] +1ms
  kafka-node:KafkaClient Sending versions request to 192.168.1.9:9092 +1ms
  kafka-node:KafkaClient Received versions response from 192.168.1.9:9092 +2ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":1,"usable":false},"22":{"min":0,"max":1,"usable":false},"23":{"min":0,"max":2,"usable":false},"24":{"min":0,"max":1,"usable":false},"25":{"min":0,"max":1,"usable":false},"26":{"min":0,"max":1,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":2,"usable":false},"29":{"min":0,"max":1,"usable":false},"30":{"min":0,"max":1,"usable":false},"31":{"min":0,"max":1,"usable":false},"33":{"min":0,"max":1,"usable":false},"34":{"min":0,"max":1,"usable":false},"35":{"min":0,"max":1,"usable":false},"37":{"min":0,"max":1,"usable":false},"38":{"min":0,"max":1,"usable":false},"39":{"min":0,"max":1,"usable":false},"40":{"min":0,"max":1,"usable":false},"41":{"min":0,"max":1,"usable":false},"42":{"min":0,"max":1,"usable":false},"produce":{"min":0,"max":7,"usable":2},"fetch":{"min":0,"max":10,"usable":2},"offset":{"min":0,"max":4,"usable":0},"metadata":{"min":0,"max":7,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":6,"usable":2},"offsetFetch":{"min":0,"max":5,"usable":1},"groupCoordinator":{"min":0,"max":2,"usable":0},"joinGroup":{"min":0,"max":3,"usable":0},"heartbeat":{"min":0,"max":2,"usable":0},"leaveGroup":{"min":0,"max":2,"usable":0},"syncGroup":{"min":0,"max":2,"usable":0},"describeGroups":{"min":0,"max":2,"usable":0},"listGroups":{"min":0,"max":2,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":2,"usable":0},"createTopics":{"min":0,"max":3,"usable":1},"deleteTopics":{"min":0,"max":3,"usable":false},"describeConfigs":{"min":0,"max":2,"usable":0},"saslAuthenticate":{"min":0,"max":0,"usable":0}} +0ms
  kafka-node:KafkaClient broker is now ready +1ms

Got message: ...
Got message: ...
```

The end of the output is simply all messages on the topic. Re-running this program I expect there to not be any messages, but I see the same output over and over again.

I tried calling `commit` myself, by adding this:

```
process.on('SIGINT', () => {
  consumer.commit(() => process.exit(0));
});
```

The result is:

```
consumer-stream.js:29
  consumer.commit(() => process.exit(0));
           ^

TypeError: consumer.commit is not a function
    at process.on (consumer-stream.js:29:12)
    at emitNone (events.js:106:13)
    at process.emit (events.js:208:7)
    at Signal.wrap.onsignal (internal/process.js:208:44)
```

**Comment by hyperlink** [comment]
use ConsumerGroupStream.

**Comment by cjohansen** [comment]
`ConsumerGroupStream` isn't really a drop-in replacement, though. Currently I'm doing this:

1. Use `Offset` to find the number of partitions for a topic
2. Spin up a `ConsumerStream` for each partition
3. For each partition: Read one message with `.read`, process it, then the next, and so on

This is nice for a few reasons:

1. I can use the number of partitions to control parallelisation
2. I can process messages in parallel, but still only advance one message per partition at a time

With a `ConsumerGroupStream` I would have to implement my own parallelisation mechanism, and it wouldn't consume partitions evenly. So I could end up processing 4 messages from the same partition in parallel, which causes problem if the first of them fail after the three next are completed (and the later offset has been commited).

It would be very nice if `ConsumerStream` worked as advertised. If it isn't supposed to work this way, then at least the documentation should be fixed.

**Comment by cjohansen** [comment]
Ok, scratch that. Just as I wrote that I realized that Kafka will distribute the work among the members of the consumer group for me, so I can just spin up `n` instances of the same consumer group, and retain my current parallelisation scheme. So `ConsumerGroupStream` will work just fine.

Still, I would recommend upadting the docs :)

**Comment by Skwarski** [comment]
Ran into a similar issue as cjohansen. Solved it by using the Offset API to commit the offset (offset + 1 even) once a message was consumed. Its a bit awkward that the documentation for the ConsumerStream says that it has a commit function when it in fact does not.

**Comment by guijob** [comment]
@Skwarski, could you make an example of how to use offset API to make a commit? That's what I've tried:

```
await new Promise((res, rej) => {
    offset.fetch(
        [{ topic: 'pl-occs-topic', partition: 0}],
        (err, data) => { return err ? rej(err) : res(data); }
    );
});
```

But it doesn't work
