### ISSUE TITLE
Consumer group OffsetOutOfRange Error in some containers

### ISSUE THREAD

**Issue by shashanksah** [SOHU-Co/kafka-node#1210]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

## Bug Report
We are using Consumer group to connect to our kafka cluster. We are facing an issue where when the service container is replaced, the new containers starts throwing OffsetOutOfRange continuously. 

From logs, It showed that the cases where this error is coming has offset value as doubled. Given below is one of the value received in production-
"highWaterOffset": 7867
"offset": 15732

When debugging this issue I manually called the consumerGroup.scheduleReconnect(0) function and was able to reproduce the same issue where the offset value is coming as a double of its actual value.

This is a serious bug we are facing in production. Any help is appreciated.

Error stack trace:
{"stack":"Error: OffsetOutOfRange\n    at events.push (/usr/src/app/node_modules/kafka-node/lib/protocol/protocol.js:267:25)\n    at /usr/src/app/node_modules/async/dist/async.js:3880:24\n    at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)\n    at /usr/src/app/node_modules/async/dist/async.js:1016:9\n    at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)\n    at /usr/src/app/node_modules/async/dist/async.js:1046:16\n    at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)\n    at Object.series (/usr/src/app/node_modules/async/dist/async.js:4735:5)\n    at _decodeFetchResponse (/usr/src/app/node_modules/kafka-node/lib/protocol/protocol.js:244:9)\n    at /usr/src/app/node_modules/kafka-node/lib/protocol/protocol.js:199:12\n    at KafkaClient.Client.invokeResponseCallback (/usr/src/app/node_modules/kafka-node/lib/baseClient.js:634:18)\n    at KafkaClient.Client.handleReceivedData (/usr/src/app/node_modules/kafka-node/lib/baseClient.js:614:10)\n    at KafkaClient.handleReceivedData (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:1340:48)\n    at Socket.<anonymous> (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:785:10)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread [as _originalOnread] (net.js:548:20)\n    at TCP.onread (/usr/src/app/node_modules/async-listener/glue.js:188:31)","error":{"topic":"review_inserted","maxNum":1,"partition":10,"time":-1,"metadata":"m"},"name":"Error","message":"OffsetOutOfRange"}

### Environment

* Node version: v6.10.1 and v8.10.0
* Kafka-node version: 4.0.2 (also present in 3.0.1)
* Kafka version: 2.0.0

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 40

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
Calling `scheduleReconnect(0)` will throw an exception and crash your process. Are you sure this is how you reproduced this issue?

**Comment by shashanksah** [comment]
I put the scheduleReconnect(0) in the consumer.on('error', function()..). Then I restarted all the brokers and I got the mentioned error. My process didn't crashed at that time, once the brokers were up again, It continued to  consume some events with incorrect offset and then it stopped consuming. 

I was not able to reproduce this issue, so I was trying random things. This may not be the case with our production though, because we don't call scheduleReconnect(0) anywhere from our code.

Can this case occur if consumerGroup threw an error during initialization?

**Comment by hyperlink** [comment]
What is your `retryMinTimeout` set to?

**Comment by shashanksah** [comment]
retryMinTimeout is set to 5000 ms.
Other Configs for consumer , producer and cluster:
consumerOptions : {
    kafkaHost: "localhost:9092",
    zk : undefined,  
    batch: undefined, 
    ssl: false, 
    sessionTimeout: 15000,
    groupId: '',
    protocol: ['roundrobin'],
    autoCommit: true,
    autoCommitIntervalMs: 5000,
    fromOffset: 'latest', // default
    commitOffsetsOnFirstJoin: true,
    outOfRangeOffset: 'latest',
    migrateHLC: false,
    migrateRolling: true,
    retries: 10000,
    retryFactor: 1,
    retryMinTimeout: 5000
  },
  producerConfig : {
    requireAcks: 1,
    ackTimeoutMs: 300,
    partitionerType: 3
  },
 "clusterConfig" : {
    "autoConnect": true,
    "requestTimeout": 10000,
    "idleConnection": 3600000
  }

**Comment by shashanksah** [comment]
@hyperlink Can you help me with the next action steps? 
Thank you

**Comment by hyperlink** [comment]
Didn't look like your configs could cause `scheduleReconnect(0)` to be called.

I would recommend [turning on debug logger](https://github.com/SOHU-Co/kafka-node#how-do-i-configure-the-log-output) to capture more information on what the ConsumerGroup is doing. It can be a bit verbose but those messages may shed some light on what is happening.

**Comment by mohit3081989** [comment]
Hi @hyperlink ,

Turning debug logger in production is something which is dangerous. I am also facing same issue. I am using container environment on AWS, I started facing the error like :

`{"name":"Error","message":"OffsetOutOfRange","stack":"Error: OffsetOutOfRange\n    at events.push (/usr/src/app/node_modules/kafka-node/lib/protocol/protocol.js:267:25)\n    at /usr/src/app/node_modules/kafka-node/node_modules/async/dist/async.js:3880:24\n    at replenish (/usr/src/app/node_modules/kafka-node/node_modules/async/dist/async.js:1011:17)\n    at /usr/src/app/node_modules/kafka-node/node_modules/async/dist/async.js:1016:9\n    at eachOfLimit (/usr/src/app/node_modules/kafka-node/node_modules/async/dist/async.js:1041:24)\n    at /usr/src/app/node_modules/kafka-node/node_modules/async/dist/async.js:1046:16\n    at _parallel (/usr/src/app/node_modules/kafka-node/node_modules/async/dist/async.js:3879:5)\n    at Object.series (/usr/src/app/node_modules/kafka-node/node_modules/async/dist/async.js:4735:5)\n    at _decodeFetchResponse (/usr/src/app/node_modules/kafka-node/lib/protocol/protocol.js:244:9)\n    at /usr/src/app/node_modules/kafka-node/lib/protocol/protocol.js:199:12\n    at KafkaClient.Client.invokeResponseCallback (/usr/src/app/node_modules/kafka-node/lib/baseClient.js:589:18)\n    at KafkaClient.Client.handleReceivedData (/usr/src/app/node_modules/kafka-node/lib/baseClient.js:569:10)\n    at KafkaClient.handleReceivedData (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:1367:48)\n    at Socket.<anonymous> (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:797:10)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread [as _originalOnread] (net.js:548:20)\n    at TCP.onread (/usr/src/app/node_modules/async-listener/glue.js:188:31)","error":{"topic":"xyz","partition":29,"time":-1,"maxNum":1,"metadata":"m"}}},"level":"error","message":"","timestamp":"2019-04-08T10:02:26.496Z"}`

Just after the deployment. During deployment, docker containers are deregistered from receiving traffic and then gets replaced with new containers. Is it possible that library couldn't right the offset properly for the old containers and they got deleted during that time which might have caused the new containers to not able to fetch right offset ? If yes, how can we fix it quickly ? 

We have seen few errors in broker like : [GroupCoordinator 1001]: Member kafka-node-client-2a4a6b4c-140f-42c3-ba21-dcac17e90611 in group xxxx has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)

Please help, it's impacting the production system for us.

**Comment by mohit3081989** [comment]
@hyperlink I think the latest release of version 4.1.0 has some issue which was released around 19 hours ago. Once we rolled back to the older version of 4.0.2, things got fixed. We were initially using latest minor versions of the library, but now we have made it fixed.

**Comment by hyperlink** [comment]
Could you provide more details about what issues you are seeing in 4.1.0?

**Comment by shashanksah** [comment]
Hi @hyperlink, Looks like your change- 'Fix ConsumerGroup receiving wrong offsets for compressed messages' in 4.1.1 will resolve this issue, right? Or Upgrading to this version may cause some other issues (my ask is based on the comments on this issue- https://github.com/SOHU-Co/kafka-node/issues/1225)?

**Comment by hyperlink** [comment]
@shashanksah I believe all issues related to compressed messages and wrong offsets are now resolved in the latest.

**Comment by shashanksah** [comment]
@hyperlink Thanks for the response. Can you also confirm that the issue pointed out by mohit3081989 above (that the version 4.1.0 also had some issue which caused the production stack to rollback to previous version) is also resolved?

**Comment by hyperlink** [comment]
Sorry, there are lots of different issues being discussed in this thread and I am not clear on what caused @mohit3081989 issue or if it's fixed with the latest. Perhaps he can respond and advise.
