### ISSUE TITLE
TypeError: this.connect is not a function  while creating KafkaClient

### ISSUE THREAD

**Issue by ssbiswal1987** [SOHU-Co/kafka-node#1235]
## Bug Report
Connecting to kafkaClient throws the following error:

`
xyz/kafka-client/node_modules/kafka-node/lib/kafkaClient.js:1
TypeError: this.connect is not a function
    at Proxy.KafkaClient (/Users/swasun/kambi/node-commons/packages/kafka-client/node_modules/kafka-node/lib/kafkaClient.js:83:10)
    at KafkaClient.getClient (/Users/swasun/kambi/node-commons/packages/kafka-client/src/index.js:22:24)
    at KafkaClient.getProducer (/Users/swasun/kambi/node-commons/packages/kafka-client/src/index.js:30:44)
    at KafkaClient.send (/Users/swasun/kambi/node-commons/packages/kafka-client/src/index.js:58:8)
    at Object.<anonymous> (/Users/swasun/kambi/node-commons/packages/kafka-client/src/examples/playground.js:14:7)
    at Generator.next (<anonymous>)
`
### Environment

* Node version: v10.14.2
* Kafka-node version: "^4.1.0"
### Include Sample Code to reproduce behavior

```js
import kafka from 'kafka-node';

const noop = () => {};
const getKafkaHosts = (hosts, port) => {
	const hostsArr = hosts.split(',').map(host => host.trim());
	return hostsArr.map(host => `${host}:${port}`).join(',');
};

export default class KafkaClient {

	constructor(hosts, port) {
		this.defaultConsumerConfig = {
			protocol: ['roundrobin'],
			sessionTimeout: 15000,
			commitOffsetsOnFirstJoin: true,
		};
		this.kafkaHost = getKafkaHosts(hosts, port);
	}

	getClient() {
		if (!this.client) {
			this.client = kafka.KafkaClient({ kafkaHost: this.kafkaHost });
		}

		return this.client;
	}

	getProducer() {
		if (!this.producer) {
			this.producer = new kafka.Producer(this.getClient());
		}

		return this.producer;
	}

	setupListeners(onMessage, onError) {
		this.consumerGroup
			.on('message', onMessage)
			.on('error', onError);
	}

	connect({ groupId, topics, ssl = false }, onMessage, onError) {
		const options = {
			kafkaHost: this.kafkaHost,
			ssl,
			groupId,
			...this.defaults,
		};

		this.consumerGroup = new kafka.ConsumerGroup(options, topics);
		this.setupListeners(onMessage, onError);

		this.client = this.consumerGroup.client;
	}


	send(topic, messages, callback = noop) {
		this.getProducer().send([
			{ topic, messages: JSON.stringify(messages) }],
		(err, data) => {
			if (err) {
				throw new Error('Send Message failed!', err);
			} else {
				callback(data);
			}
		});
	}

	disconnect(callback = noop) {
		this.consumerGroup.close(true, callback);
	}

}
```
and the implementation

```js
import KafkaClient from '../index.js';

const onMessage = (data) => {
	console.log(data);
};

const onError = (err) => {
	console.error(err);
};

const kafka = new KafkaClient('test25-v2.dev.abc.com', '9092');

kafka.send('foggles', { a: 1, b: 3 }, (d) => { console.log(d); });

```
xyz/kafka-client/node_modules/kafka-node/lib/kafkaClient.js:1
TypeError: this.connect is not a function
    at Proxy.KafkaClient (/Users/xyz/node-commons/packages/kafka-client/node_modules/kafka-node/lib/kafkaClient.js:83:10)
    at KafkaClient.getClient (/Users/xyz/node-commons/packages/kafka-client/src/index.js:22:24)
    at KafkaClient.getProducer (/Users/xyz/node-commons/packages/kafka-client/src/index.js:30:44)
    at KafkaClient.send (/Users/xyz/node-commons/packages/kafka-client/src/index.js:58:8)
    at Object.<anonymous> (/Users/xyz/node-commons/packages/kafka-client/src/examples/playground.js:14:7)
    at Generator.next (<anonymous>)

**Comment by hyperlink** [comment]
You need to instantiate the KafkaClient with the `new` keyword.
