### ISSUE TITLE
Producer raises {"nested":{}} error

### ISSUE THREAD

**Issue by Clan-Utility** [SOHU-Co/kafka-node#1241]
In the following code, ` producer.on('error'` will raise {"nested":{}} once in a while (30min, 50min, ...). Any clue on it?

````
  const Kafka = require('kafka-node');
  const kafka = new Kafka.KafkaClient({ kafkaHost: 'localhost:9092' });
  let producer = new Kafka.Producer(kafka);
  producer.on('error', err => {
    console.log(err);
    process.exit(1);
  });

  let consumer = new Kafka.ConsumerGroup({
    kafkaHost: 'localhost:9092',
    groupId: 'myGroupId',
    autoCommit: false
  }, 'Topic1');

  consumer.on('error', err => {
    console.log(err);
    process.exit(1);
  });

  producer.on('ready', () => {
    consumer.on('message', async (rawMessage) => {
       ...
    });
  });
````

**Comment by hyperlink** [comment]
Can you share the full error stack?

**Comment by Clan-Utility** [comment]
`console.log(err)` gives only {"nested":{}}

**Comment by Clan-Utility** [comment]
````
at Producer.producer.on.err (/backend/app-kafka-consumer.js:61:9
)
    at Producer.emit (events.js:188:13)
    at KafkaClient.<anonymous> (/backend/node_modules/kafka-node/lib/basePro
ducer.js:101:10)
    at KafkaClient.emit (events.js:188:13)
    at async.series.error (/backend/node_modules/kafka-node/lib/kafkaClient.
js:165:16)
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:388
8:9
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:473
:16
    at iterateeCallback (/backend/node_modules/kafka-node/node_modules/async
/dist/async.js:988:17)
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:969
:16
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:38
    at KafkaClient.<anonymous> (/backend/node_modules/kafka-node/lib/basePro
ducer.js:101:10)
    at KafkaClient.emit (events.js:188:13)
    at async.series.error (/backend/node_modules/kafka-node/lib/kafkaClient.
js:165:16)
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:388
8:9
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:473
:16
    at iterateeCallback (/backend/node_modules/kafka-node/node_modules/async
/dist/async.js:988:17)
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:969
:16
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:388
5:13
    at async.doWhilst (/backend/node_modules/kafka-node/lib/kafkaClient.js:2
07:9)
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:969
:16
    at next (/backend/node_modules/kafka-node/node_modules/async/dist/async.
js:3022:18)
    at connectToBroker (/backend/node_modules/kafka-node/lib/kafkaClient.js:
188:11)
    at /backend/node_modules/lodash/lodash.js:10052:25
    at onError (/backend/node_modules/kafka-node/lib/kafkaClient.js:234:5)
    at Socket.<anonymous> (/backend/node_modules/kafka-node/lib/kafkaClient.
js:248:5)
    at Socket.emit (events.js:193:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at /backend/node_modules/kafka-node/node_modules/async/dist/async.js:969
:16
    at next (/backend/node_modules/kafka-node/node_modules/async/dist/async.
js:3022:18)
    at connectToBroker (/backend/node_modules/kafka-node/lib/kafkaClient.js:
188:11)
    at /backend/node_modules/lodash/lodash.js:10052:25
    at onError (/backend/node_modules/kafka-node/lib/kafkaClient.js:234:5)
    at Socket.<anonymous> (/backend/node_modules/kafka-node/lib/kafkaClient.
js:248:5)
    at Socket.emit (events.js:193:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/
index.js:138:29)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
{ Error: connect ECONNREFUSED 127.0.0.1:19091
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 }
````

**Comment by Clan-Utility** [comment]
````
at Producer.producer.on.err (/backend/app.js:62:13)
    at Producer.emit (events.js:188:13)
    at KafkaClient.<anonymous> (/backendnode_modules/kafka-node/lib/baseProducer.js:101:10
)
    at KafkaClient.emit (events.js:188:13)
    at async.waterfall (/backendnode_modules/kafka-node/lib/kafkaClient.js:378:21)
    at /backendnode_modules/kafka-node/node_modules/async/dist/async.js:473:16
    at next (/backendnode_modules/kafka-node/node_modules/async/dist/async.js:5329:29)
    at /backendnode_modules/kafka-node/node_modules/async/dist/async.js:969:16
    at KafkaClient.getAvailableBroker (/backendnode_modules/kafka-node/lib/kafkaClient.js:
330:12)
    at async.waterfall.callback (/backendnode_modules/kafka-node/lib/kafkaClient.js:373:23
)
    at nextTask (/backendnode_modules/kafka-node/node_modules/async/dist/async.js:5324:14
)
     at Object.waterfall (/backendnode_modules/kafka-node/node_modules/async/dist/async.js:
5334:5)
    at KafkaClient.refreshBrokerMetadata (/backendnode_modules/kafka-node/lib/kafkaClient.
js:372:9)
    at async.ensureAsync (/backendnode_modules/kafka-node/lib/kafkaClient.js:1039:12)
    at /backendnode_modules/kafka-node/node_modules/async/dist/async.js:3269:12
    at /backendnode_modules/kafka-node/node_modules/async/dist/async.js:74:12
    at /backendnode_modules/kafka-node/lib/kafkaClient.js:1094:13
    at /backendnode_modules/kafka-node/node_modules/async/dist/async.js:3880:24
    at replenish (/backendnode_modules/kafka-node/node_modules/async/dist/async.js:1011:17
)
    at iterateeCallback (/backendnode_modules/kafka-node/node_modules/async/dist/async.js:
995:17)
    at /backendnode_modules/kafka-node/node_modules/async/dist/async.js:969:16
    at /backendnode_modules/kafka-node/node_modules/async/dist/async.js:3885:13
````

**Comment by hyperlink** [comment]
Looks like the kafka address refused connection to the client.

**Comment by Clan-Utility** [comment]
But in most of the time, the client successfully connects to kafka. This error only occurs once or twice in a hour.

**Comment by hyperlink** [comment]
This is a low-level error from node and suggests a network issue with connection to kafka. I would retry send the message again. Does the producer eventually recover its connection?

**Comment by Clan-Utility** [comment]
I use pm2 so the script is automatically restarted by pm2.

**Comment by hyperlink** [comment]
I have not looked at your code in detail but it's not necessary to process.exit when there's an error. kafka-node _should_ recover on its own.
