### ISSUE TITLE
Consumer: ApiVersions failed with unexpected error

### ISSUE THREAD

**Issue by nize** [SOHU-Co/kafka-node#1245]
### Environment

* Node version: 10.13.0
* Kafka-node version: 4.1.1
* Kafka version: 0.10.0.1

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior
show-term-publications.js:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var cgih_kafka_consumer_1 = require("../cgih-kafka-consumer");
var cgihKafkaConsumer = new cgih_kafka_consumer_1.cgihKafkaConsumer();
cgihKafkaConsumer.showTopics();
cgihKafkaConsumer.onTermPublishEvent(function (msg) {
    console.log('The term ' + msg.ASSET_RID + ' was published.');
});
//# sourceMappingURL=show-term-publications.js.map
```
cgih-kafka-consumer.js:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var cgihKafkaConsumer = /** @class */ (function () {
    function cgihKafkaConsumer() {
        var kafka = require('kafka-node');
        var Consumer = kafka.Consumer;
        var client = new kafka.KafkaClient({ kafkaHost: 'xsecgihd001.se.shb.biz:52181' }); // xsecgihd001.se.shb.biz:52181
        this.consumer = new Consumer(client, [
            { topic: 'IgcUnifiedGovEvents', partition: 0 } //IgcUnifiedGovEvents
        ], {
            autoCommit: false
        });
        this.admin = new kafka.Admin(client);
    }
    cgihKafkaConsumer.prototype.onTermPublishEvent = function (callbackMethod) {
        this.consumer.on('message', function (message) {
            console.log(message.value);
            callbackMethod(message.value);
        });
    };
    cgihKafkaConsumer.prototype.showTopics = function () {
        this.admin.listTopics(function (err, res) {
            console.log('topics', res);
        });
    };
    return cgihKafkaConsumer;
}());
exports.cgihKafkaConsumer = cgihKafkaConsumer;
//# sourceMappingURL=cgih-kafka-consumer.js.map
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on
./node-v10.13.0-linux-x64/bin/node dist/cgih-api/samples/show-term-publications.js
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: xsecgihd001.se.shb.biz port: 52181 +3ms
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +10ms
  kafka-node:KafkaClient broker socket connected {"host":"xsecgihd001.se.shb.biz","port":"52181"} +4ms
  kafka-node:KafkaClient connected to socket, trying to load initial metadata +1ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +0ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper xsecgihd001.se.shb.biz:52181 (connected: true) (ready: fals                                                                                                                e) (idle: false) (needAuthentication: false) (authenticated: false)] +0ms
  kafka-node:Consumer connection closed +2ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +2ms
  kafka-node:KafkaClient kafka-node-client reconnecting to xsecgihd001.se.shb.biz:52181 +999ms
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +1ms
  kafka-node:Consumer connection closed +1ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +1ms
  kafka-node:KafkaClient kafka-node-client reconnecting to xsecgihd001.se.shb.biz:52181 +1s
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +1ms
  kafka-node:Consumer connection closed +1ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient kafka-node-client reconnecting to xsecgihd001.se.shb.biz:52181 +1s
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:Consumer connection closed +1ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient kafka-node-client reconnecting to xsecgihd001.se.shb.biz:52181 +1s
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +1ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:Consumer connection closed +1ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient kafka-node-client reconnecting to xsecgihd001.se.shb.biz:52181 +1s
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +1ms
  kafka-node:Consumer connection closed +1ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient kafka-node-client reconnecting to xsecgihd001.se.shb.biz:52181 +1s
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +1ms
  kafka-node:Consumer connection closed +1ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient kafka-node-client reconnecting to xsecgihd001.se.shb.biz:52181 +1s
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +1ms
  kafka-node:Consumer connection closed +1ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient kafka-node-client reconnecting to xsecgihd001.se.shb.biz:52181 +1s
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +1ms
  kafka-node:Consumer connection closed +1ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient kafka-node-client reconnecting to xsecgihd001.se.shb.biz:52181 +1s
  kafka-node:KafkaClient kafka-node-client createBroker xsecgihd001.se.shb.biz:52181 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to xsecgihd001.se.shb.biz:52181 +1ms
  kafka-node:Consumer connection closed +1ms
  kafka-node:KafkaClient kafka-node-client socket closed xsecgihd001.se.shb.biz:52181 (hadError: false) +0ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available                                                                                                                 (socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (                                                                                                                socket closed)
    at new BrokerNotAvailableError (/usr/users/zeni50/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.j                                                                                                                s:11:9)
    at Socket.<anonymous> (/usr/users/zeni50/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms

**Comment by hyperlink** [comment]
Looks like the broker is disconnecting your socket. I've seen this happen when trying to connect to a TLS port and it's not enabled in the client.

**Comment by nize** [comment]
I tested the option `ssl: true` but then I got other error messages.

So then I changed to `kafkaHost: 'xsecgihd001.se.shb.biz:59092'` (another port). This resulted in the `cgihKafkaConsumer.showTopics();` giving output as expected!

However, still I don't get any output which I expect from `cgihKafkaConsumer.onTermPublishEvent`.

When I run the kafka tool

`./kafka-console-consumer.sh --zookeeper xsecgihd001.se.shb.biz:52181 --topic IgcUnifiedGovEvents`

I get message outputs:

`{"XMETA_TYPE":"GlossaryExtensions.BusinessTerm","ACTION":"APPROVE","TIMESTAMP":"1556188964204","ASSET_TYPE":"Term","eventType":"KNOWLEDGE_GRAPH","USER":"ZENI50","WORKFLOW":"true","ASSET_RID":"6662fff2.e1b1ec6c.25cmkauut.3ehhk3d.fa6ftk.ubak6849uufsce18csl8n"}
`

But in the same time I get no output at all from my script `show-term-publications.js`.

Do you understand why?

**Comment by hyperlink** [comment]
`kafkaHost` should only be assigned the address to the kafka broker not zookeeper. This module no longer supports zookeeper based connections.

I'm not sure what you are trying to do with `onTermPublishEvent`. Take a look at examples in the examples folder in this project. Also, I would recommend you use for `ConsumerGroup` which is a higher level consumer. Good luck.

**Comment by nize** [comment]
When I switched to use `ConsumerGroup` instead of `Consumer` I got it working.

I guess the problem I had before was that there was another consumer (in the same group for some reason) reading messages posted to the topic. When I specified my own group I got the messages.

```
constructor() {
	let kafka = require('kafka-node');
	let ConsumerGroup = kafka.ConsumerGroup;
	this.consumer = new ConsumerGroup({ kafkaHost: 'xsecgih001.se.shb.biz:59092', groupId: 'nils-group' },'IgcUnifiedGovEvents');
}
```
