### ISSUE TITLE
brokerForLeader - choosing first broker as leader bug

### ISSUE THREAD

**Issue by chosh31** [SOHU-Co/kafka-node#1251]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version: 10.5.0
* Kafka-node version: 4.1.1
* Kafka version: 2.1.1cp1

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

`brokerForLeader` not checked `broker.isConnected()`
1. running three brokers (kafka-host:9092/ kafka-host:9093/ kafka-host:9094)
2. second broker leader / first broker, third broker follow
3. second broker shutdown -> (changed broker leader) -> third broker
4. third broker shutdown -> (changed broker leader) -> first broker
5. restart second broker & third broker
6. first broker shutdown -> (changed broker leader) -> (retry first broker connect)  -> occur error

```sh
=====(shutdown first broker)=====

kafka-node-client socket closed kafka-host:9092 (hadError: false)
kafka-node-client schedule refreshBrokerMetadata()
kafka-node-client refreshBrokerMetadata()
Trying to connect to host: kafka-host port: 9094
kafka-node-client createBroker kafka-host:9094
kafka-node-client sending versions request to kafka-host:9094
broker socket connected {"nodeId":3,"host":"kafka-host","port":9094}
waitUntilReady [BrokerWrapper kafka-host:9094 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)]
Received versions response from kafka-host:9094
setting api support to {"21":{"min":0,"max":1,"usable":false},"22":{"min":0,"max":1,"usable":false},"23":{"min":0,"max":2,"usable":false},"24":{"min":0,"max":1,"usable":false},"25":{"min":0,"max":1,"usable":false},"26":{"min":0,"max":1,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":2,"usable":false},"29":{"min":0,"max":1,"usable":false},"30":{"min":0,"max":1,"usable":false},"31":{"min":0,"max":1,"usable":false},"33":{"min":0,"max":1,"usable":false},"34":{"min":0,"max":1,"usable":false},"35":{"min":0,"max":1,"usable":false},"37":{"min":0,"max":1,"usable":false},"38":{"min":0,"max":1,"usable":false},"39":{"min":0,"max":1,"usable":false},"40":{"min":0,"max":1,"usable":false},"41":{"min":0,"max":1,"usable":false},"42":{"min":0,"max":1,"usable":false},"produce":{"min":0,"max":7,"usable":2},"fetch":{"min":0,"max":10,"usable":2},"offset":{"min":0,"max":4,"usable":0},"metadata":{"min":0,"max":7,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":6,"usable":2},"offsetFetch":{"min":0,"max":5,"usable":1},"groupCoordinator":{"min":0,"max":2,"usable":0},"joinGroup":{"min":0,"max":3,"usable":0},"heartbeat":{"min":0,"max":2,"usable":0},"leaveGroup":{"min":0,"max":2,"usable":0},"syncGroup":{"min":0,"max":2,"usable":0},"describeGroups":{"min":0,"max":2,"usable":0},"listGroups":{"min":0,"max":2,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":2,"usable":0},"createTopics":{"min":0,"max":3,"usable":1},"deleteTopics":{"min":0,"max":3,"usable":false},"describeConfigs":{"min":0,"max":2,"usable":0},"saslAuthenticate":{"min":0,"max":0,"usable":0}}
broker is now ready
kafka-node-client updated internal metadata
refresh metadata currentAttempt 1
refresh metadata currentAttempt 2
compressing messages if needed
kafka-node-client createBroker kafka-host:9093
missing apiSupport waiting until broker is ready...
waitUntilReady [BrokerWrapper kafka-host:9093 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)]
refresh metadata currentAttempt 3
kafka-node-client sending versions request to kafka-host:9093
Received versions response from kafka-host:9093
setting api support to {"21":{"min":0,"max":1,"usable":false},"22":{"min":0,"max":1,"usable":false},"23":{"min":0,"max":2,"usable":false},"24":{"min":0,"max":1,"usable":false},"25":{"min":0,"max":1,"usable":false},"26":{"min":0,"max":1,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":2,"usable":false},"29":{"min":0,"max":1,"usable":false},"30":{"min":0,"max":1,"usable":false},"31":{"min":0,"max":1,"usable":false},"33":{"min":0,"max":1,"usable":false},"34":{"min":0,"max":1,"usable":false},"35":{"min":0,"max":1,"usable":false},"37":{"min":0,"max":1,"usable":false},"38":{"min":0,"max":1,"usable":false},"39":{"min":0,"max":1,"usable":false},"40":{"min":0,"max":1,"usable":false},"41":{"min":0,"max":1,"usable":false},"42":{"min":0,"max":1,"usable":false},"produce":{"min":0,"max":7,"usable":2},"fetch":{"min":0,"max":10,"usable":2},"offset":{"min":0,"max":4,"usable":0},"metadata":{"min":0,"max":7,"usable":1},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":6,"usable":2},"offsetFetch":{"min":0,"max":5,"usable":1},"groupCoordinator":{"min":0,"max":2,"usable":0},"joinGroup":{"min":0,"max":3,"usable":0},"heartbeat":{"min":0,"max":2,"usable":0},"leaveGroup":{"min":0,"max":2,"usable":0},"syncGroup":{"min":0,"max":2,"usable":0},"describeGroups":{"min":0,"max":2,"usable":0},"listGroups":{"min":0,"max":2,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":1},"apiVersions":{"min":0,"max":2,"usable":0},"createTopics":{"min":0,"max":3,"usable":1},"deleteTopics":{"min":0,"max":3,"usable":false},"describeConfigs":{"min":0,"max":2,"usable":0},"saslAuthenticate":{"min":0,"max":0,"usable":0}}
broker is now ready
kafka-node-client is not reconnecting to kafka-host:9092 invalid broker
refresh metadata currentAttempt 4
compressing messages if needed
refresh metadata currentAttempt 5
compressing messages if needed
refresh metadata currentAttempt 6
compressing messages if needed
refresh metadata currentAttempt 7
compressing messages if needed
refresh metadata currentAttempt 8
compressing messages if needed
refresh metadata currentAttempt 9
compressing messages if needed
refresh metadata currentAttempt 10
compressing messages if needed
refresh metadata currentAttempt 11
refresh metadata error Broker not available (loadMetadataForTopics)

events.js:167
      throw er; // Unhandled 'error' event
      ^
BrokerNotAvailableError: Broker not available (loadMetadataForTopics)
    at new BrokerNotAvailableError (/Users/shcho/git/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.loadMetadataForTopics (/Users/shcho/git/kafka-node/lib/kafkaClient.js:892:21)
    at RetryOperation._fn (/Users/shcho/git/kafka-node/lib/baseClient.js:360:12)
    at Timeout._onTimeout (/Users/shcho/git/kafka-node/node_modules/retry/lib/retry_operation.js:68:10)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Emitted 'error' event at:
    at /Users/shcho/git/kafka-node/lib/baseProducer.js:96:14
    at /Users/shcho/git/kafka-node/lib/baseClient.js:370:18
    at KafkaClient.loadMetadataForTopics (/Users/shcho/git/kafka-node/lib/kafkaClient.js:892:12)
    at RetryOperation._fn (/Users/shcho/git/kafka-node/lib/baseClient.js:360:12)
    [... lines matching original stack trace ...]
    at Timer.processTimers (timers.js:212:10)
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by chosh31** [comment]
@hyperlink 
What is your opinion on this issue?

**Comment by chosh31** [comment]
I misunderstood the code
