### ISSUE TITLE
simple consumer is always in lag of 1

### ISSUE THREAD

**Issue by dotanrs** [SOHU-Co/kafka-node#1267]
### Environment

* Node version: v8.11.1
* Kafka-node version: 4.0.1
* Kafka version: 2.11-0.10.1.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

## Bug Report

I created a very basic consumer, and looked at the offsets in kafka.
after sending one message, the consumer's offset stayed at 0 with LAG 1.
whenever I sent another message it read it properly but still had a lag of 1.
So I figured if I restart the consumer it will read the last message again, and this is indeed what happened.

The consumer code:
```
const topicsList = [consts.topicName];
const consumerOptions = {
  kafkaHost,
  groupId: consts.consumerGroupName,
  topicsList,
  sessionTimeout: 30000,
  protocol: ['roundrobin'],
  fromOffset: 'latest',
  autoCommit: false,
};

const consumer = new kafka.ConsumerGroup(consumerOptions, topicsList);

consumer.on('message', message => {
  console.log(`received ${JSON.stringify(message)}`);
  consumer.commit(true, (err, data) => {
    console.log(`json data: ${JSON.stringify(data)}`);
    console.log(`err : ${err} `);
  });
});

consumer.on('error', e => {
  console.error('Got error in consumer!');
  console.error(e);
});
```

debug logs:
note that I only sent one message in the first run, non in the second.

__first run:__
>  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: host.docker.internal port: 9092 +2ms
  kafka-node:KafkaClient createBroker host.docker.internal 9092 +1ms
consumer working... ^C to exit
  kafka-node:KafkaClient Sending versions request to host.docker.internal:9092 +4ms
  kafka-node:KafkaClient broker socket connected {"host":"host.docker.internal","port":"9092"} +2ms
  kafka-node:KafkaClient connected to socket, trying to load initial metadata +0ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +1ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper host.docker.internal:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)] +0ms
  kafka-node:KafkaClient Received versions response from host.docker.internal:9092 +2ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":2,"usable":2},"fetch":{"min":0,"max":3,"usable":2},"offset":{"min":0,"max":1,"usable":0},"metadata":{"min":0,"max":2,"usable":1},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":2,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":1,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":{"min":0,"max":0,"usable":0},"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":{"min":0,"max":0,"usable":0},"deleteTopics":{"min":0,"max":0,"usable":false}} +0ms
  kafka-node:KafkaClient broker is now ready +1ms
  kafka-node:KafkaClient updating metadatas +11ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +0ms
  kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: 'host.docker.internal',
  coordinatorPort: 9092,
  coordinatorId: 0 } +3ms
  kafka-node:ConsumerGroup joinGroupResponse {"members":[{"subscription":["ExampleTopic21"],"version":0,"id":"kafka-node-client-b4f47c26-80ac-4a78-8759-884fdf3d24ef"}],"generationId":1,"groupProtocol":"roundrobin","leaderId":"kafka-node-client-b4f47c26-80ac-4a78-8759-884fdf3d24ef","memberId":"kafka-node-client-b4f47c26-80ac-4a78-8759-884fdf3d24ef"} from kafka-node-client +4ms
  kafka-node:ConsumerGroup Assigning Partitions to members [ { subscription: [ 'ExampleTopic21' ],
    version: 0,
    userData: undefined,
    id: 'kafka-node-client-b4f47c26-80ac-4a78-8759-884fdf3d24ef' } ] +1ms
  kafka-node:ConsumerGroup Using group protocol roundrobin +0ms
  kafka-node:ConsumerGroup loadingMetadata for topics: [ 'ExampleTopic21' ] +2ms
  kafka-node:ConsumerGroup mapTopicToPartitions {} +15ms
  kafka-node:Roundrobin topicPartition: {} +1ms
  kafka-node:Roundrobin groupMembers: [{"subscription":["ExampleTopic21"],"version":0,"id":"kafka-node-client-b4f47c26-80ac-4a78-8759-884fdf3d24ef"}] +0ms
  kafka-node:Roundrobin members [ 'kafka-node-client-b4f47c26-80ac-4a78-8759-884fdf3d24ef' ] +0ms
  kafka-node:Roundrobin subscribers { 'kafka-node-client-b4f47c26-80ac-4a78-8759-884fdf3d24ef': [ 'ExampleTopic21' ] } +0ms
  kafka-node:Roundrobin round robin on topic partition pairs:  [] +0ms
  kafka-node:ConsumerGroup SyncGroup Request from kafka-node-client-b4f47c26-80ac-4a78-8759-884fdf3d24ef +1ms
  kafka-node:ConsumerGroup SyncGroup Response +6ms
  kafka-node:ConsumerGroup generationId 1 +0ms
  kafka-node:ConsumerGroup startFetch is false +0ms
  kafka-node:ConsumerGroup kafka-node-client is leader scheduled new topic/partition check +0ms
  kafka-node:ConsumerGroup kafka-node-client started heartbeats at every 10000 ms +1ms
  kafka-node:ConsumerGroup checking for new topics and partitions +30s
  kafka-node:ConsumerGroup Topic/Partitions has changed +4ms
  kafka-node:ConsumerGroup kafka-node-client leaving group +0ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +3ms
  kafka-node:ConsumerGroup GroupCoordinator Response: null +0ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { UnknownMemberId: Kafka Error Code: 25
    at new UnknownMemberId (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/errors/UnknownMemberIdError.js:4:9)
    at createGroupError (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/protocol/protocol.js:1395:15)
    at Object.self.tap (/Users/dotanreis/src/kafka-api/node_modules/binary/index.js:248:12)
    at decodeJoinGroupResponse (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/protocol/protocol.js:1394:6)
    at KafkaClient.Client.invokeResponseCallback (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 25', errorCode: 25 } +2ms
  kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 1000 ms { UnknownMemberId: Kafka Error Code: 25
    at new UnknownMemberId (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/errors/UnknownMemberIdError.js:4:9)
    at createGroupError (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/protocol/protocol.js:210:13)
    at Object.<anonymous> (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/protocol/protocol.js:1395:15)
    at Object.self.tap (/Users/dotanreis/src/kafka-api/node_modules/binary/index.js:248:12)
    at decodeJoinGroupResponse (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/protocol/protocol.js:1394:6)
    at KafkaClient.Client.invokeResponseCallback (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/baseClient.js:634:18)
    at KafkaClient.Client.handleReceivedData (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/baseClient.js:614:10)
    at KafkaClient.handleReceivedData (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/kafkaClient.js:1340:48)
    at Socket.<anonymous> (/Users/dotanreis/src/kafka-api/node_modules/kafka-node/lib/kafkaClient.js:785:10)
    at emitOne (events.js:116:13) message: 'Kafka Error Code: 25', errorCode: 25 } +2ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +1s
  kafka-node:ConsumerGroup GroupCoordinator Response: null +0ms
  kafka-node:ConsumerGroup joinGroupResponse {"members":[{"subscription":["ExampleTopic21"],"version":0,"id":"kafka-node-client-a7a07b44-e51a-471b-9898-07c33081c4b0"}],"generationId":3,"groupProtocol":"roundrobin","leaderId":"kafka-node-client-a7a07b44-e51a-471b-9898-07c33081c4b0","memberId":"kafka-node-client-a7a07b44-e51a-471b-9898-07c33081c4b0"} from kafka-node-client +4ms
  kafka-node:ConsumerGroup Assigning Partitions to members [ { subscription: [ 'ExampleTopic21' ],
    version: 0,
    userData: undefined,
    id: 'kafka-node-client-a7a07b44-e51a-471b-9898-07c33081c4b0' } ] +0ms
  kafka-node:ConsumerGroup Using group protocol roundrobin +0ms
  kafka-node:ConsumerGroup loadingMetadata for topics: [ 'ExampleTopic21' ] +0ms
  kafka-node:ConsumerGroup mapTopicToPartitions { ExampleTopic21: [ '0' ] } +4ms
  kafka-node:Roundrobin topicPartition: {"ExampleTopic21":["0"]} +0ms
  kafka-node:Roundrobin groupMembers: [{"subscription":["ExampleTopic21"],"version":0,"id":"kafka-node-client-a7a07b44-e51a-471b-9898-07c33081c4b0"}] +0ms
  kafka-node:Roundrobin members [ 'kafka-node-client-a7a07b44-e51a-471b-9898-07c33081c4b0' ] +0ms
  kafka-node:Roundrobin subscribers { 'kafka-node-client-a7a07b44-e51a-471b-9898-07c33081c4b0': [ 'ExampleTopic21' ] } +0ms
  kafka-node:Roundrobin round robin on topic partition pairs:  [ { topic: 'ExampleTopic21', partition: '0' } ] +0ms
  kafka-node:ConsumerGroup SyncGroup Request from kafka-node-client-a7a07b44-e51a-471b-9898-07c33081c4b0 +1ms
  kafka-node:ConsumerGroup SyncGroup Response +4ms
  kafka-node:ConsumerGroup kafka-node-client owns topics:  { ExampleTopic21: [ 0 ] } +0ms
  kafka-node:ConsumerGroup kafka-node-client fetchOffset Response: {"ExampleTopic21":{"0":-1}} +6ms
  kafka-node:ConsumerGroup No saved offsets +0ms
  kafka-node:KafkaClient updating metadatas +3ms
  kafka-node:ConsumerGroup kafka-node-client defaultOffset Response for latest: {"ExampleTopic21":{"0":0}} +4ms
  kafka-node:ConsumerGroup generationId 3 +4ms
  kafka-node:ConsumerGroup startFetch is true +0ms
  kafka-node:KafkaClient createBroker host.docker.internal 9092 +1ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +1ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper host.docker.internal:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)] +0ms
  kafka-node:ConsumerGroup kafka-node-client is leader scheduled new topic/partition check +0ms
  kafka-node:ConsumerGroup kafka-node-client started heartbeats at every 10000 ms +0ms
  kafka-node:KafkaClient Sending versions request to host.docker.internal:9092 +1ms
  kafka-node:KafkaClient Received versions response from host.docker.internal:9092 +5ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":2,"usable":2},"fetch":{"min":0,"max":3,"usable":2},"offset":{"min":0,"max":1,"usable":0},"metadata":{"min":0,"max":2,"usable":1},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":2,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":1,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":{"min":0,"max":0,"usable":0},"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":{"min":0,"max":0,"usable":0},"deleteTopics":{"min":0,"max":0,"usable":false}} +0ms
  kafka-node:KafkaClient broker is now ready +0ms
**received {"topic":"ExampleTopic21","value":"\"{\\\"message\\\":\\\"this is the message: 1558020744\\\"}\"","offset":0,"partition":0,"highWaterOffset":1,"key":"key1","timestamp":"2019-05-16T15:32:24.828Z"}**
json data: {"ExampleTopic21":{"partition":0,"errorCode":0}}
err : null

__second run:__
>  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: host.docker.internal port: 9092 +2ms
  kafka-node:KafkaClient createBroker host.docker.internal 9092 +0ms
consumer working... ^C to exit
  kafka-node:KafkaClient Sending versions request to host.docker.internal:9092 +5ms
  kafka-node:KafkaClient broker socket connected {"host":"host.docker.internal","port":"9092"} +1ms
  kafka-node:KafkaClient connected to socket, trying to load initial metadata +1ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +0ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper host.docker.internal:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)] +0ms
  kafka-node:KafkaClient Received versions response from host.docker.internal:9092 +3ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":2,"usable":2},"fetch":{"min":0,"max":3,"usable":2},"offset":{"min":0,"max":1,"usable":0},"metadata":{"min":0,"max":2,"usable":1},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":2,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":1,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":{"min":0,"max":0,"usable":0},"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":{"min":0,"max":0,"usable":0},"deleteTopics":{"min":0,"max":0,"usable":false}} +0ms
  kafka-node:KafkaClient broker is now ready +1ms
  kafka-node:KafkaClient updating metadatas +9ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +0ms
  kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: 'host.docker.internal',
  coordinatorPort: 9092,
  coordinatorId: 0 } +3ms
  kafka-node:ConsumerGroup joinGroupResponse {"members":[{"subscription":["ExampleTopic21"],"version":0,"id":"kafka-node-client-b2d388d7-e8c9-41f4-ae28-a86c67abee29"}],"generationId":4,"groupProtocol":"roundrobin","leaderId":"kafka-node-client-b2d388d7-e8c9-41f4-ae28-a86c67abee29","memberId":"kafka-node-client-b2d388d7-e8c9-41f4-ae28-a86c67abee29"} from kafka-node-client +27s
  kafka-node:ConsumerGroup Assigning Partitions to members [ { subscription: [ 'ExampleTopic21' ],
    version: 0,
    userData: undefined,
    id: 'kafka-node-client-b2d388d7-e8c9-41f4-ae28-a86c67abee29' } ] +0ms
  kafka-node:ConsumerGroup Using group protocol roundrobin +2ms
  kafka-node:ConsumerGroup loadingMetadata for topics: [ 'ExampleTopic21' ] +2ms
  kafka-node:ConsumerGroup mapTopicToPartitions { ExampleTopic21: [ '0' ] } +3ms
  kafka-node:Roundrobin topicPartition: {"ExampleTopic21":["0"]} +0ms
  kafka-node:Roundrobin groupMembers: [{"subscription":["ExampleTopic21"],"version":0,"id":"kafka-node-client-b2d388d7-e8c9-41f4-ae28-a86c67abee29"}] +0ms
  kafka-node:Roundrobin members [ 'kafka-node-client-b2d388d7-e8c9-41f4-ae28-a86c67abee29' ] +0ms
  kafka-node:Roundrobin subscribers { 'kafka-node-client-b2d388d7-e8c9-41f4-ae28-a86c67abee29': [ 'ExampleTopic21' ] } +0ms
  kafka-node:Roundrobin round robin on topic partition pairs:  [ { topic: 'ExampleTopic21', partition: '0' } ] +1ms
  kafka-node:ConsumerGroup SyncGroup Request from kafka-node-client-b2d388d7-e8c9-41f4-ae28-a86c67abee29 +0ms
  kafka-node:ConsumerGroup SyncGroup Response +5ms
  kafka-node:ConsumerGroup kafka-node-client owns topics:  { ExampleTopic21: [ 0 ] } +0ms
  kafka-node:ConsumerGroup kafka-node-client fetchOffset Response: {"ExampleTopic21":{"0":0}} +2ms
  kafka-node:ConsumerGroup Has saved offsets +1ms
  kafka-node:ConsumerGroup generationId 4 +0ms
  kafka-node:ConsumerGroup startFetch is true +0ms
  kafka-node:KafkaClient createBroker host.docker.internal 9092 +2ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +0ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper host.docker.internal:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)] +0ms
  kafka-node:ConsumerGroup kafka-node-client is leader scheduled new topic/partition check +0ms
  kafka-node:ConsumerGroup kafka-node-client started heartbeats at every 10000 ms +1ms
  kafka-node:KafkaClient Sending versions request to host.docker.internal:9092 +0ms
  kafka-node:KafkaClient Received versions response from host.docker.internal:9092 +3ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":2,"usable":2},"fetch":{"min":0,"max":3,"usable":2},"offset":{"min":0,"max":1,"usable":0},"metadata":{"min":0,"max":2,"usable":1},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":2,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":1,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":{"min":0,"max":0,"usable":0},"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":{"min":0,"max":0,"usable":0},"deleteTopics":{"min":0,"max":0,"usable":false}} +0ms
  kafka-node:KafkaClient broker is now ready +1ms
**received {"topic":"ExampleTopic21","value":"\"{\\\"message\\\":\\\"this is the message: 1558020744\\\"}\"","offset":0,"partition":0,"highWaterOffset":1,"key":"key1","timestamp":"2019-05-16T15:32:24.828Z"}**
json data: {"ExampleTopic21":{"partition":0,"errorCode":0}}
err : null

**Comment by hyperlink** [comment]
The internal offsets are not updated until after all messages are emitted so the offsets you are committing will "lag" behind. Commits are also throttled so I don't think your approach will work.

I would suggest trying out the ConsumerGroupStream which will eventually commit all the offsets of any messages read from the stream.
