### ISSUE TITLE
Receive InvalidMessage when produce message

### ISSUE THREAD

**Issue by qizigod** [SOHU-Co/kafka-node#1271]
## Bug Report
```
Error: InvalidMessage
    at Object.<anonymous> (/Users/ziqi/Documents/kafka-node/lib/protocol/protocol.js:928:17)
    at Object.self.tap (/Users/ziqi/Documents/kafka-node/node_modules/binary/index.js:248:12)
    at Object.decodePartitions (/Users/ziqi/Documents/kafka-node/lib/protocol/protocol.js:926:73)
    at Object.self.loop (/Users/ziqi/Documents/kafka-node/node_modules/binary/index.js:267:16)
    at Object.<anonymous> (/Users/ziqi/Documents/kafka-node/lib/protocol/protocol.js:165:8)
    at Object.self.loop (/Users/ziqi/Documents/kafka-node/node_modules/binary/index.js:267:16)
    at decodeProduceV1Response (/Users/ziqi/Documents/kafka-node/lib/protocol/protocol.js:920:6)
    at KafkaClient.Client.invokeResponseCallback (/Users/ziqi/Documents/kafka-node/lib/baseClient.js:589:18)
    at KafkaClient.Client.handleReceivedData (/Users/ziqi/Documents/kafka-node/lib/baseClient.js:569:10)
    at KafkaClient.handleReceivedData (/Users/ziqi/Documents/kafka-node/lib/kafkaClient.js:1373:48)
```
Producer produce message failed, When `getApiVersions` timeout and `attributes` is not 0.  

### Environment

* Node version: 8.11.3
* Kafka-node version: 4.1.3
* Kafka version: 2.2.0

```js
function compress (payloads, callback) {
  async.each(payloads, buildRequest, callback);

  function buildRequest (payload, cb) {
    const attributes = payload.attributes;
    const codec = getCodec(attributes);

    if (!codec) return cb(null);
    
    const innerSet = encodeMessageSet(payload.messages, 1); // this should not be 1, but should be obtained from apiMap
    codec.encode(innerSet, function (err, message) {
      if (err) return cb(err);
      payload.messages = [new Message(0, attributes, payload.key, message)];
      cb(null);
    });
  }
}
```
Here apiVersion fallback to `baseProtocolVersions`, and produce apiVersion is 0. `compress` should `encodeMessageSet` with 0 version.

**Comment by baolinCloud** [comment]
I got the similar error when produce msg.

kafka-node version: 2.2.3
node version: 6.9.1


```
error: { stack: 'Error: InvalidMessage\n at Object.<anonymous> (/node_modules/kafka-node/lib/protocol/protocol.js:539:17)\n at Object.self.tap (/node_modules/kafka-node/node_modules/binary/index.js:248:12)\n at Object.decodePartitions 
(/node_modules/kafka-node/lib/protocol/protocol.js:537:95)\n at Object.self.loop 
(/node_modules/kafka-node/node_modules/binary/index.js:267:16)\n at Object.<anonymous> 
(/node_modules/kafka-node/lib/protocol/protocol.js:56:8)\n at Object.self.loop 
(/node_modules/kafka-node/node_modules/binary/index.js:267:16)\n at decodeProduceV2Response 
(/node_modules/kafka-node/lib/protocol/protocol.js:531:6)\n at KafkaClient.Client.handleReceivedData 
(/node_modules/kafka-node/lib/client.js:763:20)\n at Socket.<anonymous> 
(/node_modules/kafka-node/lib/kafkaClient.js:523:10)\n at emitOne (events.js:96:13)\n at Socket.emit (events.js:188:7)' }


```

**Comment by viinay** [comment]
I got the similar error when producing message.
kafka-node version : 4.1.3
node version : 8.14.0

**Comment by prolificeric** [comment]
I had a similar issue and fixed it by specifying a `key` in the message object.

**Comment by zhaoleipeng** [comment]
please fix this bug. i also have this problem. the same message sometime  will be show InvalidMessage sometime is success

**Comment by gkop** [comment]
I observe this issue only when kafka-node tries to reconnect to a broker that has just rebooted, kafka-node doesn't correctly wait for the broker to initialize, the protocol versions query times out, and kafka-node falls back to the kafka 0.9 protocol versions. My quick workaround is to detect when a kafka-node client broker's `apiVersion` is equal to the base protocol version, and in those circumstances call `refreshBrokerMetadata()` on the client to attempt again to pull the correct versions.

I'd be glad to contribute a patch to this library, but it doesn't seem maintained :(
