### ISSUE TITLE
ERR_INVALID_ARG_TYPE error on trying to instantiate ConsumerGroup

### ISSUE THREAD

**Issue by 4ditya** [SOHU-Co/kafka-node#1290]
## Bug Report

On Trying to instantiate a consumer group,  I get the following error:

```
buffer.js:515
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:515:11)
    at BufferMaker.make (/data/app/node_modules/buffermaker/lib/BufferMaker.js:50:29)
    at _encodeProtocolData (/data/app/node_modules/kafka-node/lib/protocol/protocol.js:1217:47)
    at BufferMaker.encodeGroupProtocol (/data/app/node_modules/kafka-node/lib/protocol/protocol.js:1200:67)
    at Array.forEach (<anonymous>)
    at encodeJoinGroupRequest (/data/app/node_modules/kafka-node/lib/protocol/protocol.js:1389:18)
    at KafkaClient.Client.sendGroupRequest (/data/app/node_modules/kafka-node/lib/baseClient.js:176:24)
    at KafkaClient.Client.sendJoinGroupRequest (/data/app/node_modules/kafka-node/lib/baseClient.js:197:8)
    at /data/app/node_modules/kafka-node/lib/consumerGroup.js:543:21
    at nextTask (/data/app/node_modules/async/dist/async.js:5324:14)
    at next (/data/app/node_modules/async/dist/async.js:5331:9)
    at /data/app/node_modules/async/dist/async.js:969:16
    at KafkaClient.wrappedFn (/data/app/node_modules/kafka-node/lib/kafkaClient.js:481:14)
    at KafkaClient.Client.invokeResponseCallback (/data/app/node_modules/kafka-node/lib/baseClient.js:593:10)
    at KafkaClient.Client.handleReceivedData (/data/app/node_modules/kafka-node/lib/baseClient.js:569:10)
    at KafkaClient.handleReceivedData (/data/app/node_modules/kafka-node/lib/kafkaClient.js:1367:48)
```

### Environment

* Node version: 10.16.0
* Kafka-node version: 4.1.3
* Kafka version: 2.11-0.10.2.1

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

```js
const TOPICS = [
	{ topic: "CREATE_CATEGORY", partition: 0 },
	{ topic: 'GET_CATEGORIES', partition: 0 },
	{ topic: 'UPDATE_CATEGORY', partition: 0 },
];

const options = {
		kafkaHost: kafkaConfig.kafka_server, // connect directly to kafka broker (instantiates a KafkaClient)
		batch: undefined, // put client batch settings if you need them
		groupId: 'consumerSvcGroup',
		sessionTimeout: 15000,
		// An array of partition assignment protocols ordered by preference.
		// 'roundrobin' or 'range' string for built ins (see below to pass in custom assignment protocol)
		protocol: ['roundrobin'],
		encoding: 'utf8', // default is utf8, use 'buffer' for binary data
		// Offsets to use for new groups other options could be 'earliest' or 'none' (none will emit an error if no offsets were saved)
		// equivalent to Java client's auto.offset.reset
		fromOffset: 'latest', // default
		commitOffsetsOnFirstJoin: true, // on the very first time this consumer group subscribes to a topic, record the offset returned in fromOffset (latest/earliest)
		// how to recover from OutOfRangeOffset error (where save offset is past server retention) accepts same value as fromOffset
		outOfRangeOffset: 'earliest', // default
	};


	consumerGroup = new kafka.ConsumerGroup(options, TOPICS);
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

```
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient Connect attempt 1
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient Trying to connect to host: kafka-hs port: 9093
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient kafka-node-client createBroker kafka-hs:9093
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient Connect attempt 1
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient Trying to connect to host: kafka-hs port: 9093
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient kafka-node-client createBroker kafka-hs:9093
YAYAYAYAYYAY!!!
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient kafka-node-client sending versions request to kafka-hs:9093
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient broker socket connected {"host":"kafka-hs","port":9093}
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient connected to socket, trying to load initial metadata
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient missing apiSupport waiting until broker is ready...
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient waitUntilReady [BrokerWrapper kafka-hs:9093 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)]
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient kafka-node-client sending versions request to kafka-hs:9093
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient broker socket connected {"host":"kafka-hs","port":9093}
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient connected to socket, trying to load initial metadata
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient missing apiSupport waiting until broker is ready...
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient waitUntilReady [BrokerWrapper kafka-hs:9093 (connected: true) (ready: false) (idle: false) (needAuthentication: false) (authenticated: false)]
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient Received versions response from kafka-hs:9093
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":2,"usable":2},"fetch":{"min":0,"max":3,"usable":2},"offset":{"min":0,"max":1,"usable":0},"metadata":{"min":0,"max":2,"usable":1},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":3,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":2,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":1,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":{"min":0,"max":0,"usable":0},"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":{"min":0,"max":1,"usable":1},"deleteTopics":{"min":0,"max":0,"usable":false}}
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient broker is now ready
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient Received versions response from kafka-hs:9093
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":2,"usable":2},"fetch":{"min":0,"max":3,"usable":2},"offset":{"min":0,"max":1,"usable":0},"metadata":{"min":0,"max":2,"usable":1},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":3,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":2,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":1,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":{"min":0,"max":0,"usable":0},"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":{"min":0,"max":1,"usable":1},"deleteTopics":{"min":0,"max":0,"usable":false}}
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient broker is now ready
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient kafka-node-client updated internal metadata
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:ConsumerGroup Connecting kafka-node-client
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:KafkaClient kafka-node-client updated internal metadata
Producer Ready
Tue, 18 Jun 2019 20:50:02 GMT kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: 'kafka-0.kafka-hs.default.svc.cluster.local',
  coordinatorPort: 9093,
  coordinatorId: 0 }
buffer.js:515
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:515:11)
    at BufferMaker.make (/data/app/node_modules/buffermaker/lib/BufferMaker.js:50:29)
    at _encodeProtocolData (/data/app/node_modules/kafka-node/lib/protocol/protocol.js:1217:47)
    at BufferMaker.encodeGroupProtocol (/data/app/node_modules/kafka-node/lib/protocol/protocol.js:1200:67)
    at Array.forEach (<anonymous>)
    at encodeJoinGroupRequest (/data/app/node_modules/kafka-node/lib/protocol/protocol.js:1389:18)
    at KafkaClient.Client.sendGroupRequest (/data/app/node_modules/kafka-node/lib/baseClient.js:176:24)
    at KafkaClient.Client.sendJoinGroupRequest (/data/app/node_modules/kafka-node/lib/baseClient.js:197:8)
    at /data/app/node_modules/kafka-node/lib/consumerGroup.js:543:21
    at nextTask (/data/app/node_modules/async/dist/async.js:5324:14)
    at next (/data/app/node_modules/async/dist/async.js:5331:9)
    at /data/app/node_modules/async/dist/async.js:969:16
    at KafkaClient.wrappedFn (/data/app/node_modules/kafka-node/lib/kafkaClient.js:481:14)
    at KafkaClient.Client.invokeResponseCallback (/data/app/node_modules/kafka-node/lib/baseClient.js:593:10)
    at KafkaClient.Client.handleReceivedData (/data/app/node_modules/kafka-node/lib/baseClient.js:569:10)
    at KafkaClient.handleReceivedData (/data/app/node_modules/kafka-node/lib/kafkaClient.js:1367:48)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by V-Sharma10** [comment]
i am encountering the same issue, how was this resolved ? please help

**Comment by heyfgirl** [comment]
TOPICS It should be a string or an array of strings
