### ISSUE TITLE
Error: NotLeaderForPartition when sending payload

### ISSUE THREAD

**Issue by gvso** [SOHU-Co/kafka-node#1296]
## Bug Report
I'm getting this error every time I try to send a payload. Unlike #245 , this happens in the Producer.

### Environment

* Node version: 12.3.1
* Kafka-node version: 4.1.3
* Kafka version: 0.11.0.3

### Include Sample Code to reproduce behavior.

The code is a little more complex, but the client and producer are created in this way and the function responsible for sending the payload is called correctly.

```js
this.client = new kafka.KafkaClient();
this.producer = new kafka.Producer(this.client);

let payload = [{
      topic: 'Topic A',
      messages: JSON.stringify(dataObj),
    }];

this.producer.send(payload, function(err, data) {
        console.log("Error:", err);
      });

```

The logged error is the following one:

```
Error: Error: NotLeaderForPartition
    at Object.<anonymous> (node_modules/kafka-node/lib/protocol/protocol.js:952:17)
    at Object.self.tap (node_modules/binary/index.js:248:12)
    at Object.decodePartitions (node_modules/kafka-node/lib/protocol/protocol.js:950:95)
    at Object.self.loop (node_modules/binary/index.js:267:16)
    at Object.<anonymous> (node_modules/kafka-node/lib/protocol/protocol.js:165:8)
    at Object.self.loop (node_modules/binary/index.js:267:16)
    at decodeProduceV2Response (node_modules/kafka-node/lib/protocol/protocol.js:944:6)
    at KafkaClient.Client.invokeResponseCallback (node_modules/kafka-node/lib/baseClient.js:589:18)
    at KafkaClient.Client.handleReceivedData (node_modules/kafka-node/lib/baseClient.js:569:10)
    at KafkaClient.handleReceivedData (node_modules/kafka-node/lib/kafkaClient.js:1367:48)
    at Socket.<anonymous> (node_modules/kafka-node/lib/kafkaClient.js:797:10)
    at Socket.emit (events.js:200:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
```

Thanks for your contribution!

**Comment by gvso** [comment]
Removing the `logs-dir` made the trick. In my case, it was at `/var/lib/kafka`, but I read that other people have them at `/tmp/kafka-logs`
