### ISSUE TITLE
connect with SSL cert

### ISSUE THREAD

**Issue by vendybike** [SOHU-Co/kafka-node#1297]
hi, i am new in kafka, i am trying connect to kafka event stream, when i connected with node-rdkafka it worked, but i want to use node-kafka...my code
`var kafka = require('kafka-node');
var fs = require('fs');

kafkaClientOption = {
    kafkaHost : 'mybroker',
    connectTimeout: undefined,
    requestTimeout: undefined,
    autoConnect: undefined ,
    connectRetryOptions :undefined,
    sslOptions:{
        'ca':fs.readFile('cert.pem', (err) => {if(err)console.log(err);})
    },
    clientId:undefined,
    idleConnection: undefined,
    reconnectOnIdle: undefined,
    maxAsyncRequests: undefined,
    sasl:{
        username: 'myusername',
        password: 'mypass',
    }
}

var client = new kafka.KafkaClient(kafkaClientOption);

client.on('error', function (error) {
    console.error(error);
});

var producer = new kafka.Producer(client);

producer.on('ready', function () {
    console.log('ready');
})`

but i get error : 
 Cannot read property 'toUpperCase' of undefined
    at KafkaClient.saslAuth (C:\Proj\kafka-test\node_modules\kafka-node\lib\kafkaClient.js:667:49)
    at getApiVersions (C:\Proj\kafka-test\node_modules\kafka-node\lib\kafkaClient.js:654:12)
    at KafkaClient.wrappedFn (C:\Proj\kafka-test\node_modules\kafka-node\lib\kafkaClient.js:481:14)
    at KafkaClient.Client.invokeResponseCallback (C:\Proj\kafka-test\node_modules\kafka-node\lib\baseClient.js:593:10)
    at KafkaClient.Client.handleReceivedData (C:\Proj\kafka-test\node_modules\kafka-node\lib\baseClient.js:569:10)
    at KafkaClient.handleReceivedData (C:\Proj\kafka-test\node_modules\kafka-node\lib\kafkaClient.js:1367:48)
    at TLSSocket.<anonymous> (C:\Proj\kafka-test\node_modules\kafka-node\lib\kafkaClient.js:797:10)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)

what's wrong? thank you very much

**Comment by vendybike** [comment]
sorry, my fault, now it work. I added mechanism:plain to sasl :-)
