### ISSUE TITLE
OffsetOutOfRange

### ISSUE THREAD

**Issue by vendybike** [SOHU-Co/kafka-node#1299]
hello, I have made consumer and producer, producer is working perfect, but when consumer connect, i get error :
` Error: OffsetOutOfRange
    at events.push (C:\Proj\Examples\Modules\event-stream\node_modules\kafka-node\lib\protocol\protocol.js:267:25)
    at C:\Proj\Examples\Modules\event-stream\node_modules\async\dist\async.js:3880:24
    at replenish (C:\Proj\Examples\Modules\event-stream\node_modules\async\dist\async.js:1011:17)
    at C:\Proj\Examples\Modules\event-stream\node_modules\async\dist\async.js:1016:9
    at eachOfLimit (C:\Proj\Examples\Modules\event-stream\node_modules\async\dist\async.js:1041:24)
    at C:\Proj\Examples\Modules\event-stream\node_modules\async\dist\async.js:1046:16
    at _parallel (C:\Proj\Examples\Modules\event-stream\node_modules\async\dist\async.js:3879:5)
    at Object.series (C:\Proj\Examples\Modules\event-stream\node_modules\async\dist\async.js:4735:5)
    at _decodeFetchResponse (C:\Proj\Examples\Modules\event-stream\node_modules\kafka-node\lib\protocol\protocol.js:244:9)
    at C:\Proj\Examples\Modules\event-stream\node_modules\kafka-node\lib\protocol\protocol.js:193:12
    at KafkaClient.Client.invokeResponseCallback (C:\Proj\Examples\Modules\event-stream\node_modules\kafka-node\lib\baseClient.js:589:18)
    at KafkaClient.Client.handleReceivedData (C:\Proj\Examples\Modules\event-stream\node_modules\kafka-node\lib\baseClient.js:569:10)
    at KafkaClient.handleReceivedData (C:\Proj\Examples\Modules\event-stream\node_modules\kafka-node\lib\kafkaClient.js:1367:48)
    at TLSSocket.<anonymous> (C:\Proj\Examples\Modules\event-stream\node_modules\kafka-node\lib\kafkaClient.js:797:10)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12) topic: 'test_bridge_inbound', partition: 0 }`

i tried to do this 
`this.offset = new Kafka.Offset(this.client)
        this.offset.fetch([
            { topic: topic, partition: 0, time: Date.now(), maxNum: 1 }
        ], function () {
            console.log("fetch Done");
        });`
but i got same error.

**Comment by vendybike** [comment]
Any my consumer:
` kafkaConsumer = new Kafka.Consumer(
                    this.client, [{ topic: topic, offset: 0, partition: partition }], { autoCommit: true });`

**Comment by bobzsj87** [comment]
make sure your offset message is not cleaned up in the Kafka server.
If your offset to be fetched is expired, it is an expected behaviour as documented in the kafka server.
