### ISSUE TITLE
SASL - Can't connect

### ISSUE THREAD

**Issue by GeoffreyHervet** [SOHU-Co/kafka-node#1321]
## Bug Report

SASL looks broken :/ When I enter valid credentials, which work with other lib (`node-rdkafka`), it block client initialization, and emit `close` in loop

### Environment

* Node version: `v10.16.3`
* Kafka-node version: `4.1.3`
* Kafka version: `2.3.0`

### For specific cases also provide
* Number of Brokers: `1`
* Number partitions for topic: `1`

### Include Sample Code to reproduce behavior

```js
var kafka = require('kafka-node');
var Producer = kafka.Producer;
var KeyedMessage = kafka.KeyedMessage;
var Client = kafka.KafkaClient;
var client = new Client({
  kafkaHost: 'pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092',
  sasl: {
    mechanism: 'plain',
    username: '~~~~~~~~',
    password: '~~~~~~~~',
  },
});

client.on('close', function() { console.log('Close') });

var argv = require('optimist').argv;
var topic = argv.topic || 'topic1';
var p = argv.p || 0;
var a = argv.a || 0;
var producer = new Producer(client, { requireAcks: 1 });

producer.on('ready', function() {
  var message = 'a message';
  var keyedMessage = new KeyedMessage('keyed', 'a keyed message');

  producer.send(
    [{ topic: topic, partition: p, messages: [message, keyedMessage], attributes: a }],
    function(err, result) {
      console.log(err || result);
      process.exit();
    },
  );
});

producer.on('error', function(err) {
  console.log('error', err);
});
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

```
$>DEBUG=kafka-node:* node ok.js
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: pkc-e8mp5.eu-west-1.aws.confluent.cloud port: 9092 +2ms
  kafka-node:KafkaClient kafka-node-client createBroker pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 +1ms
  kafka-node:KafkaClient kafka-node-client sending versions request to pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 +115ms
  kafka-node:KafkaClient broker socket connected {"host":"pkc-e8mp5.eu-west-1.aws.confluent.cloud","port":9092} +6ms
  kafka-node:KafkaClient connected to socket, trying to load initial metadata +1ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +0ms
  kafka-node:KafkaClient waitUntilReady [BrokerWrapper pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 (connected: true) (ready: false) (idle: false) (needAuthentication: true) (authenticated: false)] +0ms
Close
  kafka-node:KafkaClient kafka-node-client socket closed pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 (hadError: false) +24ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available (socket closed)
    at new BrokerNotAvailableError (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at Socket.<anonymous> (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +1ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (socket closed)
    at new BrokerNotAvailableError (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at Socket.<anonymous> (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +2ms
  kafka-node:KafkaClient kafka-node-client reconnecting to pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 +1s
  kafka-node:KafkaClient kafka-node-client createBroker pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 +1ms
  kafka-node:KafkaClient kafka-node-client sending versions request to pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 +28ms
Close
  kafka-node:KafkaClient kafka-node-client socket closed pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 (hadError: false) +27ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available (socket closed)
    at new BrokerNotAvailableError (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at Socket.<anonymous> (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (socket closed)
    at new BrokerNotAvailableError (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at Socket.<anonymous> (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient kafka-node-client reconnecting to pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 +1s
  kafka-node:KafkaClient kafka-node-client createBroker pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 +0ms
  kafka-node:KafkaClient kafka-node-client sending versions request to pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 +27ms
Close
  kafka-node:KafkaClient kafka-node-client socket closed pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092 (hadError: false) +28ms
  kafka-node:KafkaClient ApiVersions failed with unexpected error { BrokerNotAvailableError: Broker not available (socket closed)
    at new BrokerNotAvailableError (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at Socket.<anonymous> (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
  kafka-node:KafkaClient error initializing broker after connect { BrokerNotAvailableError: Broker not available (socket closed)
    at new BrokerNotAvailableError (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at Socket.<anonymous> (/Users/geoffreyhervet/presta/kafka-producer/node_modules/kafka-node/lib/kafkaClient.js:778:19)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12) message: 'Broker not available (socket closed)' } +0ms
^C
```

Thanks for your help!

**Comment by HunderlineK** [comment]
I had this issue, I set:

```
sslOptions: {
   rejectUnauthorized: true
 },
```

and interestingly enough it is now working as expected!!

**Comment by saggarsunil** [comment]
Facing same issue. Does it support security.protocol='SASL_SSL' ?

**Comment by saggarsunil** [comment]
@GeoffreyHervet : Did it work for you ?  I am also struggling with same issue.

**Comment by hoangsonnguyen** [comment]
use 'plain' and 
  sasl: {
    mechanism: 'plain',
    username: '~~~~~~~~',
    password: '~~~~~~~~',
  },
sslOptions: {
   rejectUnauthorized: true
 },
it works for me
