### ISSUE TITLE
Partition number is string instead of number

### ISSUE THREAD

**Issue by estliberitas** [SOHU-Co/kafka-node#134]
Hello. I'm using `HighLevelProducer`.

Sometimes I suddenly get this error:

```
AssertionError: cannot write a non-number as a number
    at verifsint (buffer.js:1001:10)
    at writeInt32 (buffer.js:1089:5)
    at Buffer.writeInt32BE (buffer.js:1104:3)
    at BufferMaker.make (/xxx/node_modules/kafka-node/node_modules/buffermaker/lib/BufferMaker.js:77:36)
    at _encodeProduceRequest (/xxx/node_modules/kafka-node/lib/protocol/protocol.js:337:44)
    at /xxx/node_modules/kafka-node/lib/protocol/protocol.js:310:16
    at Client.sendToBroker (/xxx/node_modules/kafka-node/lib/client.js:325:31)
    at Client.send (/xxx/node_modules/kafka-node/lib/client.js:290:14)
    at Client.sendProduceRequest (/xxx/node_modules/kafka-node/lib/client.js:120:10)
    at HighLevelProducer.send (/xxx/node_modules/kafka-node/lib/highLevelProducer.js:70:17)
```

I added following line after line 327 in [lib/protocol/protocol.js](https://github.com/SOHU-Co/kafka-node/blob/master/lib/protocol/protocol.js#L327):

    console.dir(reqs);

After this I logged following:

    [ { topic: 'its_queue', partition: 0, messages: [ [Object] ] } ]
    [ { topic: 'its_queue', partition: 0, messages: [ [Object] ] } ]
    [ { topic: 'its_queue', partition: 0, messages: [ [Object] ] } ]
    [ { topic: 'its_queue', partition: '0', messages: [ [Object] ] } ]

So once `partition` is string, above error is thrown. Maybe I'll add a small fix to convert partition to number?

**Comment by estliberitas** [comment]
Btw, I do not set partition manually at all. It's retrieved from ZK.

**Comment by estliberitas** [comment]
The issue was in [lib/client.js, line L351](https://github.com/SOHU-Co/kafka-node/blob/master/lib/client.js#L351): `Client#updateMetadatas()` uses `Object.keys()` to get partition names which means we get array of strings instead of numbers.

**Comment by haio** [comment]
See it.
