### ISSUE TITLE
Error: Not a message set. Magic byte is 2

### ISSUE THREAD

**Issue by yunnysunny** [SOHU-Co/kafka-node#1352]
## Environment

* Node version:
* Kafka-node version: 5.0.0
* Kafka version:2.2.0

### For specific cases also provide
* Number of Brokers:3
* Number partitions for topic:64

### Include Sample Code to reproduce behavior
When we use the kafka-node of `5.0.0` and use its `HighLevelProducer` to send data to kafka, and use `ConsumerGroup` to consume the data, but it occurred the error of `Not a message set. Magic byte is 2`. 
Then we use kafka-node of `4.1.3`, the problem is missed.

 Error: Not a message set. Magic byte is 2
     at /home/sunny/code/logical-consumer-immediately/node_modules/_kafka-node@5.0.0@kafka-node/lib/protocol/protocol.js:280:25
     at /home/sunny/code/logical-consumer-immediately/node_modules/_async@2.6.3@async/dist/async.js:3880:24
     at replenish (/home/sunny/code/logical-consumer-immediately/node_modules/_async@2.6.3@async/dist/async.js:1011:17)
     at /home/sunny/code/logical-consumer-immediately/node_modules/_async@2.6.3@async/dist/async.js:1016:9
     at eachOfLimit (/home/sunny/code/logical-consumer-immediately/node_modules/_async@2.6.3@async/dist/async.js:1041:24)
     at /home/sunny/code/logical-consumer-immediately/node_modules/_async@2.6.3@async/dist/async.js:1046:16
     at _parallel (/home/sunny/code/logical-consumer-immediately/node_modules/_async@2.6.3@async/dist/async.js:3879:5)
     at Object.series (/home/sunny/code/logical-consumer-immediately/node_modules/_async@2.6.3@async/dist/async.js:4735:5)
     at _decodeFetchResponse (/home/sunny/code/logical-consumer-immediately/node_modules/_kafka-node@5.0.0@kafka-node/lib/protocol/protocol.js:244:9)
     at /home/sunny/code/logical-consumer-immediately/node_modules/_kafka-node@5.0.0@kafka-node/lib/protocol/protocol.js:199:12

**Comment by yunnysunny** [comment]
It is duplicate with the issue of https://github.com/SOHU-Co/kafka-node/issues/1208
