### ISSUE TITLE
multiple kafka producer instances, high CPU Usage

### ISSUE THREAD

**Issue by linkFly6** [SOHU-Co/kafka-node#1359]
## Questions?

I have several new producers, which are put in the cache, and the CPU is 100% occupied during initialization.

我有多个多个 producer 放在缓存里，但是在初始化 new 的时候（哪怕只有两个 producer），都会引发很高的 cpu 占用（100%）

### Environment

* Node version: v8.11.2
* Kafka-node version: 5.0.0
* Kafka version: 2.2

### Include Sample Code to reproduce behavior

```ts
// include code here

const poolMap = new Map<string, IPoolMap>()

const registerKafkaClient = (appId: string, appInfo: IAppCache, force = false): Promise<boolean> => {

  if (!force && poolMap.has(appId)) {
    return Promise.resolve(true)
  }
  return new Promise((resolve) => {
    const client = new KafkaNode.KafkaClient({
      kafkaHost: process.env.KAFKA_HOST,
      connectTimeout: 1000,
      maxAsyncRequests: 100,
      requestTimeout: 3000,
      sasl: {
        mechanism: 'plain',
        username: appInfo.kafka_appid,
        password: appInfo.kafka_secret,
      }
    })
    const producer = new KafkaNode.Producer(client, {
      requireAcks: 1,
      ackTimeoutMs: 100,
      // partitionerType: 2
    })

    /**
     * 清掉消息发布者
     */
    const close = () => {
      producer.close()
      client.close()
    }

    producer.once('ready', () => {
      if (poolMap.has(appId)) {
        // 如果连接池中已经有了，则清空历史，只有当 force=true 的时候才会命中这个逻辑
        let old = poolMap.get(appId)
        // 新的置入连接池
        poolMap.set(appId, {
          producer,
          close,
          errCount: 0
        })
        // 防止当前 kafka 对象没释放，所以延迟回收
        setTimeout(() => {
          // 清空旧对象
          old!.close()
          old = null as any
        }, 1000)
      } else {
        // 直接置入连接池
        poolMap.set(appId, {
          producer,
          close,
          errCount: 0,
        })
      }
      resolve(true)
    })
    producer.on('error', (error) => {
      close()
      // 清掉连接池对象
      if (poolMap.has(appId)) {
        poolMap.delete(appId)
      }
      resolve(false)
    })
  })
}


// demo

const apps = [
{ id: 0, info: { kafka_appid: 'xx', kafka_secret: 'xxx' } },
{ id: 1, info: { kafka_appid: 'xx', kafka_secret: 'xxx' } },
{ id: 2, info: { kafka_appid: 'xx', kafka_secret: 'xxx' } }
]

apps.forEach(app => {
   registerKafkaClient(app.id, app.info)
})


```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

```bash
AssertionError [ERR_ASSERTION]: apiSupport is empty
    at getSupportedForRequestType (/home/mask/raven/node_modules/kafka-node/lib/kafkaClient.js:974:3)
    at async.series.cb (/home/mask/raven/node_modules/kafka-node/lib/kafkaClient.js:911:33)
    at /home/mask/raven/node_modules/async/dist/async.js:3880:24
    at replenish (/home/mask/raven/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/home/mask/raven/node_modules/async/dist/async.js:995:17)
    at /home/mask/raven/node_modules/async/dist/async.js:969:16
    at /home/mask/raven/node_modules/async/dist/async.js:3885:13
    at KafkaClient.onReady (/home/mask/raven/node_modules/kafka-node/lib/kafkaClient.js:1002:5)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Connect attempt 1
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Trying to connect to host: 172.21.100.1 port: 30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client createBroker 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Connect attempt 1
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Trying to connect to host: 172.21.100.1 port: 30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client createBroker 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Connect attempt 1
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Trying to connect to host: 172.21.100.1 port: 30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client createBroker 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Connect attempt 1
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Trying to connect to host: 172.21.100.1 port: 30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client createBroker 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Connect attempt 1
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Trying to connect to host: 172.21.100.1 port: 30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client createBroker 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client sending versions request to 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient broker socket connected {"host":"172.21.100.1","port":30372}
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient connected to socket, trying to load initial metadata
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient missing apiSupport waiting until broker is ready...(loadMetadataForTopics)
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient waitUntilReady [BrokerWrapper 172.21.100.1:30372 (connected: true) (ready: false) (idle: false) (needAut
hentication: true) (authenticated: false)]
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client sending versions request to 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient broker socket connected {"host":"172.21.100.1","port":30372}
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient connected to socket, trying to load initial metadata
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient missing apiSupport waiting until broker is ready...(loadMetadataForTopics)
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient waitUntilReady [BrokerWrapper 172.21.100.1:30372 (connected: true) (ready: false) (idle: false) (needAuthentication: true) (authenticated: false)]
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client sending versions request to 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient broker socket connected {"host":"172.21.100.1","port":30372}
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient connected to socket, trying to load initial metadata
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient missing apiSupport waiting until broker is ready...(loadMetadataForTopics)
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient waitUntilReady [BrokerWrapper 172.21.100.1:30372 (connected: true) (ready: false) (idle: false) (needAuthentication: true) (authenticated: false)]
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client sending versions request to 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient broker socket connected {"host":"172.21.100.1","port":30372}
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient connected to socket, trying to load initial metadata
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient missing apiSupport waiting until broker is ready...(loadMetadataForTopics)
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient waitUntilReady [BrokerWrapper 172.21.100.1:30372 (connected: true) (ready: false) (idle: false) (needAuthentication: true) (authenticated: false)]
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient kafka-node-client sending versions request to 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient broker socket connected {"host":"172.21.100.1","port":30372}
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient connected to socket, trying to load initial metadata
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient missing apiSupport waiting until broker is ready...(loadMetadataForTopics)
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient waitUntilReady [BrokerWrapper 172.21.100.1:30372 (connected: true) (ready: false) (idle: false) (needAuthentication: true) (authenticated: false)]
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Received versions response from 172.21.100.1:30372
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":2,"usable":2},"fetch":{"min":0,"max":3,"usable":2},"offset":{"min":0,"max":1,"usable":0},"metadata":{"min":0,"max":2,"usable":1},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":3,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":2,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":1,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":{"min":0,"max":0,"usable":0},"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":{"min":0,"max":1,"usable":1},"deleteTopics":{"min":0,"max":0,"usable":false}}
Tue, 26 Nov 2019 05:37:09 GMT kafka-node:KafkaClient Sending SASL/PLAIN handshake request to [BrokerWrapper 172.21.100.1:30372 (connected: true) (ready: false) (idle: false) (needAuthentication: true) (authenticated: false)]
```

**Comment by linkFly6** [comment]
CPU usage:

cpu 占用：
![image](https://user-images.githubusercontent.com/6982402/69603205-eeec9200-1054-11ea-97cd-e0c569a6f482.png)
