### ISSUE TITLE
TypeError: _.isEmpty is not a function

### ISSUE THREAD

**Issue by kvpradeep689** [SOHU-Co/kafka-node#1387]
## Questions?
Trying to write a simple Kafka publisher in Nodejs and running into error at _.isEmpty(brokers). It says the function does not exist. Wondering why 'underscore' package is not a dependency for kafka-node package when it is being used in the code. Am I missing anything in the code? 

### Environment

* Node version: v12.13.1
* Kafka-node version: 5.0.0

### Include Sample Code to reproduce behavior
```js
var Producer = kafka.Producer;
    var Client = kafka.KafkaClient;
    let clientOptions = {
      kafkaHost: 'kafkahostServerIPAddress:9092'
    }

    var client = new Client(clientOptions);
    console.log("Client is ready");
    var producer = new Producer(client);
    console.log("Producer is initialized");
    producer.on('ready', async function () {
      console.log("Producer for kafka is ready");
      });

    producer.on('error', function (error:any) {
      console.log("failed sending to kafka:" + error);
      });
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on
  kafka-node:KafkaClient Connect attempt 1 +4ms
  kafka-node:KafkaClient Trying to connect to host: hic017058 port: 9092 +0ms
  kafka-node:KafkaClient kafka-node-client createBroker hic017058:9092 +1ms
  kafka-node:KafkaClient kafka-node-client sending versions request to kafkahostServerIPAddress:9092 +41ms
  kafka-node:KafkaClient broker socket connected {"host":"kafkahostServerIPAddress","port":9092} +9ms
  kafka-node:KafkaClient connected to socket, trying to load initial metadata +1ms
C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\kafka-node\lib\kafkaClient.js:442
    if (!_.isEmpty(brokers)) {
           ^

TypeError: _.isEmpty is not a function
    at KafkaClient.brokerForLeader (C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\kafka-node\lib\kafkaClient.js:442:12)
    at KafkaClient.loadMetadataForTopics (C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\kafka-node\lib\kafkaClient.js:888:23)
    at C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\kafka-node\lib\kafkaClient.js:146:16
    at C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\async\dist\async.js:3880:24
    at replenish (C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\async\dist\async.js:1011:17)
    at iterateeCallback (C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\async\dist\async.js:995:17)
    at C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\async\dist\async.js:969:16
    at C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\async\dist\async.js:3885:13
    at C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\kafka-node\lib\kafkaClient.js:203:16
    at C:\Projects\Intelligrated\Momentum\sample-dot-client\node_modules\async\dist\async.js:969:16

**Comment by kvpradeep689** [comment]
It looks like this package works only with javascript. Used [node-rdkafka](https://www.npmjs.com/package/node-rdkafka) for TypeScript.
