### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:9092

### ISSUE THREAD

**Issue by sanjay-nag** [SOHU-Co/kafka-node#1401]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version: 10.13.0
* Kafka-node version: 4.1.0
* Kafka version: 2.11-1.1.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 

### Kafka Broker configurations
**server.properties**
`advertised.listeners=PLAINTEXT://<KafkaBroker/Zookeeper Private IP of EC2>:9092
zookeeper.connect=<KafkaBroker/Zookeeper Private IP of EC2>:2181`

**connect-distributed.properties**
`bootstrap.servers=<KafkaBroker/Zookeeper Private IP of EC2>:9092`

**connect-standalone.properties**
`bootstrap.servers=<KafkaBroker/Zookeeper Private IP of EC2>:9092`

**producer.properties**
`bootstrap.servers=<Producer Public IP of EC2>:9092`

**consumer.properties**
`bootstrap.servers=<Producer Public IP of EC2>:9092`

### Producer configuration
connection.js
`this.client = new kafka.KafkaClient("<KafkaBroker/Zookeeper Public IP of EC2>:2181");`

### Consumer configuration
connection.js
`this.client = new kafka.KafkaClient("<KafkaBroker/Zookeeper Public IP of EC2>:2181");`

### Error at both producer and consumer EC2s 

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:9092
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
Emitted 'error' event at:
    at KafkaClient.<anonymous> (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/baseProducer.js:101:10)
    at KafkaClient.emit (events.js:182:13)
    at KafkaClient.EventEmitter.emit (domain.js:442:20)
    at async.series.error (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:165:16)
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:3888:9
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:988:17)
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:969:16
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:3885:13
    at async.doWhilst (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:207:9)
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:969:16
    at next (/home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:3022:18)
    at connectToBroker (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:188:11)
    at /home/ec2-user/kafka-frontend/node_modules/lodash/lodash.js:10050:25
    at onError (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:234:5)
    at Socket.<anonymous> (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:248:5)

### Please help me!

**Comment by kirannbhatt** [comment]
In connection.js for both Producer and Consumer. Try:
```
this.client = new kafka.KafkaClient({ kafkaHost: "<KafkaBroker/Zookeeper Public IP of EC2>:2181" });
```

**Comment by sanjay-nag** [comment]
> In connection.js for both Producer and Consumer. Try:
> 
> ```
> this.client = new kafka.KafkaClient({ kafkaHost: "<KafkaBroker/Zookeeper Public IP of EC2>:2181" });
> ```

Thank you, this worked!
