### ISSUE TITLE
Error: AssertionError [ERR_ASSERTION]: apiSupport is empty

### ISSUE THREAD

**Issue by rorysavage77** [SOHU-Co/kafka-node#1420]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version: v8.9.3
* Kafka-node version: 5.0.0
* Kafka version: 2.11

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

```js
        const client = new kafka.KafkaClient({kafkaHost: brokerUrl});

        /* handle all of the various emitter states */

        /* disable connect string as it gets too chatty*/
        //client.on("connect", function () {
        //    node.log("Client connected to: " + topic)
        //});
        client.on("reconnect", function () {
            node.log("Client reconnected to: " + topic)
            try { topicFunc(); }
            catch (err) {node.error(err); }
        });
        client.on("ready", function () {
            node.log("Client Ready: " + topic)
        });
        client.on("error", function (err) {
            node.log("Client Error: " + err)
        });
        client.on("uncaughtException", function (err) {
            node.log("Client Caught uncaughtException: " + err)
        });
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

```
ssertionError with newly provisioned subscribers
{ AssertionError [ERR_ASSERTION]: apiSupport is empty
    at getSupportedForRequestType (/usr/src/node-red/node_modules/kafka-node/lib/kafkaClient.js:974:3)
    at async.series.cb (/usr/src/node-red/node_modules/kafka-node/lib/kafkaClient.js:911:33)
    at /usr/src/node-red/node_modules/async/dist/async.js:3880:24
    at replenish (/usr/src/node-red/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/usr/src/node-red/node_modules/async/dist/async.js:995:17)
    at /usr/src/node-red/node_modules/async/dist/async.js:969:16
    at /usr/src/node-red/node_modules/async/dist/async.js:3885:13
    at KafkaClient.onReady (/usr/src/node-red/node_modules/kafka-node/lib/kafkaClient.js:998:5)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
14 Jul 00:22:01 - [red] Uncaught Exception:
14 Jul 00:22:01 - { AssertionError [ERR_ASSERTION]: apiSupport is empty
    at getSupportedForRequestType (/usr/src/node-red/node_modules/kafka-node/lib/kafkaClient.js:974:3)
    at async.series.cb (/usr/src/node-red/node_modules/kafka-node/lib/kafkaClient.js:911:33)
    at /usr/src/node-red/node_modules/async/dist/async.js:3880:24
    at replenish (/usr/src/node-red/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/usr/src/node-red/node_modules/async/dist/async.js:995:17)
    at /usr/src/node-red/node_modules/async/dist/async.js:969:16
    at /usr/src/node-red/node_modules/async/dist/async.js:3885:13
    at KafkaClient.onReady (/usr/src/node-red/node_modules/kafka-node/lib/kafkaClient.js:998:5)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

Thanks for your contribution!

**Comment by sashadu** [comment]
Hello dear colleagues, any update or plans for this bug fixing? Thank you.

**Comment by heecheon92** [comment]
Please help us by fixing this issue. I have already used this library in production application. Catching the assertion error and reinitializing kafkaClient doesn't fix the problem. What should I do when encountering this problem?

**Comment by ag-simpplr** [comment]
Facing same issue

**Comment by Soumik43** [comment]
Hey guys, is there any solution to this, it seems that we are facing this issue when we are trying to connect to Confluent cloud kafka, but there does not seem to be an issue like this on AWS MSK, if there's any solution to this it would be helpful!
