### ISSUE TITLE
NO_NODE error on kafka consumer init.

### ISSUE THREAD

**Issue by madhavan020985** [SOHU-Co/kafka-node#148]
````javascript
var kafka = require('kafka-node'),
Consumer = kafka.Consumer,
client = new kafka.Client(),
consumer = new Consumer(
  client,
  [
    { topic: '1234', partition: 0 }
  ]
);
consumer.on('message', function (message) {
  console.log(message);
});
````
Kafka consumer created using the above code crashes with NO_NODE[-101] error.

Exception: NO_NODE[-101]
````javascript
    at ConnectionManager.onSocketData (/home/sk/ws/kafka/node_modules/kafka-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:23)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
````

**Comment by haio** [comment]
The default zk connectionString is `localhost:2181/kafka0.8`, so please check your server configuration and change it to yours.

**Comment by madhavan020985** [comment]
````javascript
zookeeper.connect=localhost:2181
````
this is how it comes shipped with kafka. I see, an inherent mismatch between zookeeper & kafka defaults. but anyway, config change is not an issue. when does zookeeper make the node kafka0.8? does it happen, when kafka broker connects to it for the first time? now my zookeeper root node has child nodes like brokers, consumers etc.. does all of them get grouped under kafka0.8 node?

**Comment by haio** [comment]
The client can't do this, you should change configure in your Kafka
server.properties and create path kafka0.8 in zk manually.  The easiest way
is set connectionString to localhost:2181.

madhavan020985 <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>于2015年2月3日星期二写道：
