### ISSUE TITLE
Getting following error on require('kafka-node');unable to use module

### ISSUE THREAD

**Issue by mindfireon812** [SOHU-Co/kafka-node#194]
2015-04-13T11:45:14.372Z - error: uncaughtException: Cannot read property 'prototype' of undefined date=Mon Apr 13 2015 17:15:14 GMT+0530 (IST), pid=11452, uid=1001, gid=1001, rss=149561344, heapTotal=77818624, heapUsed=48361528, loadavg=[1.8935546875, 1.79248046875, 1.658203125], uptime=30420.134800244, trace=[column=29, file=/kafka-node/node_modules/lodash/dist/lodash.js, function=runInContext, line=462, method=null, native=false, column=11, file= /kafka-node/node_modules/lodash/dist/lodash.js, function=, line=6329, method=null, native=false, column=3, file=/kafka-node/node_modules/lodash/dist/lodash.js, function=, line=6360, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=9, file=/kafka-node/lib/highLevelConsumer.js, function=, line=4, method=null, native=false], stack=[TypeError: Cannot read property 'prototype' of undefined,     at runInContext (/kafka-node/node_modules/lodash/dist/lodash.js:462:29),     at Object.<anonymous> (/kafka-node/node_modules/lodash/dist/lodash.js:6329:11),     at Object.<anonymous> (/kafka-node/node_modules/lodash/dist/lodash.js:6360:3),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (/kafka-node/lib/highLevelConsumer.js:4:9)]

**Comment by haio** [comment]
This seems a issue with your node.js environment, which version are you using?

**Comment by mindfireon812** [comment]
Issue resolved.

It was issue due to global object declaration.

**Comment by haio** [comment]
ok, so close this.
