### ISSUE TITLE
Getting Invalid ELF header error 

### ISSUE THREAD

**Issue by rachel13** [SOHU-Co/kafka-node#221]
Hi, I am currently using the latest version of kafka-node. For development, I run it on a Windows 8 machine and am able to build my project. However, when I deploy it to a uBuntu server, I get the following error on my console:

../node modules/kafka-node/node modules/snappy/node modules/bindings/bindings.js:83 
throw e
Error: /home/mongodbadmin/M2Service/node modules/kafka-node/node modules/snappy/build/Release/binding. node: invalid ELF header 
at Error (native)
at Module.load (module.js:355:32) 
at Function.Module._load (module.js:310: 12) 
at Module.require (module.js:365: 17) 
at require (module.js:384:17) 
at bindings(home/mongodbadmin/M2Service/nodemodules/kafka-node/nodemodules/snappy/nodemodules/bindings/bindings.js:76:4)

at Object.<anonymous> ()home/mongodbadmin/M2Service/node_modules/kafka-node/node_modules/snappy/snappy.js:2:34)
at Module. compile (module.js:460:26) 
at Object.Module._extensions..js (module.js:478:10) 
at Module.load (module.js:355:32) 

What could be the cause of this?

**Comment by rachel13** [comment]
Problem solved. I reinstalled the lib on the server and this issue just went away.

**Comment by debbybz05** [comment]
I have this problem, can you exlpain how did you solve it?

**Comment by rachel13** [comment]
@debbybz05 My problem was that the uBuntu server was behind a firewall and it couldnt resolve some dependencies which kafka-node has. I had to rerun all npm packages install on the uBuntu server itself by connecting it to the internet.
