### ISSUE TITLE
Highlevel producer did not do the failover?

### ISSUE THREAD

**Issue by ychen11** [SOHU-Co/kafka-node#223]
As we tested, this highlevel producer only throws out the error message when one node of our server cluster fails. And will try next node next time when we send another message.
Would it support the failover? To retry next server node automatically instead of throwing an error?

**Comment by shaharmor** [comment]
+1. we would really like this feature as well.

**Comment by mvmalderen** [comment]
I'm experiencing the same problem. When a cluster node fails and when kafka-node was using that node, then it keeps trying to reconnect to that one node and ignores other cluster nodes.
Multiple errors of the following type are emitted in a periodic fashion (about one per second), each time with the same Kafka broker address and port number.
```
[Error: connect ECONNREFUSED 10.0.0.8:9092]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.0.0.8',
  port: 9092 }
Error: connect ECONNREFUSED 10.0.0.8:9092
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
```
It would be awesome if kafka-node would automatically failover to another node in the Kafka cluster if such node is available.
