### ISSUE TITLE
HighLevelConsumer.addTopics() is broken

### ISSUE THREAD

**Issue by chrishiestand** [SOHU-Co/kafka-node#239]
HighLevelConsumer.addTopics() fails with both forms of topics input.

In this example code, the HighLevelConsumer consumes topic1 to start with, and then topic2 is added later with an offset kafka-node fails to subscribe with an error.

Here is the code:
```
#!/usr/bin/env node

var kafka             = require('kafka-node'),
    HighLevelConsumer = kafka.HighLevelConsumer,
    client            = new kafka.Client('dockerbox'),
    consumer          = new HighLevelConsumer(
        client,
        [
            { topic: 'topic1' }
        ],
        {
            groupId: 'my-group'
        }
    );


consumer.on('message', function (message) {
    console.log(message);
});

consumer.addTopics([{ topic: 'topic2', offset: 10 }], function (err, added) {
    if (err) {
        console.log('ERROR');
        console.error(err);
    }
    console.log(added);
}, true);
```

And here is the output:
```
username@hostname:~/project/kafka (master)$ node build/test.js
ERROR
{ [TopicsNotExistError: The topic(s) [object Object] do not exist]
  topics: [ { topic: 'topic2', offset: 10 } ],
  message: 'The topic(s) [object Object] do not exist' }
undefined
```

And here is the consumer offset status:
```
kafka-run-class.sh kafka.tools.ConsumerOffsetChecker --zookeeper dockerbox:2181 --group my-group

Group           Topic                          Pid Offset          logSize         Lag             Owner
my-group        topic1                         0   37              37              0               my-group_29f650f8-3125-4360-b55b-efa1789c7cbf
my-group        topic2                         0   122             122             0               none
```

In the other form for addTopics():
```
#!/usr/bin/env node

var kafka             = require('kafka-node'),
    HighLevelConsumer = kafka.HighLevelConsumer,
    client            = new kafka.Client('dockerbox'),
    consumer          = new HighLevelConsumer(
        client,
        [
            { topic: 'topic1' }
        ],
        {
            groupId: 'my-group'
        }
    );


consumer.on('message', function (message) {
    console.log(message);
});

consumer.addTopics(['topic2'], function (err, added) {
    if (err) {
        console.log('ERROR');
        console.error(err);
    }
    console.log(added);
});
```

Eventually I get the output and error:
```
[ 'topic2' ]

events.js:85
      throw er; // Unhandled 'error' event
            ^
FailedToRegisterConsumerError: Path wasn't created
    at new FailedToRegisterConsumerError (/Users/username/project/kafka/node_modules/kafka-node/lib/errors/FailedToRegisterConsumerError.js:11:11)
    at /Users/username/project/kafka/node_modules/kafka-node/lib/highLevelConsumer.js:137:40
    at done (/Users/username/project/kafka/node_modules/kafka-node/node_modules/async/lib/async.js:126:15)
    at /Users/username/project/kafka/node_modules/kafka-node/node_modules/async/lib/async.js:32:16
    at /Users/username/project/kafka/node_modules/kafka-node/lib/highLevelConsumer.js:127:29
    at /Users/username/project/kafka/node_modules/kafka-node/lib/zookeeper.js:401:22
    at /Users/username/project/kafka/node_modules/kafka-node/node_modules/async/lib/async.js:251:17
    at /Users/username/project/kafka/node_modules/kafka-node/node_modules/async/lib/async.js:148:21
    at /Users/username/project/kafka/node_modules/kafka-node/node_modules/async/lib/async.js:248:21
    at /Users/username/project/kafka/node_modules/kafka-node/node_modules/async/lib/async.js:612:34

```

Despite the fact that kafka-node states it's been added, a simultaneous inspection shows that topic2 has **not** been added.
```
kafka-run-class.sh kafka.tools.ConsumerOffsetChecker --zookeeper dockerbox:2181 --group my-group
Group           Topic                          Pid Offset          logSize         Lag             Owner
my-group        topic1                         0   37              37              0               my-group_56a63c03-e707-41f6-948b-57f4298492fa
my-group        topic2                         0   122             122             0               none
```

**Comment by mindfireon812** [comment]
is this fixed ?

**Comment by Azriel46d** [comment]
Have the same issue, and with some further digging I found that in ~~~zookeeper.js~~~ line 374 it indicates the node to look for by 
~~~
var path = '/consumers/' + groupId + '/owners/' + topic + '/' + partition
~~~

when I check zookeper for that node i found that it does not exist there. I also checked the path
~~~
'/consumers/' + groupId + '/owners
~~~
and there I saw the topics generated on initialisation only rather than the one's through add topic. 

Will continue to dig into this maybe i'll find a solution

**Comment by mustafamamun** [comment]
same here.
