### ISSUE TITLE
When zk restart , kafka-node throw TypeError and Exception: CONNECTION_LOSS[-4]

### ISSUE THREAD

**Issue by baolinCloud** [SOHU-Co/kafka-node#250]
The detail error messages are listed below, any ideas?

events.js:74
throw TypeError('Uncaught, unspecified "error" event.');
^
TypeError: Uncaught, unspecified "error" event.
at TypeError (<anonymous>)
at emit (events.js:74:15)
at null.<anonymous> (/test/node_modules/kafka-node/lib/highLevelProducer.js:64:14)
at emit (events.js:95:17)
at null.<anonymous> (/test/node_modules/kafka-node/lib/client.js:82:14)
at emit (events.js:95:17)
at /test/node_modules/kafka-node/lib/zookeeper.js:216:30
at done (/test/node_modules/kafka-node/node_modules/async/lib/async.js:129:15)
at /test/node_modules/kafka-node/node_modules/async/lib/async.js:32:16
at /test/node_modules/kafka-node/lib/zookeeper.js:237:37

---------------------

events.js:72
throw er; // Unhandled 'error' event
^
Exception: CONNECTION_LOSS[-4]
at ConnectionManager.cleanupPendingQueue (/test/node_modules/kafka-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:189:46)
at ConnectionManager.onSocketClosed (/test/node_modules/kafka-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:274:10)
at Socket.emit (events.js:95:17)
at TCP.close (net.js:466:12)

**Comment by hyperlink** [comment]
The socket connection to zookeeper has closed. I am working on a fix for the consumer side in issue #279 .
