### ISSUE TITLE
Port to Node.JS 4.x

### ISSUE THREAD

**Issue by tb01923** [SOHU-Co/kafka-node#253]
Noted here, this package is currently failing to build under Node.JS 4.x.

The upstream issue to track: nodejs/node#2798

It looks as though this is (at minimum) based on Snappy@4.0.0 being included in the package.json. Snappy@4.0.1 does compile correctly on Node.JS 4.x.

**Comment by daveroberts** [comment]
+1

**Comment by giorgosera** [comment]
Affected by this too +1

**Comment by OndroNR** [comment]
+1

**Comment by kadishmal** [comment]
So, can this issue be considered resolved as the PR has been merged?

**Comment by ghughal** [comment]
Is this issue closed? I tried with 0.2.29 and still getting error.

**Comment by dmtrs** [comment]
@ghughal could you share the errors you are getting?

**Comment by ghughal** [comment]
Here's the error I'm getting. There are bunch of C/C++ error before this. I'm building this on SUSE Linux Enterprise Server 11 (x86_64)

```
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/home/virtual/myapp/node_modules/kafka-node/node_modules/snappy/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v4.2.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.0.101-0.47.55-default
gyp ERR! command "/opt/node-v4.2.2-linux-x64/bin/node" "/opt/node-v4.2.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/virtual/myapp/node_modules/kafka-node/node_modules/snappy
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 3.0.101-0.47.55-default
npm ERR! argv "/opt/node-v4.2.2-linux-x64/bin/node" "/opt/node/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! snappy@4.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@4.0.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.
```

**Comment by dmtrs** [comment]
@ghughal please share gcc version you have on the machine, if not latest update and give it a try.

**Comment by kadishmal** [comment]
Right. I have failed once but after upgrading to g++ 4.8, the compilation was successful. I haven't particularly tried kafka-node but node-hashes. I suppose he reason should be the same.

**Comment by hyperlink** [comment]
We're been using this in a 4.x environment w/o issues.
