### ISSUE TITLE
Error with latest version of node

### ISSUE THREAD

**Issue by anirbanhalder** [SOHU-Co/kafka-node#299]
If we are using any node version above 4.x, we get below error. Is someone looking into it?
Here's the exception:

$ nvm use v4.2.4
Now using node v4.2.4 (npm v2.14.12)

$ node app.js
/myapp/node_modules/kafka-node/node_modules/snappy/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/myapp/node_modules/kafka-node/node_modules/snappy/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/myapp/node_modules/kafka-node/node_modules/snappy/snappy.js:2:34)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by OndroNR** [comment]
Have you tried `npm i` so it would reinstall snappy?

**Comment by OndroNR** [comment]
I think you have native code packages installed for older node.js version.

**Comment by SomeKittens** [comment]
Working for me with freshly installed packages.

**Comment by anirbanhalder** [comment]
Yes, working fine with freshly installed packages. Thanks!
