### ISSUE TITLE
node-zookeeper-client EventEmitter-Leak

### ISSUE THREAD

**Issue by ansgarS** [SOHU-Co/kafka-node#316]
If you start multiple (four in my setup) Consumers in one process (using one client for each consumer), there will be a possible EventEmitter Leak in node-zookeeper-client/lib/WatcherManager.js(line 37):
https://github.com/alexguan/node-zookeeper-client/blob/master/lib/WatcherManager.js#L37

it seems that ```watchers[path].once("notification", watcher);``` is called more than 11 times.

My stacktrace: 
```console
(node) warning: possible EventEmitter memory leak detected. 11 notification listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at registerWatcher (/opt/nodejs/node_modules/node-zookeeper-client/lib/WatcherManager.js:37:24)
    at WatcherManager.registerDataWatcher (/opt/nodejs/node_modules/node-zookeeper-client/lib/WatcherManager.js:55:5)
    at ConnectionManager.registerDataWatcher (/opt/nodejs/node_modules/node-zookeeper-client/lib/ConnectionManager.js:173:25)
    at Object.callback (/opt/nodejs/node_modules/node-zookeeper-client/index.js:740:48)
    at ConnectionManager.onSocketData (/opt/nodejs/node_modules/node-zookeeper-client/lib/ConnectionManager.js:562:35)
    at ConnectionManager.onSocketData (/opt/nodejs/node_modules/node-zookeeper-client/lib/ConnectionManager.js:580:14)
    at ConnectionManager.onSocketData (/opt/nodejs/node_modules/node-zookeeper-client/lib/ConnectionManager.js:580:14)
    at ConnectionManager.onSocketData (/opt/nodejs/node_modules/node-zookeeper-client/lib/ConnectionManager.js:580:14)
```

**Comment by krishnateja262** [comment]
I am having the same problem. @ansgarS were you able to find a solution for it?

**Comment by ppryde** [comment]
+ 1 for this issue, I get it with a single consumer but when the number of partitions I add >= 11

**Comment by estliberitas** [comment]
It's very old issue, AFAIK, it's not fixed still

**Comment by mafischer** [comment]
I just came across this issue today.
