### ISSUE TITLE
when consumer restart, old messages are going to be sent, kafka-node version is 0.3.2

### ISSUE THREAD

**Issue by baolinCloud** [SOHU-Co/kafka-node#345]
When I restart high-level kafka-node consumer, offsetOutOfRange event has been triggered (but the error is undefined), and I get lots of old messages. I guess the offset was reset to the min value, and the code proves.

Why offsetOutOfRange event was triggerd?

If i changed the offset to max value, any side effects ?

**Comment by haio** [comment]
> Why offsetOutOfRange event was triggerd?
This might because the client didn't commit the offset before it restart, but the some of the old message may have been deleted. When consumer restart the next time, it will consumer from the last committed offset, this time `offsetOutOfRange ` may be triggerd.

> If i changed the offset to max value, any side effects ?
Not sure about it, manually set offset only work when fromOffset is set to true

**Comment by baolinCloud** [comment]
I set autoCommit to true, why the client didn't commit the offset before it restart? something wrong?

**Comment by baolinCloud** [comment]
Kafka server log:


ERROR [KafkaApi-0] Error when processing fetch request for partition [test,1] offset 0 from consumer with correlation id 2264207 (kafka.server.KafkaApis)
kafka.common.OffsetOutOfRangeException: Request for offset 0 but we only have log segments in the range 4577 to 4577.
        at kafka.log.Log.read(Log.scala:380)
        at kafka.server.KafkaApis.kafka$server$KafkaApis$$readMessageSet(KafkaApis.scala:530)
        at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$readMessageSets$1.apply(KafkaApis.scala:476)
        at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$readMessageSets$1.apply(KafkaApis.scala:471)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at kafka.server.KafkaApis.kafka$server$KafkaApis$$readMessageSets(KafkaApis.scala:471)
        at kafka.server.KafkaApis.handleFetchRequest(KafkaApis.scala:437)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:186)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:42)
        at java.lang.Thread.run(Thread.java:745)

**Comment by haio** [comment]
It seems the consumer start to consumer from offset 0, you should check whether the client commit offset successfully

**Comment by baolinCloud** [comment]
The time of error log on kafka server is 2016-03-31 08:49:36,873; AND the time of error log on kafka consumer is 2016-03-31 08:49:36.975.

I am puzzled why the time of error log on kafka server is early than kafka consumer client.

Is the following procedure right?
kafka consumer client commit error -->  kafka server OffsetOutOfRangeException-->kafka consumer client catch offsetOutOfRange  --> kafka consumer set offset to 0

**Comment by haio** [comment]
Yeah, more specifically, the last step should be kafka consumer set offset to the minum offset on the server

**Comment by baolinCloud** [comment]
fetch(payloads, cb) 

{
   topic: 'topicName',
   partition: 0, //default 0
   // time:
   // Used to ask for all messages before a certain time (ms), default Date.now(),
   // Specify -1 to receive the latest offsets and -2 to receive the earliest available offset.
   time: Date.now(),
   maxNum: 1 //default 1
}


what does maxNum mean?

**Comment by baolinCloud** [comment]
https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L109

I found that the response of fetchOffset function is not the max offset on kafka server, which results in the reconsume the messages.

How can i fetch the max offset when consumer rebalanced?
