### ISSUE TITLE
[kafka-node 0.3.2] When I restart kafka-node high-level consumer, consumer fetch messges with offset 0

### ISSUE THREAD

**Issue by baolinCloud** [SOHU-Co/kafka-node#350]
Each  time  I restart kafka-node high-level consumer, I can see the error log from the server as belows:

ERROR [KafkaApi-0] Error when processing fetch request for partition [test,0] offset 0 from consumer with correlation id 66276 (kafka.server.KafkaApis)
kafka.common.OffsetOutOfRangeException: Request for offset 0 but we only have log segments in the range 45503 to 51197.
        at kafka.log.Log.read(Log.scala:380)
        at kafka.server.KafkaApis.kafka$server$KafkaApis$$readMessageSet(KafkaApis.scala:530)
        at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$readMessageSets$1.apply(KafkaApis.scala:476)
        at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$readMessageSets$1.apply(KafkaApis.scala:471)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at kafka.server.KafkaApis.kafka$server$KafkaApis$$readMessageSets(KafkaApis.scala:471)
        at kafka.server.KafkaApis$FetchRequestPurgatory.expire(KafkaApis.scala:783)
        at kafka.server.KafkaApis$FetchRequestPurgatory.expire(KafkaApis.scala:765)
        at kafka.server.RequestPurgatory$ExpiredRequestReaper.run(RequestPurgatory.scala:216)
        at java.lang.Thread.run(Thread.java:745)

**Comment by hyperlink** [comment]
Should be fixed in version 0.5.1.
