### ISSUE TITLE
Fail to parse out broker configuration

### ISSUE THREAD

**Issue by jakepearson** [SOHU-Co/kafka-node#356]
Good afternoon. I am having trouble connecting to my office's kafka cluster. I started with code like this:

```
const kafka = require('kafka-node');
const HighLevelConsumer = kafka.HighLevelConsumer;
const client = new kafka.Client('zookeeper-01:2181', 'super-client-id');
const consumer = new HighLevelConsumer(
        client,
        [
            { topic: 'a-super-great-topic' }
        ],
        {
            groupId: 'the-super-grouper'
        }
    );
consumer.on('message', function(message) {
  console.log(message);
})
```

When I run my node server I get the following output:

```
bld-kafka-03.f4tech.com-1457105355761:bld-kafka-03.f4tech.com:9092
^

SyntaxError: Unexpected token b
    at Object.parse (native)
    at /Users/pairing/projects/unicorny/great-fun-time-webserver/node_modules/kafka-node/lib/zookeeper.js:241:40
    at /Users/pairing/projects/unicorny/great-fun-time-webserver/node_modules/node-zookeeper-client/index.js:165:26
    at Object.async.whilst (/Users/pairing/projects/unicorny/great-fun-time-webserver/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:627:13)
    at /Users/pairing/projects/unicorny/great-fun-time-webserver/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:623:23
    at /Users/pairing/projects/unicorny/great-fun-time-webserver/node_modules/node-zookeeper-client/index.js:145:21
    at Object.callback (/Users/pairing/projects/unicorny/great-fun-time-webserver/node_modules/node-zookeeper-client/index.js:582:17)
    at ConnectionManager.onSocketData (/Users/pairing/projects/unicorny/great-fun-time-webserver/node_modules/node-zookeeper-client/lib/ConnectionManager.js:562:35)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
```

I took a look at the source code of `zookeeper.js` and it is reading from `zookeeper` at `/brokers/id/3`. `Zookeeper` returns the following output:

```
bld-kafka-03.f4tech.com-1457105355761:bld-kafka-03.f4tech.com:9092
cZxid = 0x581c3b3d2d
ctime = Fri Mar 04 08:29:15 MST 2016
mZxid = 0x581c3b3d2d
mtime = Fri Mar 04 08:29:15 MST 2016
pZxid = 0x581c3b3d2d
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x151b3de38f221d8
dataLength = 66
numChildren = 0
```

So my broker isn't defined a `json` document. Is there a way to configure `kafka-node` to parse the broker information differently?

**Comment by hyperlink** [comment]
That's very odd. The kafka data structure in zookeeper **should be** in JSON. What version of Kafka is this?
