### ISSUE TITLE
Error: Cannot read property 'sslHost' of undefined (client.js:546:23)

### ISSUE THREAD

**Issue by philidem** [SOHU-Co/kafka-node#398]
We're using the new SSL support and saw this error when trying to create our Kafka producer:

```
Cannot read property 'sslHost' of undefined
    at connect [as createBroker] (/Users/philidem/Development/third-party/kafka-node/lib/client.js:546:23)
    at Client.setupBroker (/Users/philidem/Development/third-party/kafka-node/lib/client.js:535:24)
    at Client.reconnectBroker (/Users/philidem/Development/third-party/kafka-node/lib/client.js:610:24)
    at null._onTimeout (/Users/philidem/Development/third-party/kafka-node/lib/client.js:599:12)
    at Timer.listOnTimeout (timers.js:92:15)
```

I'm logging this issue here to keep track of it but I will try to add more details later.

Problem lines are these:

```javascript
host = brokerProfile[this.ssl ? 'sslHost' : 'host'] || host;
port = brokerProfile[this.ssl ? 'sslPort' : 'port'] || port;
```

I think this is the right fix:

```javascript
host = brokerProfile && brokerProfile[this.ssl ? 'sslHost' : 'host'] || host;
port = brokerProfile && brokerProfile[this.ssl ? 'sslPort' : 'port'] || port;
```

I don't know enough about _brokerFile_. I would like to understand a little better why it might be undefined in some cases before applying this fix. I don't want to hide another underlying problem.

**Comment by philidem** [comment]
@CharlesWall @hyperlink can you take a look at this error to provide insight into why `brokerProfile` is `undefined` and if my fix described above is reasonable?

**Comment by hyperlink** [comment]
I'll take a look.
