### ISSUE TITLE
after close is called throws uncaughtException: write after end

### ISSUE THREAD

**Issue by kumar-b** [SOHU-Co/kafka-node#412]
Here is the stack trace of the uncaught exception.

```javascript
Tue Jul 26 2016 15:18:25 GMT+0530 (IST) - error: uncaughtException: write after end date=Tue Jul 26 2016 15:18:25 GMT+0530 (IST), pid=563, uid=0, gid=0, cwd=/home/kafka/consumer/node-server, execPath=/home/kafka/consumer/node-server/node, version=v4.4.5, argv=[/home/kafka/consumer/node-server/node, /home/kafka/consumer/node-server/index.js], rss=55496704, heapTotal=41443168, heapUsed=30733056, loadavg=[0.22216796875, 0.23681640625, 0.216796875], uptime=2520106
Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at Socket.Writable.write (_stream_writable.js:211:5)
    at Socket.write (net.js:626:40)
    at BrokerWrapper.write (/home/kafka/consumer/node-server/node_modules/kafka-node/lib/wrapper/BrokerWrapper.js:26:15)
    at Client.loadMetadataForTopics (/home/kafka/consumer/node-server/node_modules/kafka-node/lib/client.js:270:10)
    at RetryOperation._fn (/home/kafka/consumer/node-server/node_modules/kafka-node/lib/client.js:389:12)
    at RetryOperation.attempt (/home/kafka/consumer/node-server/node_modules/kafka-node/node_modules/retry/lib/retry_operation.js:56:8)
    at attemptRequestMetadata (/home/kafka/consumer/node-server/node_modules/kafka-node/lib/client.js:387:15)
    at Client.refreshMetadata (/home/kafka/consumer/node-server/node_modules/kafka-node/lib/client.js:383:3)
    at null.<anonymous> (/home/kafka/consumer/node-server/node_modules/kafka-node/lib/consumer.js:84:10)
```

Anyone facing similar issue?
I'm using following to close the consumer connection. The callback gives no error.
`consumer.close(true, callback)`

**Comment by 0x530302** [comment]
Do you use the same client for multiple consumers, or are you also calling `client.close(cb)`?

I had the same issue and found that `consumer.close` also calls `client.close`. Therefore when the client is closed before the consumer finished committing the offsets, the `write after end` error will occur.
