### ISSUE TITLE
producer.send(..., callback) doesn't guarantee callback get called if socket was terminated unexpectly

### ISSUE THREAD

**Issue by alexzhuustc** [SOHU-Co/kafka-node#428]
producer.send(..., callback) doesn't guarantee callback get called if socket was terminated unexpectly

When we send a message to broker, and at that time the socket was terminated unexpectly, we observed below:
  producer.on('error', callback)                -> callback get fired, err is "Error: This socket has been ended by the other party"
  producer.send(..., callback)                  -> callback never get fired. we lost the track of that failed message.
  
  
I checked the source code, probably caused by below reason:
  1. send() callback is fired from handleReceivedData()
  2. handleReceivedData() is called from socket.on('data')
  
if the socket was terminated unexpectly, socket.on('error') will fire, instead of 'data' event. 
so send()'s callback never get fired.

**Comment by hyperlink** [comment]
When the socket is closed all the queued callbacks should be called with an error that was emitted. I'll double check this. What was the specific error you saw?

**Comment by alexzhuustc** [comment]
producer.on('error') emit an error "Error: This socket has been ended by the other party".

**Comment by goodfella1408** [comment]
Getting the same error during commit  (kafka-node v 0.5.3) . Commit callback doesnt return . Only the error event is sent to the consumer (consumer.on('error',function(err){})) -
 [ERROR] { [Error: This socket has been ended by the other party] code: 'EPIPE' }
Error: This socket has been ended by the other party
at Socket.writeAfterFIN [as write] (net.js:297:12)
at BrokerWrapper.write (/home/ubuntu/workspace/metrics_batch/node_modules/kafka-node/lib/wrapper/BrokerWrapper.js:29:17)
at Client.sendToBroker (/home/ubuntu/workspace/metrics_batch/node_modules/kafka-node/lib/client.js:430:20)
at Client.send (/home/ubuntu/workspace/metrics_batch/node_modules/kafka-node/lib/client.js:379:14)
at Client.sendOffsetCommitRequest (/home/ubuntu/workspace/metrics_batch/node_modules/kafka-node/lib/client.js:187:10)
at autoCommit (/home/ubuntu/workspace/metrics_batch/node_modules/kafka-node/lib/highLevelConsumer.js:494:21)

**Comment by hyperlink** [comment]
@alexzhuustc I can't reproduce the issue. I have a test script that generates random data and publishes it to a topic periodically. When I apply `tcpkill` it emits an error on the producer and all the callbacks get called with a `BrokerNotAvailableError: Could not find the leader` error. Here's what the output looks like:

```
 kafka-node:Test creating new client & producer +0ms
  kafka-node:Test producer ready! +215ms
  kafka-node:Test Sending message #0 +1ms
  kafka-node:Test Client connect +187ms
  kafka-node:Test Callback called for #0, took: 0s 234.431238ms +48ms
  kafka-node:Test Sending message #1 +275ms
  kafka-node:Test Callback called for #1, took: 0s 20.423814ms +21ms
  kafka-node:Test Sending message #2 +487ms
  kafka-node:Test Callback called for #2, took: 0s 26.511115ms +27ms
  kafka-node:Test Sending message #3 +479ms
  kafka-node:Test Callback called for #3, took: 0s 20.339415ms +21ms
  kafka-node:Test Sending message #4 +484ms
  kafka-node:Test Callback called for #4, took: 0s 18.388154ms +19ms
  kafka-node:Test Sending message #5 +486ms
  kafka-node:Test Callback called for #5, took: 0s 20.489135ms +21ms
  kafka-node:Test Sending message #6 +485ms
  kafka-node:Test Callback called for #6, took: 0s 48.820369ms +49ms
  kafka-node:Test Sending message #7 +456ms
  kafka-node:Test Callback called for #7, took: 0s 19.701679ms +19ms
  kafka-node:Test Sending message #8 +485ms
  kafka-node:Test Callback called for #8, took: 0s 19.444588ms +20ms
  kafka-node:Test Sending message #9 +483ms
  kafka-node:Test Callback called for #9, took: 0s 29.769909ms +30ms
  kafka-node:Test Producer Error +433ms { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
  kafka-node:Test Sending message #10 +40ms
  kafka-node:Test Callback called for #10, took: 0s 0.702758ms +0ms
  kafka-node:Test Send Callback Error #10 +1ms { [BrokerNotAvailableError: Could not find the leader] message: 'Could not find the leader' }
  kafka-node:Test Sending message #11 +503ms
  kafka-node:Test Callback called for #11, took: 0s 0.40042ms +0ms
  kafka-node:Test Send Callback Error #11 +0ms { [BrokerNotAvailableError: Could not find the leader] message: 'Could not find the leader' }
  kafka-node:Test Client reconnect +491ms
  kafka-node:Test Producer Error +1ms { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
  kafka-node:Test Sending message #12 +11ms
  kafka-node:Test Callback called for #12, took: 0s 0.45885ms +0ms
  kafka-node:Test Send Callback Error #12 +0ms { [BrokerNotAvailableError: Could not find the leader] message: 'Could not find the leader' }
  kafka-node:Test Sending message #13 +504ms
  kafka-node:Test Callback called for #13, took: 0s 0.874751ms +1ms
  kafka-node:Test Send Callback Error #13 +0ms { [BrokerNotAvailableError: Could not find the leader] message: 'Could not find the leader' }
```

And after I stop the `tcpkill`

```
  kafka-node:Test Sending message #37 +503ms
  kafka-node:Test Callback called for #37, took: 0s 1.01778ms +2ms
  kafka-node:Test Send Callback Error #37 +0ms { [BrokerNotAvailableError: Could not find the leader] message: 'Could not find the leader' }
  kafka-node:Test Client reconnect +333ms
  kafka-node:Test Producer Error +7ms { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
  kafka-node:Test Sending message #38 +161ms
  kafka-node:Test Callback called for #38, took: 0s 0.580204ms +1ms
  kafka-node:Test Send Callback Error #38 +0ms { [BrokerNotAvailableError: Could not find the leader] message: 'Could not find the leader' }
  kafka-node:Test Sending message #39 +505ms
  kafka-node:Test Callback called for #39, took: 0s 1.400621ms +2ms
  kafka-node:Test Send Callback Error #39 +0ms { [BrokerNotAvailableError: Could not find the leader] message: 'Could not find the leader' }
  kafka-node:Test Client reconnect +405ms
  kafka-node:Test Sending message #40 +96ms
  kafka-node:Test Callback called for #40, took: 0s 45.584348ms +46ms
  kafka-node:Test Sending message #41 +460ms
  kafka-node:Test Callback called for #41, took: 0s 18.085517ms +18ms
  kafka-node:Test Sending message #42 +486ms
  kafka-node:Test Callback called for #42, took: 0s 33.808267ms +35ms
  kafka-node:Test Sending message #43 +473ms
  kafka-node:Test Callback called for #43, took: 0s 41.34553ms +42ms
```

Can you add more of your code that demonstrates this issue?

**Comment by alexzhuustc** [comment]
抱歉，前一comment的内容有错误，非常抱歉。

我现在了解到的信息是，callback不被触发与这个类型的Error紧密相关：“Error: This socket has been ended by the other party”。

不过，这个类型的Error只在一段时间内频繁出现，大约1天1次。 持续了约5天左右。 自打我提交了这个issue, 这个error再也没出现过。  现在一直运行得好好的, 我不知道怎么复现。

**Comment by alexzhuustc** [comment]
Could it be caused by below reason? just a guess.
--------------------------------------------------


Client.prototype.clearCallbackQueue = function (socket, error) {
  if (!longpolling) {
    Object.keys(queue).forEach(function (key) {
      var handlers = queue[key];
      var cb = handlers[1];
      cb(error);   --->       function my_callback_1() {
                                  producer.send(another_payload, my_callback_2); // my_callback_2 was assigned to same queue as my_callback_1
                              }
      
      
    });
  }
  delete this.cbqueue[socketId];        <---- my_callback_2 was cleared but never get fired
};

**Comment by alexzhuustc** [comment]
下面是我的一个原因猜测。事件按以下顺序触发，可能会造成callback丢失

1. 服务器关闭
2. socket.on('end') -> retrying=true
3. socket.on('close', had_error:false) -> cbqueue清空
4. call producer.send(..., callback) ->  以下条件都能通过 (!broker || !broker.socket || broker.socket.error || broker.socket.closing) -> 进入cbqueue
5. socket.on('error', 'Error: This socket has been ended by the other party') -> 外部可以收到producer.on('error')的callback
6. producer.send(..., callback)在cbqueue中的callback丢失了
