### ISSUE TITLE
TypeError: value is out of bounds (HLC Fetch Request)

### ISSUE THREAD

**Issue by hyperlink** [SOHU-Co/kafka-node#455]
`v0.5.5`

```
TypeError: value is out of bounds
  at checkInt (buffer.js:824:11)
  at Buffer.writeInt32BE (buffer.js:1027:5)
  at [object Object].BufferMaker.make (/app/node_modules/kafka-node/node_modules/buffermaker/lib/BufferMaker.js:77:36)
  at encodeOffsetRequest (/app/node_modules/kafka-node/lib/protocol/protocol.js:505:42)
  at [object Object].Client.sendToBroker (/app/node_modules/kafka-node/lib/client.js:478:19)
  at [object Object].Client.send (/app/node_modules/kafka-node/lib/client.js:443:10)
  at [object Object].Client.sendOffsetRequest (/app/node_modules/kafka-node/lib/client.js:258:8)
  at [object Object].HighLevelConsumer.offsetRequest (/app/node_modules/kafka-node/lib/highLevelConsumer.js:534:15)
  at [object Object].<anonymous> (/app/node_modules/kafka-node/lib/highLevelConsumer.js:271:10)
  at emitOne (events.js:77:13)
  at [object Object].emit (events.js:169:7)
  at /app/node_modules/kafka-node/lib/client.js:178:25
  at Object.<anonymous> (/app/node_modules/kafka-node/lib/protocol/protocol.js:109:18)
  at Object.self.tap (/app/node_modules/kafka-node/node_modules/binary/index.js:248:12)
  at Object.decodePartitions (/app/node_modules/kafka-node/lib/protocol/protocol.js:106:8)
  at Object.self.loop (/app/node_modules/kafka-node/node_modules/binary/index.js:267:16)
  at Object.<anonymous> (/app/node_modules/kafka-node/lib/protocol/protocol.js:55:8)
  at Object.self.loop (/app/node_modules/kafka-node/node_modules/binary/index.js:267:16)
  at _decodeFetchResponse (/app/node_modules/kafka-node/lib/protocol/protocol.js:97:6)
  at /app/node_modules/kafka-node/lib/protocol/protocol.js:87:12
  at [object Object].Client.handleReceivedData (/app/node_modules/kafka-node/lib/client.js:660:18)
  at TLSSocket.<anonymous> (/app/node_modules/kafka-node/lib/client.js:623:10)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at TLSSocket.Readable.push (_stream_readable.js:111:10)
  at TLSWrap.onread (net.js:536:20)
```

**Comment by hyperlink** [comment]
Have not seen this issue occur since 0.5.7 was released.
