### ISSUE TITLE
CONNECTION_LOSS on new consumer (after closing older one)

### ISSUE THREAD

**Issue by rafaelgondim** [SOHU-Co/kafka-node#486]
The scenario:
I'm listening for changes on the topics on zookeeper, when I get the event I close the consumer and try to start a new one subscribing for new topics, I try because I'm getting this error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4]
    at ConnectionManager.queue (C:\Desenvolvimento\temp\hex-service\node_modules\node-zookeeper-client\lib\ConnectionManager.js:716:32)
    at C:\Desenvolvimento\temp\hex-service\node_modules\node-zookeeper-client\index.js:730:36
    at async.whilst.args (C:\Desenvolvimento\temp\hex-service\node_modules\node-zookeeper-client\index.js:125:13)
    at Object.async.whilst (C:\Desenvolvimento\temp\hex-service\node_modules\node-zookeeper-client\node_modules\async\lib\async.js:619:13)
    at attempt (C:\Desenvolvimento\temp\hex-service\node_modules\node-zookeeper-client\index.js:117:11)
    at Client.exists (C:\Desenvolvimento\temp\hex-service\node_modules\node-zookeeper-client\index.js:727:5)
    at Zookeeper.topicExists (C:\Desenvolvimento\temp\hex-service\node_modules\kafka-node\lib\zookeeper.js:336:15)
    at checkZK (C:\Desenvolvimento\temp\hex-service\node_modules\kafka-node\lib\client.js:415:13)
    at C:\Desenvolvimento\temp\hex-service\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Desenvolvimento\temp\hex-service\node_modules\async\lib\async.js:233:13)
```

For listening the change on zookeeper I'm using this:
```
const kafkaClient = new kafka.Client('localhost:2181/');

class Broker extends EventEmitter {
    constructor() {
        super();
        const eventHandler = function () {
                kafkaClient.zk.client.getChildren('/brokers/topics', eventHandler, (error, children) => {
                    if (error) {
                        debug(`Fail: ${error}`);
                    } else {
                        this.emit('topics', children);
                    }
                });
            }.bind(this);
        eventHandler();
    }
}
```

Elsewhere I'm getting the "topics" event:
```
//Those statements are on the constructor from a Class
 new Broker().on('topics', (topics) => {
            debug('New topics');
            //...
            if (this.consumer) {
                this.consumer.close(() => {
                    debug('old consumer closed connection');
                    process.nextTick(this.filterAndSubscribe.bind(this, topics));
                });
            } 
            //...
        });

//....

//Function on a class
filterAndSubscribe() {
        //....
        this.consumer = new kafka.Consumer(kafkaClient, fetchRequests);
        this.consumer.on('message', message => {
            //....
        });

        this.consumer.on('error', (err) => {
            debug(`Fail on consumer: ${err}`);
        });
        this.consumer.on('offsetOutOfRange', function (err) {
            debug(`Fail on consumer: ${err}`);
        });
    }
```

Suggestions?

**Comment by hyperlink** [comment]
Don't share the client instance. When the consumer is closed it will also close the client it used  along with the zookeeper client.

**Comment by rafaelgondim** [comment]
Worked!
Thank you
