### ISSUE TITLE
Does this library support Kafka 0.10+?

### ISSUE THREAD

**Issue by juanpaco** [SOHU-Co/kafka-node#527]
I've seen questions about 0.9+.  I'm getting an error of:

```
 Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (/path/to/project/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:35)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
  code: -101,
  name: 'NO_NODE',
  path: undefined,
  message: 'Exception: NO_NODE[-101]' }
```

I'm using version 1.0.1 of `kafka-node`.

I recently installed Kafka 0.10, and I'm trying to narrow down if I did something wrong in my installation (OSX, homebrew).

**Comment by hyperlink** [comment]
We're running kafka 0.10 in all our environments without issues. You may want to check zookeeper and kafka are setup is ok.

**Comment by juanpaco** [comment]
Thanks for the response.  That rules out `node-kafka`, so I'll turn towards my configuration to find the culprit.
