### ISSUE TITLE
Connection refused on remote kafka node

### ISSUE THREAD

**Issue by fnbns** [SOHU-Co/kafka-node#570]
Good day,

I have a problem connecting to a remote kafka node (which works fine) when doinh:
`client = new kafka.Client('<remote-ip>:2181')`
The error is:  ECONNREFUSED 127.0.0.1:9092 which I find strange since I am passing a remote address, not localhost...

Thank you,
Alex.

**Comment by RobertHerhold** [comment]
@fnbns Did you get this working? I'm running into the same issue.

**Comment by akashdeep-singh** [comment]
@fnbns What was the fix? I'm having the same problem.

**Comment by avi190692** [comment]
I am facing the same issue. Have you find the solution.

**Comment by sanjay-nag** [comment]
Facing the same issue

- Kafka Broker and Zookeeper on the single EC2 instance
- Producer in another EC2 instance
- Consumer in another EC2 instance

Versions
kafka-node: 4.1.0
Kafka: 2.11-1.1.0

### Kafka Broker configurations
**server.properties**
`advertised.listeners=PLAINTEXT://<KafkaBroker/Zookeeper Private IP of EC2>:9092
zookeeper.connect=<KafkaBroker/Zookeeper Private IP of EC2>:2181`

**connect-distributed.properties**
`bootstrap.servers=<KafkaBroker/Zookeeper Private IP of EC2>:9092`

**connect-standalone.properties**
`bootstrap.servers=<KafkaBroker/Zookeeper Private IP of EC2>:9092`

**producer.properties**
`bootstrap.servers=<Producer Public IP of EC2>:9092`

**consumer.properties**
`bootstrap.servers=<Producer Public IP of EC2>:9092`

### Producer configuration
connection.js
`this.client = new kafka.KafkaClient("<KafkaBroker/Zookeeper Public IP of EC2>:2181");`

### Consumer configuration
connection.js
`this.client = new kafka.KafkaClient("<KafkaBroker/Zookeeper Public IP of EC2>:2181");`

### Error at both producer and consumer EC2s 

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:9092
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
Emitted 'error' event at:
    at KafkaClient.<anonymous> (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/baseProducer.js:101:10)
    at KafkaClient.emit (events.js:182:13)
    at KafkaClient.EventEmitter.emit (domain.js:442:20)
    at async.series.error (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:165:16)
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:3888:9
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:988:17)
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:969:16
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:3885:13
    at async.doWhilst (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:207:9)
    at /home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:969:16
    at next (/home/ec2-user/kafka-frontend/node_modules/async/dist/async.js:3022:18)
    at connectToBroker (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:188:11)
    at /home/ec2-user/kafka-frontend/node_modules/lodash/lodash.js:10050:25
    at onError (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:234:5)
    at Socket.<anonymous> (/home/ec2-user/kafka-frontend/node_modules/kafka-node/lib/kafkaClient.js:248:5)

### Please help me!
