### ISSUE TITLE
kafka consumerGroup heartbeat error

### ISSUE THREAD

**Issue by macurial** [SOHU-Co/kafka-node#626]
Kafka consumer only set the host param in the `options`,and It report this err in the console

```sh
kafka-node:ConsumerGroup SyncGroup Request from kafka-node-client-c078933e-f1f9-43a4-a11c-201b454eb17e +0ms
  kafka-node:ConsumerGroup SyncGroup Response +4ms
  kafka-node:ConsumerGroup kafka-node-client owns topics:  { wym: [ 0 ] } +0ms
  kafka-node:ConsumerGroup kafka-node-client fetchOffset Response: {"wym":{"0":45142}} +3ms
  kafka-node:ConsumerGroup Has saved offsets +0ms
  kafka-node:ConsumerGroup generationId 10359 +0ms
  kafka-node:ConsumerGroup kafka-node-client started heartbeats at every 5000 ms +1ms
  kafka-node:ConsumerGroup kafka-node-client Heartbeat error: { RebalanceInProgress: Kafka Error Code: 27
    at new RebalanceInProgress (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/errors/RebalanceInProgressError.js:4:9)
    at createGroupError (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/protocol/protocol.js:100:13)
    at Object.<anonymous> (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/protocol/protocol.js:656:16)
    at Object.self.tap (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/binary/index.js:248:12)
    at decodeGroupHeartbeat (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/protocol/protocol.js:655:6)
    at Client.handleReceivedData (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/client.js:739:18)
    at Socket.<anonymous> (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/client.js:702:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20) message: 'Kafka Error Code: 27', errorCode: 27 } +5s
  kafka-node:ConsumerGroupRecovery RECOVERY from heartbeat: kafka-node-client retrying in 1000 ms { RebalanceInProgress: Kafka Error Code: 27
    at new RebalanceInProgress (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/errors/RebalanceInProgressError.js:4:9)
    at createGroupError (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/protocol/protocol.js:100:13)
    at Object.<anonymous> (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/protocol/protocol.js:656:16)
    at Object.self.tap (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/binary/index.js:248:12)
    at decodeGroupHeartbeat (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/protocol/protocol.js:655:6)
    at Client.handleReceivedData (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/client.js:739:18)
    at Socket.<anonymous> (/Users/wenlei/WebstormProjects/WYMMsg/node_modules/kafka-node/lib/client.js:702:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20) message: 'Kafka Error Code: 27', errorCode: 27 } +0ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +1s
  kafka-node:ConsumerGroup GroupCoordinator Response: null +0ms
```
#HERE is my code #
```javascript
let kafka = require('kafka-node');
let config = require('../config/config.json')['kafka'];
let topic = config.topics;
let options = {
    host: '192.168.0.31:2181'
};

let consumerGroup = new kafka.ConsumerGroup(options, topic);

consumerGroup.on('error', function (err) {
    console.log('error', err);
});
consumerGroup.on('message', function (message) {
    var mv;
	console.log(message);
	if(!!message.value) {
		if (message.value.startsWith('{"')) {
			try {
				mv = JSON.parse(message.value);
			} catch (e) {
				console.log(e);
			}
		} else {
			mv = message.value;
		}

		msg.to(message.topic).emit('refresh', mv);
	}
});
``` 
So why is this happened ,please?

**Comment by hyperlink** [comment]
It doesn't look like those errors were emitted so they can be safely ignored. You have debug mode on you can see the error responses from the kafka coordinator the consumergroup should be able to handle these w/o issue.

**Comment by macurial** [comment]
ok,thanks

**Comment by furstenheim-geoblink** [comment]
I'm seeing the same error (with debug flag activated), when that happens the message is emitted twice.

First the heartbeat error:
```  kafka-node:ConsumerGroup kafka-node-client Heartbeat error: { RebalanceInProgress: Kafka Error Code: 27
 ```
[...]
Then it ignores preexisting messae
```kafka-node:KafkaClient ignoring message due to it being from an old group - memberId: kafka-node-client-xxx !=kafka-node-client-xxx - generationId: 23!=23 +46ms
  kafka-node:KafkaClient ignoring message due to it being from an old group - memberId: kafka-node-client-xxx !=kafka-node-client-xxx - generationId: 23!=23 +0ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +956ms
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +0ms
````
Finally the messages are emitted again
