### ISSUE TITLE
highLevelConsumer issue 

### ISSUE THREAD

**Issue by matesio** [SOHU-Co/kafka-node#627]
/node_modules/kafka-node/lib/highLevelConsumer.js:514
  this.topicPayloads.forEach(p => {
                                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/s04-cluster-cas/Desktop/node_modules/kafka-node/kafka.js:1:91)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by hyperlink** [comment]
this module requires node version > 4.4.7

**Comment by matesio** [comment]
thanks it worked
