### ISSUE TITLE
I am trying to feed events from my angular2 project to kafka-server running in the local system through kafka-node. But my pm2 is giving the below mentioned error persistently. Can anyone give me some insights of how I resolve this?

### ISSUE THREAD

**Issue by RTChowdary** [SOHU-Co/kafka-node#649]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version: v6.9.0
* Kafka-node version:1.6.0
* Kafka version:2.11-0.10.2.0

### For specific cases also provide
* Number of Brokers: <default value>
* Number partitions for topic: <default value>

### Include Sample Code to reproduce behavior

```js
var kafka = require('kafka-node');
var Producer = kafka.Producer;
var KeyedMessage = kafka.KeyedMessage;
var Client = kafka.Client;
var client = new Client('localhost:2181');
var topic = 'test';
var producer = new Producer(client, { requireAcks: 1 });

producer.on('ready', function () {
  var message = 'another message1';
  var keyedMessage = new KeyedMessage('keyed', 'a keyed message');

  producer.send([
    { topic: topic, messages: [message]}
  ], function (err, result) {
    console.log(err || result);
    process.exit();
  });
});
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on
0|web      | Tue, 11 Apr 2017 18:43:12 GMT body-parser deprecated undefined extended: provide extended option at node_modules/body
-parser/index.js:105:29                                                                                                           
0|web      | Listening on:: http://localhost:3000                                                                                 
0|web      | TypeError: Cannot read property 'filter' of undefined                                                                
0|web      |     at zoneAwareEventListeners (/Users/xxx/yyy/ng-web/node_modules/zone.js/dist/zone-node.js:772:13)        
0|web      |     at EventEmitter.listeners (eval at createNamedFn (/Users/xxx/yyy/ng-web/node_modules/zone.js/dist/zone-n
ode.js:785:17), <anonymous>:3:36)                                                                                                 
0|web      |     at registerWatcher (/Users/xxx/yyy/ng-web/node_modules/node-zookeeper-client/lib/WatcherManager.js:30:36
)                                                                                                                                 
0|web      |     at WatcherManager.registerChildWatcher (/Users/xxx/yyy/ng-web/node_modules/node-zookeeper-client/lib/Wat
cherManager.js:63:5)                                                                                                              
0|web      |     at ConnectionManager.registerChildWatcher (/Users/xxx/yyy/ng-web/node_modules/node-zookeeper-client/lib/
ConnectionManager.js:177:25)                                                                                                      
0|web      |     at Object.callback (/Users/xxx/yyy/ng-web/node_modules/node-zookeeper-client/index.js:806:44)           
0|web      |     at ConnectionManager.onSocketData (/Users/xxx/yyy/ng-web/node_modules/node-zookeeper-client/lib/Connecti
onManager.js:562:35)                                                                                                              
0|web      |     at ZoneDelegate.invokeTask (/Users/xxx/yyy/ng-web/node_modules/zone.js/dist/zone-node.js:236:37)        
0|web      |     at Zone.runTask (/Users/xxx/yyy/ng-web/node_modules/zone.js/dist/zone-node.js:136:47)                   
0|web      |     at Socket.ZoneTask.invoke (/Users/xxx/yyy/ng-web/node_modules/zone.js/dist/zone-node.js:304:33)         
0|web      |     at emitOne (events.js:96:13)                                                                                     
0|web      |     at Socket.emit (events.js:188:7)                                                                                 
0|web      |     at readableAddChunk (_stream_readable.js:176:18)                                                                 
0|web      |     at Socket.Readable.push (_stream_readable.js:134:10)                                                             
0|web      |     at TCP.onread (net.js:548:20)                                                                                    
PM2        | App name:web id:0 disconnected                                                                                       
PM2        | App [web] with id [0] and pid [17702], exited with code [7] via signal [SIGINT]                                      
PM2        | Starting execution sequence in -cluster mode- for app name:web id:0                                                  
PM2        | App name:web id:0 online                                                                                             
0|web      | { _: [], log_dir: '/var/tmp' }                                                                                       
0|web      | Tue, 11 Apr 2017 18:43:14 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at dist/i
ndex.js:7367:22                                                                                                                   
0|web      | Tue, 11 Apr 2017 18:43:14 GMT body-parser deprecated undefined extended: provide extended option at node_modules/body
-parser/index.js:105:29     

Thanks for your contribution!

**Comment by RTChowdary** [comment]
This problem is because of a bug in the zone.js versions(0.6.22-0.6.25). This bug is fixed in 0.6.26 and above versions.
