### ISSUE TITLE
Gzip compression doesn't work in 2.1.0

### ISSUE THREAD

**Issue by kosik86** [SOHU-Co/kafka-node#736]
I've found a problem with the latest 2.1.0 version.
I use gzip compression by default and everything worked as expected in kafka-node@2.0.1. 
The `HighLevelProducer` is unable to send any message after I upgraded to 2.1.0.

* Node version: 6.10.x
* Kafka-node version: 2.1.0
* Kafka version: 0.9

### How to reproduce

Run the following code using kafka-node 2.0.1 and 2.1.0.
```js
const kafka_node = require("kafka-node");

const options = {
    "encoding": "utf8",
    "kafkaHost": "localhost:9092",
    "autoCommit": true,
    "autoCommitIntervalMs": 500
}, producer = new kafka_node.HighLevelProducer(new kafka_node.KafkaClient(options));


producer.send([{
        topic: "test",
        messages: ["testMessage"],
        attributes: 1
    }], (error, data) => {

    	console.log(error, data);
});

```

At the same time, I have Kafka console consumer running and it crashes when I sent a message using kafka-node@2.1.0:

```
[2017-08-07 14:28:04,198] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
java.lang.IllegalArgumentException
```

The only way to make it work in kafka-node@2.1.0 is changing `attributes` from 1 to 0 to disable compression. However, I can't see any breaking changes mentioned for `2.1.0` and I assume this is a bug.

**Comment by hyperlink** [comment]
This seems to work for me. I'm using `KAFKA_VERSION=0.9 ./start-docker.sh` to start kafka 0.9. Maybe your broker settings are different?

```
14:41 $ node
> const kafka_node = require('.')
undefined
> const options = {
...     "encoding": "utf8",
...     "kafkaHost": "localhost:9092",
...     "autoCommit": true,
...     "autoCommitIntervalMs": 500
... }, producer = new kafka_node.HighLevelProducer(new kafka_node.KafkaClient(options));
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +2ms
undefined
>   kafka-node:KafkaClient Sending versions request to localhost:9092 +7ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +2ms
  kafka-node:KafkaClient updating metadatas +13ms
  kafka-node:KafkaClient getApiVersions request timedout probably less than 0.10 using base support +489ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":1,"usable":1},"fetch":{"min":0,"max":0,"usable":0},"offset":{"min":0,"max":0,"usable":0},"metadata":{"min":0,"max":0,"usable":0},"leader":null,"stopReplica":null,"updateMetadata":null,"controlledShutdown":null,"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":0,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":null,"listGroups":null,"saslHandshake":null,"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":null,"deleteTopics":null} +0ms

> producer.send([{
...         topic: "test",
...         messages: ["testMessage"],
...         attributes: 1
...     }], (error, data) => {
...
...         console.log(error, data);
... });
  kafka-node:KafkaClient compressing messages if needed +25s
undefined
>   kafka-node:KafkaClient checking payload topic/partitions has leaders +15ms
  kafka-node:KafkaClient found leaders for all +0ms
  kafka-node:KafkaClient sending request +0ms
  kafka-node:KafkaClient grouped requests by 1 brokers ["1001"] +1ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +2ms
  kafka-node:KafkaClient Sending versions request to 127.0.0.1:9092 +0ms
  kafka-node:KafkaClient getApiVersions request timedout probably less than 0.10 using base support +504ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":1,"usable":1},"fetch":{"min":0,"max":0,"usable":0},"offset":{"min":0,"max":0,"usable":0},"metadata":{"min":0,"max":0,"usable":0},"leader":null,"stopReplica":null,"updateMetadata":null,"controlledShutdown":null,"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":0,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":null,"listGroups":null,"saslHandshake":null,"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":null,"deleteTopics":null} +1ms
  kafka-node:KafkaClient broker is now ready +0ms
  kafka-node:KafkaClient Using V1 of produce +0ms
null { test: { '0': 1 } }
```

```
kafka_1      | waiting for kafka to be ready
kafka_1      | [2017-08-07 18:38:02,601] INFO KafkaConfig values:
kafka_1      | 	advertised.host.name = 127.0.0.1
kafka_1      | 	metric.reporters = []
kafka_1      | 	quota.producer.default = 9223372036854775807
kafka_1      | 	offsets.topic.num.partitions = 50
kafka_1      | 	log.flush.interval.messages = 9223372036854775807
kafka_1      | 	auto.create.topics.enable = true
kafka_1      | 	controller.socket.timeout.ms = 30000
kafka_1      | 	log.flush.interval.ms = null
kafka_1      | 	principal.builder.class = class org.apache.kafka.common.security.auth.DefaultPrincipalBuilder
kafka_1      | 	replica.socket.receive.buffer.bytes = 65536
kafka_1      | 	min.insync.replicas = 1
kafka_1      | 	replica.fetch.wait.max.ms = 500
kafka_1      | 	num.recovery.threads.per.data.dir = 1
kafka_1      | 	ssl.keystore.type = JKS
kafka_1      | 	default.replication.factor = 1
kafka_1      | 	ssl.truststore.password = [hidden]
kafka_1      | 	log.preallocate = false
kafka_1      | 	sasl.kerberos.principal.to.local.rules = [DEFAULT]
kafka_1      | 	fetch.purgatory.purge.interval.requests = 1000
kafka_1      | 	ssl.endpoint.identification.algorithm = null
kafka_1      | 	replica.socket.timeout.ms = 30000
kafka_1      | 	message.max.bytes = 1000012
kafka_1      | 	num.io.threads = 8
kafka_1      | 	offsets.commit.required.acks = -1
kafka_1      | 	log.flush.offset.checkpoint.interval.ms = 60000
kafka_1      | 	delete.topic.enable = false
kafka_1      | 	quota.window.size.seconds = 1
kafka_1      | 	ssl.truststore.type = JKS
kafka_1      | 	offsets.commit.timeout.ms = 5000
kafka_1      | 	quota.window.num = 11
kafka_1      | 	zookeeper.connect = zookeeper:2181
kafka_1      | 	authorizer.class.name =
kafka_1      | 	num.replica.fetchers = 1
kafka_1      | 	log.retention.ms = null
kafka_1      | 	log.roll.jitter.hours = 0
kafka_1      | 	log.cleaner.enable = true
kafka_1      | 	offsets.load.buffer.size = 5242880
kafka_1      | 	log.cleaner.delete.retention.ms = 86400000
kafka_1      | 	ssl.client.auth = none
kafka_1      | 	controlled.shutdown.max.retries = 3
kafka_1      | 	queued.max.requests = 500
kafka_1      | 	offsets.topic.replication.factor = 3
kafka_1      | 	log.cleaner.threads = 1
kafka_1      | 	sasl.kerberos.service.name = null
kafka_1      | 	sasl.kerberos.ticket.renew.jitter = 0.05
kafka_1      | 	socket.request.max.bytes = 104857600
kafka_1      | 	ssl.trustmanager.algorithm = PKIX
kafka_1      | 	zookeeper.session.timeout.ms = 6000
kafka_1      | 	log.retention.bytes = -1
kafka_1      | 	sasl.kerberos.min.time.before.relogin = 60000
kafka_1      | 	zookeeper.set.acl = false
kafka_1      | 	connections.max.idle.ms = 600000
kafka_1      | 	offsets.retention.minutes = 1440
kafka_1      | 	replica.fetch.backoff.ms = 1000
kafka_1      | 	inter.broker.protocol.version = 0.9.0.X
kafka_1      | 	log.retention.hours = 168
kafka_1      | 	num.partitions = 1
kafka_1      | 	broker.id.generation.enable = true
kafka_1      | 	listeners = PLAINTEXT://:9092,SSL://:9093
kafka_1      | 	ssl.provider = null
kafka_1      | 	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
kafka_1      | 	log.roll.ms = null
kafka_1      | 	log.flush.scheduler.interval.ms = 9223372036854775807
kafka_1      | 	ssl.cipher.suites = null
kafka_1      | 	log.index.size.max.bytes = 10485760
kafka_1      | 	ssl.keymanager.algorithm = SunX509
kafka_1      | 	security.inter.broker.protocol = PLAINTEXT
kafka_1      | 	replica.fetch.max.bytes = 1048576
kafka_1      | 	advertised.port = 9092
kafka_1      | 	log.cleaner.dedupe.buffer.size = 134217728
kafka_1      | 	replica.high.watermark.checkpoint.interval.ms = 5000
kafka_1      | 	log.cleaner.io.buffer.size = 524288
kafka_1      | 	sasl.kerberos.ticket.renew.window.factor = 0.8
kafka_1      | 	zookeeper.connection.timeout.ms = 6000
kafka_1      | 	controlled.shutdown.retry.backoff.ms = 5000
kafka_1      | 	log.roll.hours = 168
kafka_1      | 	log.cleanup.policy = delete
kafka_1      | 	host.name =
kafka_1      | 	log.roll.jitter.ms = null
kafka_1      | 	max.connections.per.ip = 2147483647
kafka_1      | 	offsets.topic.segment.bytes = 104857600
kafka_1      | 	background.threads = 10
kafka_1      | 	quota.consumer.default = 9223372036854775807
kafka_1      | 	request.timeout.ms = 30000
kafka_1      | 	log.index.interval.bytes = 4096
kafka_1      | 	log.dir = /tmp/kafka-logs
kafka_1      | 	log.segment.bytes = 1073741824
kafka_1      | 	log.cleaner.backoff.ms = 15000
kafka_1      | 	offset.metadata.max.bytes = 4096
kafka_1      | 	ssl.truststore.location = /var/private/ssl/certs/server.truststore.jks
kafka_1      | 	group.max.session.timeout.ms = 30000
kafka_1      | 	ssl.keystore.password = [hidden]
kafka_1      | 	zookeeper.sync.time.ms = 2000
kafka_1      | 	port = 9092
kafka_1      | 	log.retention.minutes = null
kafka_1      | 	log.segment.delete.delay.ms = 60000
kafka_1      | 	log.dirs = /kafka/kafka-logs-925be2b61c28
kafka_1      | 	controlled.shutdown.enable = true
kafka_1      | 	compression.type = producer
kafka_1      | 	max.connections.per.ip.overrides =
kafka_1      | 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
kafka_1      | 	log.cleaner.io.max.bytes.per.second = 1.7976931348623157E308
kafka_1      | 	auto.leader.rebalance.enable = true
kafka_1      | 	leader.imbalance.check.interval.seconds = 300
kafka_1      | 	log.cleaner.min.cleanable.ratio = 0.5
kafka_1      | 	replica.lag.time.max.ms = 10000
kafka_1      | 	num.network.threads = 3
kafka_1      | 	ssl.key.password = [hidden]
kafka_1      | 	reserved.broker.max.id = 1000
kafka_1      | 	metrics.num.samples = 2
kafka_1      | 	socket.send.buffer.bytes = 102400
kafka_1      | 	ssl.protocol = TLS
kafka_1      | 	socket.receive.buffer.bytes = 102400
kafka_1      | 	ssl.keystore.location = /var/private/ssl/certs/server.keystore.jks
kafka_1      | 	replica.fetch.min.bytes = 1
kafka_1      | 	unclean.leader.election.enable = true
kafka_1      | 	group.min.session.timeout.ms = 6000
kafka_1      | 	log.cleaner.io.buffer.load.factor = 0.9
kafka_1      | 	offsets.retention.check.interval.ms = 600000
kafka_1      | 	producer.purgatory.purge.interval.requests = 1000
kafka_1      | 	metrics.sample.window.ms = 30000
kafka_1      | 	broker.id = -1
kafka_1      | 	offsets.topic.compression.codec = 0
kafka_1      | 	log.retention.check.interval.ms = 300000
kafka_1      | 	advertised.listeners = PLAINTEXT://127.0.0.1:9092,SSL://127.0.0.1:9093
kafka_1      | 	leader.imbalance.per.broker.percentage = 10
kafka_1      |  (kafka.server.KafkaConfig)
```

**Comment by kosik86** [comment]
@hyperlink I can send a message - this works fine. However,  the problem occurs when consuming that message.
I use the following command to test it:
```
./bin/kafka-console-consumer.sh --zookeeper localhost:2181  --topic test
```

Instead of seeing new messages the consumer terminates with the error:
```
[2017-08-07 21:05:25,618] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:275)
	at kafka.message.Message.sliceDelimited(Message.scala:237)
	at kafka.message.Message.key(Message.scala:224)
	at kafka.message.MessageAndMetadata.key(MessageAndMetadata.scala:30)
	at kafka.consumer.OldConsumer.receive(BaseConsumer.scala:83)
	at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:109)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:69)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:47)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
```

Also, I tested this behaviour by running `ConsumerGroup`.

This is what the consumer receives:
* `2.1.0` with compression
```javascript
{ topic: 'test',
  value: '',
  offset: 68,
  partition: 0,
  highWaterOffset: undefined,
  key: '�\u001d�\u0012����\u0000\u0000\u0000\u000btestMessage' }
```
* 2.1.0 no compression
```javascript
{ topic: 'test',
  value: 'testMessage',
  offset: 74,
  partition: 0,
  highWaterOffset: 75,
  key: null }
```


* 2.0.1 with compression
```js
  { topic: 'test',
  value: 'testMessage',
  offset: 69,
  partition: 0,
  highWaterOffset: undefined,
  key: null }
```


@hyperlink  am I doing something wrong?

**Comment by hyperlink** [comment]
@kosik86 this is a bug. I will look into it.

**Comment by hyperlink** [comment]
@kosik86 anyway you could test `master` to see if it's fixed for you?

**Comment by kosik86** [comment]
@hyperlink yes, I can confirm, `master` works for me.

**Comment by hyperlink** [comment]
Published as v2.2.0

**Comment by kosik86** [comment]
I tested 2.2.0 again and as expected I can use `ConsumerGroup` to consume messages sent by `HighLevelProducer` but still having issues with Kafka console-consumer.

@hyperlink is this expected that `kafka-console-consumer.sh` won't be able to consume messages of the new structure?
The only difference I can see when inspecting a raw message received by `ConsumerGroup` is the new field `timestamp`.

* Message sent by HighLevelProducer in @2.0.1
```
{ topic: 'test',
  value: 'testMessage',
  offset: 12910,
  partition: 0,
  highWaterOffset: undefined,
  key: null }
```
* Message sent by HighLevelProducer in @2.2.0
```
{ topic: 'test',
  value: 'testMessage',
  offset: 12911,
  partition: 0,
  highWaterOffset: undefined,
  key: null,
  timestamp: 2017-08-09T08:21:13.694Z }
```
The second message crashes the console consumer:
```
$ ./bin/kafka-console-consumer.sh --zookeeper localhost:2181  --topic test 
[2017-08-09 10:29:44,920] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:275)
	at kafka.message.Message.sliceDelimited(Message.scala:237)
	at kafka.message.Message.key(Message.scala:224)
	at kafka.message.MessageAndMetadata.key(MessageAndMetadata.scala:30)
	at kafka.consumer.OldConsumer.receive(BaseConsumer.scala:83)
	at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:109)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:69)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:47)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
Processed a total of 0 messages
```

**Comment by hyperlink** [comment]
@kosik86 console consumer works for me using kafka/bin `0.9.0.1`
