### ISSUE TITLE
BrokerNotAvailableError: Could not find the leader

### ISSUE THREAD

**Issue by nithingit** [SOHU-Co/kafka-node#741]
I am running my app with 2node kafka cluster.The toipic is created with replication factor 2 and 4 partitions,so there are 2 in sync replicas and each node is leader to 2 partitions.

When i manually pull down one node ,I can see that all partitions will have the same leade,but some of the messages(like 2 out of 100) are lost may be during leader switching in the middle.

I tried using the retries config while creating the producer ,but that doesn't seem to work.I am using kafka-node 1.6.

{ BrokerNotAvailableError: Could not find the leader
    at new BrokerNotAvailableError (C:\Users\nithin.a\Desktop\asp_handler\node_modules\kafka-node\lib\errors\BrokerNotAvailableError.js:11:9)
    at Client.sendToBroker (C:\Users\nithin.a\Desktop\asp_handler\node_modules\kafka-node\lib\client.js:551:17)
    at Client.send (C:\Users\nithin.a\Desktop\asp_handler\node_modules\kafka-node\lib\client.js:510:10)
    at C:\Users\nithin.a\Desktop\asp_handler\node_modules\kafka-node\lib\client.js:220:10
    at C:\Users\nithin.a\Desktop\asp_handler\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (C:\Users\nithin.a\Desktop\asp_handler\node_modules\async\lib\async.js:236:30)
    at Object.async.forEach.async.each (C:\Users\nithin.a\Desktop\asp_handler\node_modules\async\lib\async.js:209:22)
    at Client.sendProduceRequest (C:\Users\nithin.a\Desktop\asp_handler\node_modules\kafka-node\lib\client.js:218:9)
    at HighLevelProducer.BaseProducer.send (C:\Users\nithin.a\Desktop\asp_handler\node_modules\kafka-node\lib\baseProducer.js:123:10)
    at Object.senddata (C:\Users\nithin.a\Desktop\asp_handler\src\main\modules\asp\utils\kafkautil.js:9:19) message: 'Could not find the leader' }

**Comment by hyperlink** [comment]
The caller of send is responsible for handling an error callback and sending the message again if it fails.

**Comment by sugir93** [comment]
Didnt get you? can you please explaining me why this is happening and how to fix it

**Comment by giftig** [comment]
@sugir93 he's saying the client is reporting an error from kafka, and you'll need to deal with it. If you're stuck with a kafka error you'll need to try to debug kafka, not the node kafka client.
