### ISSUE TITLE
Broker fail behavior

### ISSUE THREAD

**Issue by NikitaLiashenko** [SOHU-Co/kafka-node#756]
### Environment

* Node version: 8.1.2
* Kafka-node version: 2.2.2
* Kafka version: 0.11.0

### Configurations

**Client config:**
        kafkaHost: "localhost:9092,
        clientId: 'test-kafka-client-2',
        connectTimeout: 1000,
        requestTimeout: 60000,
        autoConnect: true
**Producer config:**
        requireAcks: 1,
        ackTimeoutMs: 100,
        partitionerType: 2
**Consumer config:**
        kafkaHost: 'localhost:9092',
        ssl: true,
        groupId: 'kafka-node-group',
        autoCommit: true,
        autoCommitIntervalMs: 500,
        fetchMaxWaitMs: 100,
        paused: false,
        maxNumSegments: 1000,
        fetchMinBytes: 1,
        fetchMaxBytes: 1024 * 1024,
        maxTickMessages: 1000,
        fromOffset: 'latest',
        outOfRangeOffset: 'earliest',
        sessionTimeout: 30000,
        retries: 10,
        retryFactor: 1.8,
        retryMinTimeout: 1000,
        connectOnReady: true,
        migrateHLC: false,
        migrateRolling: true,
        protocol: ['roundrobin']

### Problem

I am trying to write a server, which should wrap kafka-node library and work fine even if Kafka fails.
Currently there is a problem with consuming messages after broker recovery - multiple duplicates are presented. 

Recently I had an idea that the problem is in offset. F.e. we have consumed 20000 messages, but last autoCommit happened on 17000th message. Then Kafka fails and after recovery offset is still on 17000th message, so consumer start reading from 17001th message.

I have decided to set autoCommit to false and commit manually with `force: true` after every message received.
Unfortunately even if I haven't touch kafka there are multiple errors in commiting just because request was timed out.

Also I tried to pause consumer on commit and resume it on successful commit, but nothing changed.

I tried to look through the commiting strategy in source code of consumerGroup and highLevelConsumer files too and found that autoCommit and commit use same function. Also I've found that it uses setTimeout with autoCommitIntervalMs.
I suppose that if there is no autoCommitIntervalMs presented in consumer config commit will be done asap, but autoCommitIntervalMs equals to 5000 by default, so the commit doesn't happen right after the call.

Is there any way to commit right on `commit` function call?
Could you please suggest some solution for problem with duplicating?

**Comment by hyperlink** [comment]
How does this kafka failure happen? Is there a way a easy way I could reproduce this?

**Comment by NikitaLiashenko** [comment]
I do it by myself using terminal.
It's just a simulation of Kafka fail.
I need my wrapper to work ok when Kafka fails.

**Comment by hyperlink** [comment]
PR #758 could fix this issue you're having.

**Comment by hyperlink** [comment]
@NikitaLiashenko did the latest release resolve this issue for you?

**Comment by NikitaLiashenko** [comment]
@hyperlink I haven't checked yet.
I'll do it in the nearest days.

**Comment by NikitaLiashenko** [comment]
@hyperlink 
Looks like release 2.2.3 haven't fixed anything.
Let me explain the whole situation.

We are going to implement fault-tolerant wrapper on `kafka-node` module. What we are looking for is proper behavior when Kafka broker fails.

In our implementation we have something like message queue on produce and consume, cause we produce messages in batches and consume them one by one, then collect and return to outside code as batch.

Currently we want to handle situation when kafka broker fails and restarts properly.
We are trying to use autoCommit, but looks like there might be situation when messages we consumed, but commit was not sent to kafka, so offset was not updated.
Unfortunately we still see that our messages are duplicated. F.e. I've published 200000 messages recently and consumed 404014 messages instead.

We have also tried to do commit on every consume by typing `consumer.commit(true, callback)`  but looks like due to amount of messages `kafka-node` can't commit such many offsets, so we observe `Refused after 30000 milliseconds` error.

Could we please minimize time between commit call and actual commit somehow? I suppose this could solve problem with so many offsets to commit.
Could you please suggest some other solution which our team could use to solve such problem?

Thanks

**Comment by hyperlink** [comment]
Thanks for sharing your use case. It would be more helpful if you could provide some code examples and logs.

* afaik `kafka-node` does not have a `Refused after 30000 milliseconds` error.  Can you post what the exact error is?

* `consumer.commit` is just an alias for `consumer.autoCommit` and the call is throttled based on `autoCommitIntervalMs`. So it's not possible for the system to commit more often than what's specified by `autoCommitIntervalMs`. And `autoCommit` is automatically triggered after every fetch request.

**Comment by NikitaLiashenko** [comment]
@hyperlink 
Here is our repo https://github.com/devicehive/devicehive-ws-kafka-proxy/tree/Splitting
In examples folder you could find server, consumer and producer.

Regarding strange error here is an error log by pino package.
```{"pid":17928,"hostname":"nlyashenko","level":50,"time":1505998817040,"msg":"Request timed out after 30000ms","type":"Error","stack":"TimeoutError\n    at new TimeoutError (/home/nlyashenko/Projects/devicehive-ws-kafka-proxy/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)\n    at Timeout.setTimeout [as _onTimeout] (/home/nlyashenko/Projects/devicehive-ws-kafka-proxy/node_modules/kafka-node/lib/kafkaClient.js:384:14)\n    at ontimeout (timers.js:488:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:283:5)","message":"Request timed out after 30000ms","v":1}```

I've also tried to reduce `autoCommitIntervalMs` to 5ms, but got same error.

Thanks

**Comment by tmatvienko** [comment]
Hi @hyperlink !
Is there any update on described issue? It blocks us from moving further with kafka-node integration.

Regards,
Tatyana

**Comment by hyperlink** [comment]
Sorry, I haven't had a chance to investigate this. Been busy at work and I don't know if I will have any time in the future.

**Comment by tanmainaik** [comment]
Guys. any update on this, please.

**Comment by NikitaLiashenko** [comment]
@tanmainaik Unfortunately there are no updates on this. Still waiting for @hyperlink to investigate the problem. Our team's investigation has no results for now.

**Comment by arpitjain099** [comment]
Any updates on this one? I am also stuck with this issue

**Comment by NikitaLiashenko** [comment]
@arpitjain099 No updates from my side.
