### ISSUE TITLE
ensureBrokerReady Method Seems to Have Performance Issuse.

### ISSUE THREAD

**Issue by tangrui** [SOHU-Co/kafka-node#766]
The situation is hard to describe.

According to the following code, at the very begging, if there're many concurrent calls to the `sendRequest` method, then most of them will try to call `ensureBrokerReady` method, and will print many many "*missing apiSupport waiting until broker is ready...*" logs. After a while, the `ensureBrokerReady` methods calls back.

Since we have 3 brokers, so seems that the above progress will repeat for each broker. In the bad case, when more messages comes in, then the `waitUntilReady` method will not notify them in time. Then timeout is triggered.

But I try the Client class instead of the KafkaClient class and got no problem. I think whether the broker ensure will be done when the KafkaClient is ready. In another words, if the KafkaClient is ready, I hope all of the brokers will available directly. 

```
KafkaClient.prototype.sendRequest = function (request, callback) {
  logger.debug('sending request');
  const payloads = this.payloadsByLeader(request.data.payloads);

  logger.debug('grouped requests by %d brokers %j', Object.keys(payloads).length, Object.keys(payloads));

  const sendToBroker = async.ensureAsync((payload, leader, callback) => {
    const correlationId = this.nextId();

    const broker = this.brokerForLeader(leader);
    if (!broker || !broker.isConnected()) {
      callback(new errors.BrokerNotAvailableError('Broker not available (sendRequest)'));
      return;
    }

    const coder = getSupportedForRequestType(broker, request.type);

    const encoder = request.data.args != null ? coder.encoder.apply(null, request.data.args) : coder.encoder;
    const decoder = coder.decoder;

    const requestData = encoder(this.clientId, correlationId, payload);

    if (request.data.requireAcks === 0) {
      broker.writeAsync(requestData);
      callback(null, { result: 'no ack' });
    } else {
      this.queueCallback(broker.socket, correlationId, [decoder, callback]);
      broker.write(requestData);
    }
  });

  const ensureBrokerReady = async.ensureAsync((leader, callback) => {
    const broker = this.brokerForLeader(leader);
    if (broker.apiSupport == null) {
      logger.debug('missing apiSupport waiting until broker is ready...');
      this.waitUntilReady(broker, callback);
    } else {
      logger.debug('has apiSupport broker is ready');
      callback(null);
    }
  });

  async.mapValues(
    payloads,
    function (payload, leader, callback) {
      async.series(
        [
          function (callback) {
            ensureBrokerReady(leader, callback);
          },
          function (callback) {
            sendToBroker(payload, leader, callback);
          }
        ],
        function (error, results) {
          if (error) {
            return callback(error);
          }
          callback(null, _.last(results));
        }
      );
    },
    callback
  );
};
```

**Comment by hyperlink** [comment]
The client does not assume all nodes in the cluster are the same version at all times. The reason is during a rolling upgrade each node can be upgraded individually and be on different versions.  Tjhis can also be the case if the rollback is performed on the cluster.

We request the version API upon every new connection. As long as that connection is maintained the api version data for that node is cached.

Here are some thoughts on how to solve your issue:

1. throttle producer sends so each request is sent serially you may want to do this anyway to maintain the order of your messages
2. increase request timeout or disable it entirely  set `requestTimeout` option to `false` to disable
3. version request is usually fast but connections against a v0.9 will wait for the timeout to infer it's 0.9 we will need to make a code change for this but we add a new option to fix to version 0.9 so we don't need to wait for a timeout

**Comment by tangrui** [comment]
Or another way, can you expose a separate API that I can do this by myself before sending a message. I've tried `initializeBroker` method but seems a little complicated.

And there's another problem with `waitUntilReady`, if a lot of messages comes in simultaneously, the broker ready event may be listened many times then cause `EventEmmiter` to complain a potential leak.

**Comment by hyperlink** [comment]
Hi @tangrui what if we change the meaning of the 'ready' event that producers emit when using the `KafkaClient`. Ready in the original zookeeper based Client means the brokers in the cluster have been discovered and the Producer/Consumer is ready to be used. for KafkaClient `ready` can instead mean that we've discovered the cluster AND preemptively connected to all the brokers and completed the initial API request.

What do you think?

**Comment by tangrui** [comment]
That would be great.

When I get a `ready` event, then I can promise to use the Producer/Customer.

**Comment by AlJohri** [comment]
hi @hyperlink, I think I'm running into this same issue as @tangrui described above:

>And there's another problem with waitUntilReady, if a lot of messages comes in simultaneously, the broker ready event may be listened many times then cause EventEmmiter to complain a potential leak.

I keep getting:

```
(node:10368) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 10.128.141.5:9092-ready listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:243:17)
    at KafkaClient.addListener (events.js:259:10)
    at KafkaClient.once (events.js:290:8)
    at KafkaClient.waitUntilReady (/Users/johria/Development/heliograf/apps/elex/node_modules/kafka-node/lib/kafkaClient.js:763:8)
    at async.ensureAsync (/Users/johria/Development/heliograf/apps/elex/node_modules/kafka-node/lib/kafkaClient.js:816:12)
    at /Users/johria/Development/heliograf/apps/elex/node_modules/async/dist/async.js:3269:12
    at /Users/johria/Development/heliograf/apps/elex/node_modules/async/dist/async.js:74:12
    at /Users/johria/Development/heliograf/apps/elex/node_modules/kafka-node/lib/kafkaClient.js:829:13
    at /Users/johria/Development/heliograf/apps/elex/node_modules/async/dist/async.js:3880:24
    at replenish (/Users/johria/Development/heliograf/apps/elex/node_modules/async/dist/async.js:1011:17)
```

I'm consuming messages from a topic and producing to another topic- I have a check that waits for the producer to be `ready`.

I receive this error this first time I try to write. On this first occurrence, it tries to send dozens of messages at once. If I comment out the part of the code that produces messages, the error goes away.

**Comment by AlJohri** [comment]
Looks like I fixed my issue by doing producer.send with an array of messages instead of one at a time.

**Comment by pefish** [comment]
> Hi @tangrui what if we change the meaning of the 'ready' event that producers emit when using the `KafkaClient`. Ready in the original zookeeper based Client means the brokers in the cluster have been discovered and the Producer/Consumer is ready to be used. for KafkaClient `ready` can instead mean that we've discovered the cluster AND preemptively connected to all the brokers and completed the initial API request.
> 
> What do you think?

I dont think that emitting event is a good way to notify ready, callback or promise may be good choice.
