### ISSUE TITLE
Compatibility issue with 0.9.0.1 with compression enabled

### ISSUE THREAD

**Issue by kosik86** [SOHU-Co/kafka-node#785]
I've reported this issue already as #736 but looks like it's not resolved.

Also I tested it using docker as suggested.
All tests below are performed on EC2 instance in AWS running Ubuntu 14.04 linux as I had some trouble running `start-docker.sh` script on my Mac.

### Environment

* Node version: 6.9
* Kafka-node version: 2.2.3
* Kafka version: 0.9.0.1 and 0.11.0

### How to  reproduce behavior

```js
const kafka_node = require("kafka-node");

const options = {
    "encoding": "utf8",
    "kafkaHost": "localhost:9092",
    "autoCommit": true,
    "autoCommitIntervalMs": 500
}, producer = new kafka_node.HighLevelProducer(new kafka_node.KafkaClient(options));


producer.send([{
        topic: "test",
        messages: ["testMessage"],
        attributes: 1
    }], (error, data) => {

    	console.log(error, data);
});
```

### Output when using Kafka 0.9.0.1

```
root@ip-172-31-31-162:/home/ubuntu/kafkaTest/kafka-node# KAFKA_VERSION=0.9 ./start-docker.sh
...
Status: Downloaded newer image for wurstmeister/kafka:0.9.0.1
Creating kafkanode_zookeeper_1 ... 
Creating kafkanode_zookeeper_1 ... done
Creating kafkanode_kafka_1 ... 
Creating kafkanode_kafka_1 ... done
```
```
root@ip-172-31-31-162:/home/ubuntu/kafkaTest# export DEBUG=kafka-node:*
root@ip-172-31-31-162:/home/ubuntu/kafkaTest# node
> const kafka_node = require("kafka-node");
undefined
> 
> const options = {
...     "encoding": "utf8",
...     "kafkaHost": "localhost:9092",
...     "autoCommit": true,
...     "autoCommitIntervalMs": 500
... }, producer = new kafka_node.HighLevelProducer(new kafka_node.KafkaClient(options));
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +2ms
undefined
> 
> 
> producer.send([{
...         topic: "test",
...         messages: ["testMessage"],
...         attributes: 1
...     }], (error, data) => {
... 
...     	console.log(error, data);
... });  kafka-node:KafkaClient Sending versions request to localhost:9092 +44ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +4ms
  kafka-node:KafkaClient updating metadatas +60ms
  kafka-node:KafkaClient getApiVersions request timedout probably less than 0.10 using base support +440ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":1,"usable":1},"fetch":{"min":0,"max":0,"usable":0},"offset":{"min":0,"max":0,"usable":0},"metadata":{"min":0,"max":0,"usable":0},"leader":null,"stopReplica":null,"updateMetadata":null,"controlledShutdown":null,"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":0,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":null,"listGroups":null,"saslHandshake":null,"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":null,"deleteTopics":null} +0ms

  kafka-node:KafkaClient compressing messages if needed +195ms
undefined
>   kafka-node:KafkaClient checking payload topic/partitions has leaders +7ms
  kafka-node:KafkaClient payloads has no leaders! Our metadata could be out of date try refreshingMetadata [ { topic: 'test',
    partition: 0,
    messages: [ [Object] ],
    attributes: 1 } ] +0ms
  kafka-node:Client refresh metadata currentAttempt 1 +3ms
  kafka-node:Client refresh metadata currentAttempt 2 +239ms
  kafka-node:KafkaClient updating metadatas +2ms
  kafka-node:KafkaClient sending request +2ms
  kafka-node:KafkaClient grouped requests by 1 brokers ["1001"] +0ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +6ms
  kafka-node:KafkaClient Sending versions request to 127.0.0.1:9092 +2ms
  kafka-node:KafkaClient getApiVersions request timedout probably less than 0.10 using base support +502ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":1,"usable":1},"fetch":{"min":0,"max":0,"usable":0},"offset":{"min":0,"max":0,"usable":0},"metadata":{"min":0,"max":0,"usable":0},"leader":null,"stopReplica":null,"updateMetadata":null,"controlledShutdown":null,"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":0,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":null,"listGroups":null,"saslHandshake":null,"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":null,"deleteTopics":null} +0ms
  kafka-node:KafkaClient broker is now ready +0ms
  kafka-node:KafkaClient Using V1 of produce +1ms
null { test: { '0': 0 } }
```

Then I used console consumer to print all messages:
```
root@ip-172-31-31-162:/home/ubuntu/kafkaTest# docker exec -it kafkanode_kafka_1  ./opt/kafka_2.11-0.9.0.1/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --new-consumer  --topic test --from-beginning
[2017-10-19 20:30:03,042] ERROR Uncaught error in request completion: (org.apache.kafka.clients.NetworkClient)
org.apache.kafka.common.KafkaException: Error deserializing key/value for partition test-0 at offset 0
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:628)
	at org.apache.kafka.clients.consumer.internals.Fetcher.handleFetchResponse(Fetcher.java:566)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$000(Fetcher.java:69)
	at org.apache.kafka.clients.consumer.internals.Fetcher$1.onSuccess(Fetcher.java:139)
	at org.apache.kafka.clients.consumer.internals.Fetcher$1.onSuccess(Fetcher.java:136)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.onComplete(ConsumerNetworkClient.java:380)
	
```

### Output when using Kafka 0.11.0.0

```
root@ip-172-31-31-162:/home/ubuntu/kafkaTest/kafka-node# KAFKA_VERSION=0.11 ./start-docker.sh
...
Creating kafkanode_zookeeper_1 ... 
Creating kafkanode_zookeeper_1 ... done
Creating kafkanode_kafka_1 ... 
Creating kafkanode_kafka_1 ... done
```
```
root@ip-172-31-31-162:/home/ubuntu/kafkaTest# node
> const kafka_node = require("kafka-node");
undefined
> 
> const options = {
...     "encoding": "utf8",
...     "kafkaHost": "localhost:9092",
...     "autoCommit": true,
...     "autoCommitIntervalMs": 500
... }, producer = new kafka_node.HighLevelProducer(new kafka_node.KafkaClient(options));
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +3ms
undefined
> 
> 
> producer.send([{
...         topic: "test",
...         messages: ["testMessage"],
...         attributes: 1
...     }], (error, data) => {
... 
...     	console.log(error, data);
... });  kafka-node:KafkaClient Sending versions request to localhost:9092 +42ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +9ms
  kafka-node:KafkaClient Received versions response from localhost:9092 +33ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":0,"usable":false},"22":{"min":0,"max":0,"usable":false},"23":{"min":0,"max":0,"usable":false},"24":{"min":0,"max":0,"usable":false},"25":{"min":0,"max":0,"usable":false},"26":{"min":0,"max":0,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":0,"usable":false},"29":{"min":0,"max":0,"usable":false},"30":{"min":0,"max":0,"usable":false},"31":{"min":0,"max":0,"usable":false},"32":{"min":0,"max":0,"usable":false},"33":{"min":0,"max":0,"usable":false},"produce":{"min":0,"max":3,"usable":2},"fetch":{"min":0,"max":5,"usable":0},"offset":{"min":0,"max":2,"usable":0},"metadata":{"min":0,"max":4,"usable":0},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":3,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":3,"usable":2},"offsetFetch":{"min":0,"max":3,"usable":1},"groupCoordinator":{"min":0,"max":1,"usable":0},"joinGroup":{"min":0,"max":2,"usable":0},"heartbeat":{"min":0,"max":1,"usable":0},"leaveGroup":{"min":0,"max":1,"usable":0},"syncGroup":{"min":0,"max":1,"usable":0},"describeGroups":{"min":0,"max":1,"usable":false},"listGroups":{"min":0,"max":1,"usable":false},"saslHandshake":{"min":0,"max":0,"usable":false},"apiVersions":{"min":0,"max":1,"usable":0},"createTopics":{"min":0,"max":2,"usable":false},"deleteTopics":{"min":0,"max":1,"usable":false}} +0ms
  kafka-node:KafkaClient updating metadatas +45ms

  kafka-node:KafkaClient compressing messages if needed +514ms
undefined
>   kafka-node:KafkaClient checking payload topic/partitions has leaders +6ms
  kafka-node:KafkaClient payloads has no leaders! Our metadata could be out of date try refreshingMetadata [ { topic: 'test',
    partition: 0,
    messages: [ [Object] ],
    attributes: 1 } ] +1ms
  kafka-node:Client refresh metadata currentAttempt 1 +2ms
  kafka-node:Client refresh metadata currentAttempt 2 +269ms
  kafka-node:KafkaClient updating metadatas +3ms
  kafka-node:KafkaClient sending request +1ms
  kafka-node:KafkaClient grouped requests by 1 brokers ["1001"] +1ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +5ms
  kafka-node:KafkaClient Sending versions request to 127.0.0.1:9092 +2ms
  kafka-node:KafkaClient Received versions response from 127.0.0.1:9092 +3ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":0,"usable":false},"22":{"min":0,"max":0,"usable":false},"23":{"min":0,"max":0,"usable":false},"24":{"min":0,"max":0,"usable":false},"25":{"min":0,"max":0,"usable":false},"26":{"min":0,"max":0,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":0,"usable":false},"29":{"min":0,"max":0,"usable":false},"30":{"min":0,"max":0,"usable":false},"31":{"min":0,"max":0,"usable":false},"32":{"min":0,"max":0,"usable":false},"33":{"min":0,"max":0,"usable":false},"produce":{"min":0,"max":3,"usable":2},"fetch":{"min":0,"max":5,"usable":0},"offset":{"min":0,"max":2,"usable":0},"metadata":{"min":0,"max":4,"usable":0},"leader":{"min":0,"max":0,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":3,"usable":false},"controlledShutdown":{"min":1,"max":1,"usable":false},"offsetCommit":{"min":0,"max":3,"usable":2},"offsetFetch":{"min":0,"max":3,"usable":1},"groupCoordinator":{"min":0,"max":1,"usable":0},"joinGroup":{"min":0,"max":2,"usable":0},"heartbeat":{"min":0,"max":1,"usable":0},"leaveGroup":{"min":0,"max":1,"usable":0},"syncGroup":{"min":0,"max":1,"usable":0},"describeGroups":{"min":0,"max":1,"usable":false},"listGroups":{"min":0,"max":1,"usable":false},"saslHandshake":{"min":0,"max":0,"usable":false},"apiVersions":{"min":0,"max":1,"usable":0},"createTopics":{"min":0,"max":2,"usable":false},"deleteTopics":{"min":0,"max":1,"usable":false}} +1ms
  kafka-node:KafkaClient broker is now ready +0ms
  kafka-node:KafkaClient Using V2 of produce +1ms
null { test: { '0': 0 } }
```
```
root@ip-172-31-31-162:/home/ubuntu/kafkaTest# docker exec -it kafkanode_kafka_1  ./opt/kafka_2.12-0.11.0.0/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --new-consumer  --topic test --from-beginning
testMessage

^CProcessed a total of 1 messages

```

**Comment by SirR4T** [comment]
ran across this issue, and consuming via `kafka-console-consumer.sh` was successful after removing `attributes: 1`.

**Comment by kosik86** [comment]
@SirR4T it works when you change/remove `attributes` because it disables compression. It won't solve the main problem.

**Comment by SirR4T** [comment]
Sure, just wanted to point out that disabling compression did indeed work for me. Could be useful for someone else running into this issue too?

Also, if we were to fix the main problem, how would we go about it? i'm a noob here, but am willing to take a shot at it.
