### ISSUE TITLE
Explicit metadata refresh required in producer after stopping or starting brokers?

### ISSUE THREAD

**Issue by thomaslee** [SOHU-Co/kafka-node#798]
Not sure if this is a bug or by design but per the title: it seems like I need to explicitly refresh broker metadata after stopping a broker on a failed attempt to produce with `kafka.Producer`. Presumably it's still trying to write to the broker that was taken offline & needs the metadata refresh to pick up the new partition leaders.

My code to repro looks something like:

```
const client = new kafka.KafkaClient({
  kafkaHost: "...",
  requestTimeout: 5000
})
const producer = new kafka.Producer({
  requireAcks: -1,
  ackTimeoutMs: 5000
})
producer.on('ready', () => {
  producer.send([{topic: '...', messages: ['test']}], (err, data) => {
    if (err) {
      console.log('failed', err)
      // need client.refreshBrokerMetadata(...) here for future attempts to succeed.
    }
  })
})
```

**Comment by hyperlink** [comment]
We try to call `refreshBrokerMetadata` whenever we encounter a `BrokerNotAvailableError`. It's done in several places in `client.js`. Are you not seeing this behavior?

**Comment by thomaslee** [comment]
@hyperlink using similar code to my repro case with a few console.log()s thrown in for good measure (_without_ the metadata refresh call), I get the following output. I stop the broker leading one of the partitions associated with shared-queue-1 right before the initial BrokerNotAvailableError then all the timeouts start spamming:

```
producing eb5576b8-9cbc-41a8-99c4-537f49bb3e23 to queue shared-queue-1
producing a9df4e12-aa17-42f1-b8f4-324ff8bc9680 to queue shared-queue-1
producing b04ae26c-662e-460d-aead-ba1298fb72da to queue shared-queue-1
producing b89c9627-bb21-4a50-8d11-bed0724a0b1b to queue shared-queue-1
producing 9078746d-a7be-4f44-b565-4e156f70ddee to queue shared-queue-1
producing b3432551-e8c1-4e94-ae43-062d42507709 to queue shared-queue-1
producing ef7f91d2-04c4-4537-9a82-c82d362905a8 to queue shared-queue-1
producing 7f0b2377-da9d-47ba-a0df-4acc272a02e4 to queue shared-queue-1
producing 58197bd2-cb7e-4200-b82f-dc45ba37ee03 to queue shared-queue-1
producing c60213bb-814e-4286-9e19-7390aef1d564 to queue shared-queue-1
producing 1e5d0771-882b-4126-a8b1-ab0d2d69014f to queue shared-queue-1
producing 8c75e5ed-8dc6-409d-90c1-1374e6b9ff1f to queue shared-queue-1
produce failed: { BrokerNotAvailableError: Broker not available (sendRequest)
    at new BrokerNotAvailableError ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at async.ensureAsync ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:659:16)
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:3255:12
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:74:12
    at $REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:699:13
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:3866:24
    at replenish ($REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:998:17)
    at iterateeCallback ($REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:983:17)
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:958:16
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:3871:13 message: 'Broker not available (sendRequest)' }
producing 3ad20478-ae30-4429-89a7-8d5f8853f25d to queue shared-queue-1
producing 19197526-ae47-43be-bd1a-06a1b110b6e8 to queue shared-queue-1
producing 5f367ead-c1c1-45ab-a99e-512f3d9e6cd9 to queue shared-queue-1
producing 6d15fc7e-f9df-4d20-8fe5-ebb0f8d8445e to queue shared-queue-1
producing 9d82a0e1-7cc1-4b01-b96d-91970400e7ab to queue shared-queue-1
producing 4a906a7f-8046-4623-8e0d-704cf752cf70 to queue shared-queue-1
producing 4c1cac9c-f7bf-4ac3-b562-e30c37ca917a to queue shared-queue-1
producing 864e44c6-f98c-4365-8ba6-f6b3ace8672a to queue shared-queue-1
producing 1399d5f3-2b05-405f-b253-680bbc856c86 to queue shared-queue-1
produce failed: { TimeoutError: Request timed out after 5000ms
    at new TimeoutError ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:642:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 5000ms' }
producing bd5422c6-d656-49a1-9c78-a62dc9e7cac2 to queue shared-queue-1
producing 2e0a5800-8178-4e47-b02b-b879167e5e33 to queue shared-queue-1
produce failed: { TimeoutError: Request timed out after 5000ms
    at new TimeoutError ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:642:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 5000ms' }
producing 2ff6fb87-fbf1-4985-bb58-acf9693b266a to queue shared-queue-1
producing 66d21ef5-4050-4465-b968-f2ab07447fa0 to queue shared-queue-1
produce failed: { TimeoutError: Request timed out after 5000ms
    at new TimeoutError ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:642:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 5000ms' }
producing 26138540-82e6-46dc-8171-ebce47231fcd to queue shared-queue-1
producing fd3c975d-f519-4097-8403-3d1c672cad26 to queue shared-queue-1
producing feb1d31b-9715-409f-8e65-139176baa369 to queue shared-queue-1
produce failed: { TimeoutError: Request timed out after 5000ms
    at new TimeoutError ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:642:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 5000ms' }
producing c36da665-0107-440a-befe-141205fb5b00 to queue shared-queue-1
producing 453efb2e-84f2-41ea-a09a-cc014e76a944 to queue shared-queue-1
produce failed: { TimeoutError: Request timed out after 5000ms
    at new TimeoutError ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:642:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 5000ms' }
producing 5c242e93-6258-4c7f-a8ad-5177be9f03d9 to queue shared-queue-1
produce failed: { TimeoutError: Request timed out after 5000ms
    at new TimeoutError ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:642:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 5000ms'
```

It seems to continue this way forever. When I add the metadata refresh call, the timeouts don't seem to occur:

```
producing 2f5a0cb3-f8ec-4804-a5ed-0df2564c0331 to queue shared-queue-1
producing 18cd6b9c-d7f7-4188-84b8-2ea16028e30b to queue shared-queue-1
producing c89bb368-a395-49de-a078-9ae52924d663 to queue shared-queue-1
producing 1ad1fd0a-e1ec-40ee-b095-b41e4498fae5 to queue shared-queue-1
produce failed: Error: NotLeaderForPartition
    at Object.<anonymous> ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/protocol/protocol.js:539:17)
    at Object.self.tap ($REDACTED_HOME/src/kafka-demo/node_modules/binary/index.js:248:12)
    at Object.decodePartitions ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/protocol/protocol.js:537:95)
    at Object.self.loop ($REDACTED_HOME/src/kafka-demo/node_modules/binary/index.js:267:16)
    at Object.<anonymous> ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/protocol/protocol.js:56:8)
    at Object.self.loop ($REDACTED_HOME/src/kafka-demo/node_modules/binary/index.js:267:16)
    at decodeProduceV2Response ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/protocol/protocol.js:531:6)
    at KafkaClient.Client.handleReceivedData ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/client.js:763:20)
    at Socket.<anonymous> ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:523:10)
    at emitOne (events.js:96:13)
producing 7128d46b-f77c-4bda-887a-d9d71182955f to queue shared-queue-1
producing c243ec65-0c92-4dba-a4ff-3cf9d2af2abc to queue shared-queue-1
produce failed: { BrokerNotAvailableError: Broker not available (sendRequest)
    at new BrokerNotAvailableError ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at async.ensureAsync ($REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:659:16)
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:3255:12
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:74:12
    at $REDACTED_HOME/src/kafka-demo/node_modules/kafka-node/lib/kafkaClient.js:699:13
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:3866:24
    at replenish ($REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:998:17)
    at iterateeCallback ($REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:983:17)
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:958:16
    at $REDACTED_HOME/src/kafka-demo/node_modules/async/dist/async.js:3871:13 message: 'Broker not available (sendRequest)' } 
producing c3a5cf2a-9872-4c14-81ba-b4842b58ac50 to queue shared-queue-1
producing 8e126553-c694-4bd8-b88e-a4ec115437f7 to queue shared-queue-1
producing 96c4268a-f0ef-4583-9198-1e6e5f0fadb5 to queue shared-queue-1
producing a36356c1-095e-4b44-a388-da5331b9ee0d to queue shared-queue-1
producing 7366170a-755e-426a-94f2-f88961a6c5e7 to queue shared-queue-1
producing 46bacd38-7f17-4f3a-a808-e98fa7f3ed9f to queue shared-queue-1
producing 97904be5-2098-4e50-a6ff-f4f9174d6444 to queue shared-queue-1
producing 44102446-fe21-4dc1-b457-73f0cc1d439c to queue shared-queue-1
producing 2b29efc6-9e3a-41d9-a8c2-7ddbf53b1c97 to queue shared-queue-1
producing 0effce3c-3501-40c1-88f7-d23ec2fda599 to queue shared-queue-1
```

**Comment by thomaslee** [comment]
Maybe worth noting consumers do just fine when the broker is stopped.

**Comment by hyperlink** [comment]
looks like we don't call `refreshBrokerMetadata` like we should be doing [here](https://github.com/SOHU-Co/kafka-node/blob/master/lib/kafkaClient.js#L734).
