### ISSUE TITLE
No topicNames crashes app.

### ISSUE THREAD

**Issue by artz** [SOHU-Co/kafka-node#800]
Hello, just reporting this as it seems the core lib should protect against this sort of error.

```kafka consumer error { Error: getaddrinfo ENOTFOUND broker.kafka broker.kafka:9092
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'broker.kafka',
  host: 'broker.kafka',
  port: '9092' }
/opt/app/node_modules/kafka-node/lib/client.js:491
  if (!topicNames.length) return cb();
                 ^

TypeError: Cannot read property 'length' of undefined
    at KafkaClient.Client.refreshMetadata (/opt/app/node_modules/kafka-node/lib/client.js:491:18)
    at ConsumerGroup.consumer.on (/opt/app/server/modules/mint/index.js:109:20)
    at emitOne (events.js:96:13)
    at ConsumerGroup.emit (events.js:191:7)
    at KafkaClient.<anonymous> (/opt/app/node_modules/kafka-node/lib/consumerGroup.js:124:10)
    at emitOne (events.js:96:13)
    at KafkaClient.emit (events.js:191:7)
    at connectToBrokers.error (/opt/app/node_modules/kafka-node/lib/kafkaClient.js:131:14)
    at async.doWhilst (/opt/app/node_modules/kafka-node/lib/kafkaClient.js:175:9)
    at /opt/app/node_modules/kafka-node/node_modules/async/dist/async.js:958:16```

**Comment by hyperlink** [comment]
@mehfooz-ul-haq are you having the same issue?
