### ISSUE TITLE
No definition for refreshBrokerMetadata() function of client

### ISSUE THREAD

**Issue by raeesaa** [SOHU-Co/kafka-node#816]
Hi,

I was facing some issues related to ConsumerGroup reconnection on broker failure and that is when I noticed in module codebase that there is not definition for `refreshBrokerMetadata()` function in client.js file despite of that function being called from few places. I am not sure if it is an issue or it was intentional.
Link: https://github.com/SOHU-Co/kafka-node/blob/master/lib/client.js#L282

Summary of the issue I faced related to reconnection:

I have kafka and zookeeper running in docker containers scaled to 3 instances each and ConsumerGroup written using this module. ConsumerGroup is able to consume messages from topic on starting process and also it is able to reconnect to broker on restarting any of the three brokers. However, problem arises when I stop broker container that ConsumerGroup is registered with. I would expect ConsumerGroup to reconnect with one of the other two brokers which are running but it fails to do and I end up getting `TimeoutError` in ConsumerGroup.

Debug logs:

```
Thu, 30 Nov 2017 11:10:15 GMT kafka-node:ConsumerGroup Connecting kafka-node-client
Thu, 30 Nov 2017 11:10:15 GMT kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: '10.42.99.89',
	coordinatorPort: 9092,
	coordinatorId: 1 }
Thu, 30 Nov 2017 11:10:15 GMT kafka-node:KafkaClient found 1 connected broker(s)
Thu, 30 Nov 2017 11:10:15 GMT kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { BrokerNotAvailableError
	at new BrokerNotAvailableError (/app/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
	at KafkaClient.Client.sendGroupRequest (/app/node_modules/kafka-node/lib/client.js:296:15)
	at KafkaClient.Client.sendJoinGroupRequest (/app/node_modules/kafka-node/lib/client.js:308:8)
	at /app/node_modules/kafka-node/lib/consumerGroup.js:454:21
	at nextTask (/app/node_modules/kafka-node/node_modules/async/dist/async.js:5310:14)
	at next (/app/node_modules/kafka-node/node_modules/async/dist/async.js:5317:9)
	at /app/node_modules/kafka-node/node_modules/async/dist/async.js:958:16
	at KafkaClient.wrappedFn (/app/node_modules/kafka-node/lib/kafkaClient.js:374:14)
	at KafkaClient.Client.handleReceivedData (/app/node_modules/kafka-node/lib/client.js:764:60)
	at Socket.<anonymous> (/app/node_modules/kafka-node/lib/kafkaClient.js:523:10)
	at emitOne (events.js:115:13)
	at Socket.emit (events.js:210:7)
	at addChunk (_stream_readable.js:266:12)
	at readableAddChunk (_stream_readable.js:253:11)
	at Socket.Readable.push (_stream_readable.js:211:10)
	at TCP.onread (net.js:585:20) message: 'Broker not available' }
Thu, 30 Nov 2017 11:10:15 GMT kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 5000 ms { BrokerNotAvailableError
	at new BrokerNotAvailableError (/app/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
	at KafkaClient.Client.sendGroupRequest (/app/node_modules/kafka-node/lib/client.js:296:15)
	at KafkaClient.Client.sendJoinGroupRequest (/app/node_modules/kafka-node/lib/client.js:308:8)
	at /app/node_modules/kafka-node/lib/consumerGroup.js:454:21
	at nextTask (/app/node_modules/kafka-node/node_modules/async/dist/async.js:5310:14)
	at next (/app/node_modules/kafka-node/node_modules/async/dist/async.js:5317:9)
	at /app/node_modules/kafka-node/node_modules/async/dist/async.js:958:16
	at KafkaClient.wrappedFn (/app/node_modules/kafka-node/lib/kafkaClient.js:374:14)
	at KafkaClient.Client.handleReceivedData (/app/node_modules/kafka-node/lib/client.js:764:60)
	at Socket.<anonymous> (/app/node_modules/kafka-node/lib/kafkaClient.js:523:10)
	at emitOne (events.js:115:13)
	at Socket.emit (events.js:210:7)
	at addChunk (_stream_readable.js:266:12)
	at readableAddChunk (_stream_readable.js:253:11)
	at Socket.Readable.push (_stream_readable.js:211:10)
	at TCP.onread (net.js:585:20) message: 'Broker not available' }

```

**Comment by kawtakwar** [comment]
Having same issue. Could you please look into @hyperlink ?. This is restricting us to use this library in production mode.

**Comment by hyperlink** [comment]
`refreshBrokerMetadata` is purposefully left unimplemented in `client.js`. This method is used to refresh the broker metadata directly from kafka and used exclusively by `KafkaClient`. Since `Client` performs broker discovery through zookeper it isn't necessary to have. Also client.js is deprecated so if possible use `KafkaClient`.

When a broker disappears you should expect to get errors such `BrokerNotAvailable`  but as the brokers eventually takes leadership of those partitions the client should eventually connect to the correct one. Let me know if that is not happening.

**Comment by raeesaa** [comment]
@hyperlink In my case ConsumerGroup does not connect to new leader when the broker it was registered with goes down. On debugging, I came to [this line](https://github.com/SOHU-Co/kafka-node/blob/master/lib/consumerGroup.js#L445) in ConsumerGroup code and found corresponding function defined in `client.js` which eventually calls `refreshBrokerMetadata` method when broker is not available. Maybe I misunderstood the flow. 

My setup:

- Running kafka and zookeeper via docker-compose at scale of 3.
- Producer written in java which publishes events to kafka.
- ConsumerGroup is created in node.js which consumes event.

Now when I stop kafka container ConsumerGroup was registered to, ConsumerGroup does not connect to new leader. 

We did not face this issue in case of Java producer, it properly connects to new leader.

**Comment by ApurvaB** [comment]
I am getting the same Issue.

**Comment by hyperlink** [comment]
@raeesaa `refreshBrokerMetadata` is overriden [here](https://github.com/SOHU-Co/kafka-node/blob/master/lib/kafkaClient.js#L285) when using `KafkaClient`.
