### ISSUE TITLE
Having issues when importing this package to Angular 5

### ISSUE THREAD

**Issue by surajprgupta** [SOHU-Co/kafka-node#822]
I think because this package uses `require()`, I am having the issue.
Can you suggest a solution !!!

**Comment by surajprgupta** [comment]
Error Details
`import HighLevelConsumer from "kafka-node";`
`console.log(HighLevelConsumer);`

> [0] WARNING in ./node_modules/optional/optional.js
[0] 6:11-26 Critical dependency: the request of a dependency is an expression
[0]     at CommonJsRequireContextDependency.getWarnings (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
[0]     at Compilation.reportDependencyErrorsAndWarnings (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compilation.js:703:24)
[0]     at Compilation.finish (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compilation.js:561:9)
[0]     at applyPluginsParallel.err (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compiler.js:506:17)
[0]     at /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/tapable/lib/Tapable.js:289:11
[0]     at _addModuleChain (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compilation.js:507:11)
[0]     at processModuleDependencies.err (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compilation.js:477:14)
[0]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0]  @ ./node_modules/optional/optional.js
[0]  @ ./node_modules/kafka-node/lib/codec/snappy.js
[0]  @ ./node_modules/kafka-node/lib/codec/index.js
[0]  @ ./node_modules/kafka-node/lib/kafkaClient.js
[0]  @ ./node_modules/kafka-node/kafka.js
[0]  @ ./client/app/_pages/report/report.component.ts
[0]  @ ./client/app/app.module.ts
[0]  @ ./client/main.ts
[0]  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./client/main.ts
[0] 
[0] WARNING in ./node_modules/node-zookeeper-client/lib/jute/index.js
[0] 771:20-47 Critical dependency: the request of a dependency is an expression
[0]     at CommonJsRequireContextDependency.getWarnings (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
[0]     at Compilation.reportDependencyErrorsAndWarnings (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compilation.js:703:24)
[0]     at Compilation.finish (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compilation.js:561:9)
[0]     at applyPluginsParallel.err (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compiler.js:506:17)
[0]     at /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/tapable/lib/Tapable.js:289:11
[0]     at _addModuleChain (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compilation.js:507:11)
[0]     at processModuleDependencies.err (/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/webpack/lib/Compilation.js:477:14)
[0]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0]  @ ./node_modules/node-zookeeper-client/lib/jute/index.js
[0]  @ ./node_modules/node-zookeeper-client/index.js
[0]  @ ./node_modules/kafka-node/lib/consumerGroupMigrator.js
[0]  @ ./node_modules/kafka-node/lib/consumerGroup.js
[0]  @ ./node_modules/kafka-node/kafka.js
[0]  @ ./client/app/_pages/report/report.component.ts
[0]  @ ./client/app/app.module.ts
[0]  @ ./client/main.ts
[0]  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./client/main.ts
[0] 
[0] ERROR in ./node_modules/buffermaker/test/BufferMaker.js
[0] Module not found: Error: Can't resolve 'should' in '/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/test'
[0] resolve 'should' in '/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/test'
[0]   Parsed request is a module
[0]   using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/package.json (relative path: ./test)
[0]     Field 'browser' doesn't contain a valid alias configuration
[0]   after using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/package.json (relative path: ./test)
[0]     resolve as module
[0]       /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/test/node_modules doesn't exist or is not a directory
[0]       /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/node_modules doesn't exist or is not a directory
[0]       /home/surajgupta/public_html/newamps/data-charts-application/node_modules doesn't exist or is not a directory
[0]       /home/surajgupta/public_html/newamps/node_modules doesn't exist or is not a directory
[0]       /home/surajgupta/public_html/node_modules doesn't exist or is not a directory
[0]       /home/surajgupta/node_modules doesn't exist or is not a directory
[0]       /home/node_modules doesn't exist or is not a directory
[0]       /node_modules doesn't exist or is not a directory
[0]       looking for modules in /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/node_modules
[0]         using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/package.json (relative path: ./node_modules)
[0]           Field 'browser' doesn't contain a valid alias configuration
[0]         after using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/package.json (relative path: ./node_modules)
[0]           using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/package.json (relative path: ./node_modules/should)
[0]             no extension
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/node_modules/should doesn't exist
[0]             .ts
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/node_modules/should.ts doesn't exist
[0]             .js
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/node_modules/should.js doesn't exist
[0]             as directory
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/node_modules/should doesn't exist
[0]       looking for modules in /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules
[0]         using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./node_modules)
[0]           Field 'browser' doesn't contain a valid alias configuration
[0]         after using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./node_modules)
[0]           using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./node_modules/should)
[0]             no extension
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should doesn't exist
[0]             .ts
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should.ts doesn't exist
[0]             .js
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should.js doesn't exist
[0]             as directory
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should doesn't exist
[0]       looking for modules in /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules
[0]         using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./node_modules)
[0]           Field 'browser' doesn't contain a valid alias configuration
[0]         after using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./node_modules)
[0]           using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./node_modules/should)
[0]             no extension
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should doesn't exist
[0]             .ts
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should.ts doesn't exist
[0]             .js
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should.js doesn't exist
[0]             as directory
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should doesn't exist
[0]       looking for modules in /home/surajgupta/public_html/newamps/data-charts-application/public/client
[0]         using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./client)
[0]           Field 'browser' doesn't contain a valid alias configuration
[0]         after using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./client)
[0]           using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./client/should)
[0]             no extension
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/client/should doesn't exist
[0]             .ts
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/client/should.ts doesn't exist
[0]             .js
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/client/should.js doesn't exist
[0]             as directory
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/client/should doesn't exist
[0]       looking for modules in /home/surajgupta/public_html/newamps/data-charts-application/public/client
[0]         using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./client)
[0]           Field 'browser' doesn't contain a valid alias configuration
[0]         after using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./client)
[0]           using description file: /home/surajgupta/public_html/newamps/data-charts-application/public/package.json (relative path: ./client/should)
[0]             no extension
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/client/should doesn't exist
[0]             .ts
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/client/should.ts doesn't exist
[0]             .js
[0]               Field 'browser' doesn't contain a valid alias configuration
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/client/should.js doesn't exist
[0]             as directory
[0]               /home/surajgupta/public_html/newamps/data-charts-application/public/client/should doesn't exist
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/test/node_modules]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/node_modules]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/node_modules]
[0] [/home/surajgupta/public_html/newamps/node_modules]
[0] [/home/surajgupta/public_html/node_modules]
[0] [/home/surajgupta/node_modules]
[0] [/home/node_modules]
[0] [/node_modules]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/node_modules/should]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/node_modules/should.ts]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should.ts]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/node_modules/should.js]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should.js]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/buffermaker/node_modules/should]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should.ts]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should.js]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/node_modules/should]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/client/should]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/client/should.ts]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/client/should.js]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/client/should]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/client/should]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/client/should.ts]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/client/should.js]
[0] [/home/surajgupta/public_html/newamps/data-charts-application/public/client/should]
[0]  @ ./node_modules/buffermaker/test/BufferMaker.js 1:0-17
[0]  @ ./node_modules/buffermaker ^.*BufferMaker$
[0]  @ ./node_modules/buffermaker/index.js
[0]  @ ./node_modules/kafka-node/lib/protocol/protocol.js
[0]  @ ./node_modules/kafka-node/lib/protocol/index.js
[0]  @ ./node_modules/kafka-node/kafka.js
[0]  @ ./client/app/_pages/report/report.component.ts
[0]  @ ./client/app/app.module.ts
[0]  @ ./client/main.ts
[0]  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./client/main.ts

**Comment by kosik86** [comment]
@surajprgupta this module is meant to be used with nodejs.

**Comment by surajprgupta** [comment]
Yes, I know that, and it's running fine with express js,
but I have front-end in Angular 2+(5)  and backend in express js,
and was trying to integrate it directly into the Angular,
To reduce the extra HTTP call to the backend server to access Kafka
@kosik86

**Comment by aikar** [comment]
@surajprgupta ... that's not how things work.

In order for that to ever work, your Kafka server would have to be open to the entire internet to do whatever it pleases with...

**Comment by hyperlink** [comment]
Unfortunately, this module will not work with Angular.
