### ISSUE TITLE
How to query the current list of topics for a consumer group

### ISSUE THREAD

**Issue by deitch** [SOHU-Co/kafka-node#861]
It is both: question and bug.

We are having an issue wherein a broker disappearing and coming back within a minute (same hostname, same IP, same port) leads to `BrokerNotAvailableError`. We try to reconnect using `refreshMetadata` (see sample reconnect code below). Eventually it does seem to reconnect, but the consumer group we use does not have any topics associated, and so no messages come through.

We cannot reproduce it with any reliability. That also means we cannot turn on debug logs and leave them on indefinitely.

We are hoping our own minimal logs would catch it.

1. How do we ask the `consumerGroup` what its current state of brokers and topics is?
2. Have you seen this, where `refreshMetadata` returns without error, but topics are unavailable?

### Environment

* Node version: 8.9.0
* Kafka-node version: 2.2.3
* Kafka version: 1.0.0

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 2

### Sample Reconnect Code

```js
      consumerGroup.on('error', (err) => {
        log.error(`error on consumerGroup ${groupName}`);
        log.error(err);
        // we can handle a broker not available error or a timeout error
        if (err && ((err.name === "BrokerNotAvailableError" && !reconnecting) || err.name === "TimeoutError")) {
          log.error("attempting reconnect");
          reconnecting = true;
          reconnectAttempts++;
          consumerGroup.client.refreshMetadata(consumerGroup.topics, (err) => {
            if (err != null) {
              log.error(`error refreshing metadata for consumer group: ${err}`);
              log.error(err.stack);
            } else {
              log.error(`reconnect successful`);
              reconnectAttempts = 0;
            }
            reconnecting = false;
          });
        }
      });
      consumerGroup.on('connect', () => {
        reconnectAttempts = 0;
        log.info(`Connected consumerGroup ${groupName}`);
      });
```

Logs:

```
2018-02-03T16:22:44.513Z - ^[[32minfo^[[39m: [streamloader:kafka] processed 80177 since Sat, 03 Feb 2018 05:28:43 GMT , kafka CONNECTED
2018-02-03T16:23:24.598Z - ^[[31merror^[[39m: [streamloader:kafka] error on consumerGroup influxloader-group
2018-02-03T16:23:24.598Z - ^[[31merror^[[39m: [streamloader:kafka]  BrokerNotAvailableError: Could not find the leader
    at new BrokerNotAvailableError (/app/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.Client.sendToBroker (/app/node_modules/kafka-node/lib/client.js:565:17)
    at KafkaClient.Client.send (/app/node_modules/kafka-node/lib/client.js:520:10)
    at KafkaClient.Client.sendFetchRequest (/app/node_modules/kafka-node/lib/client.js:208:8)
    at ConsumerGroup.HighLevelConsumer.fetch (/app/node_modules/kafka-node/lib/highLevelConsumer.js:573:15)
    at Immediate.<anonymous> (/app/node_modules/kafka-node/lib/consumerGroup.js:186:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

// repeat above lots

2018-02-03T16:23:32.348Z - ^[[31merror^[[39m: [streamloader:kafka] attempting reconnect
2018-02-03T16:23:40.795Z - ^[[31merror^[[39m: [streamloader:kafka] error refreshing metadata for consumer group: LeaderNotAvailable,LeaderNotAvailable
2018-02-03T16:23:40.795Z - ^[[31merror^[[39m: [streamloader:kafka]
2018-02-03T16:23:44.513Z - ^[[32minfo^[[39m: [streamloader] printing statistics
2018-02-03T16:23:44.513Z - ^[[32minfo^[[39m: [streamloader:influx] start:Sat, 03 Feb 2018 05:28:34 GMT ; processed:80259 ; averagePointsPerWrite:11 ; failedWrites:4 ; failedMessagesPermanent:0 ; failedMessagesTemporary:31
2018-02-03T16:23:44.513Z - ^[[32minfo^[[39m: [streamloader:kafka] processed 80259 since Sat, 03 Feb 2018 05:28:43 GMT , kafka DISCONNECTED: reconnect attempts 1
2018-02-03T16:23:54.483Z - ^[[31merror^[[39m: [streamloader:kafka] error on consumerGroup influxloader-group
2018-02-03T16:23:54.483Z - ^[[31merror^[[39m: [streamloader:kafka]  TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/app/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/kafka-node/lib/kafkaClient.js:384:14)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
2018-02-03T16:23:54.483Z - ^[[31merror^[[39m: [streamloader:kafka] attempting reconnect
2018-02-03T16:24:44.514Z - ^[[32minfo^[[39m: [streamloader] printing statistics
2018-02-03T16:24:44.514Z - ^[[32minfo^[[39m: [streamloader:influx] start:Sat, 03 Feb 2018 05:28:34 GMT ; processed:80259 ; averagePointsPerWrite:11 ; failedWrites:4 ; failedMessagesPermanent:0 ; failedMessagesTemporary:31
2018-02-03T16:24:44.514Z - ^[[32minfo^[[39m: [streamloader:kafka] processed 80259 since Sat, 03 Feb 2018 05:28:43 GMT , kafka CONNECTED
```

The `CONNECTED` message in the statistics line is defined as `reconnectAttempts == 0`.

Would love to provide more info, and even have the minimal logs tell us what the current Kafka connection state is. How?

**Comment by hyperlink** [comment]
`consumerGroup.topicPayloads` is the consumer's view of what topics/partitions/offsets it owns. And `consumerGroup.client.this.topicMetadata` is the client's view of what broker topics are available.

**Comment by deitch** [comment]
Thanks @hyperlink . 

So `topicMetadata` is *all* topics, while `topicPayloads` is _my_ topics, along with current state of each?

Any sense of what went wrong with our connection, and how to discover it? The brokers recovered, but this never seemed to. I cannot reproduce yet, but I think with each (supposedly) successful reconnection I will dump `topicPayloads` to the logs. Hopefully that will give insight.

**Comment by hyperlink** [comment]
@deitch does kafka logs around the time of the reconnects reveal anything?

I'm also pushing out `2.4.1` soon which contains another fix to help recover better. The goal being this module should be responsible for recovery and not the user of this library.

**Comment by deitch** [comment]
> does kafka logs around the time of the reconnects reveal anything?

Not much, I can try and grab them and have another look. We had 3 VMs each as a worker node, with a kafka pod on each. The VMs ran OS updates and rebooted, which is why we lost connections, but it should have recovered reasonably quickly.

> pushing out 2.4.1 soon which contains another fix to help recover better

Do you mean all of the error-catching, validating, and `refreshMetadata` I did above? That would be very nice indeed!

**Comment by deitch** [comment]
Here are some of the logs from one of the nodes at loss time, nothing exceptional there. I had to scrub some of the topic names because of confidentiality, replaced stuff with `xxxx`.

```
[2018-02-03 16:23:25,546] WARN [ReplicaFetcher replicaId=101, leaderId=102, fetcherId=0] Error in fetch to broker 102, request (type=FetchRequest, replicaId=101, maxWait=500, minBytes=1, maxBytes=1048576
0, fetchData={spark-cdr-0=(offset=0, logStartOffset=0, maxBytes=1048576), xxxx-webservice-0=(offset=0, logStartOffset=0, maxBytes=1048576), xxxx-video-0=(offset=0, logStartOffset=0,
 maxBytes=1048576), xxxx-webservice-0=(offset=1145162, logStartOffset=1052613, maxBytes=1048576), xxxx-video-0=(offset=2314566, logStartOffset=2272840, maxBytes=1048576), xxxx-session-0=(offset=4997048, logStartOffset=4843829, maxBytes=1048576), xxxx-callrouter-0=(offset=3426398, logStartOffset=3381031, maxBytes=1048576)}, isolationLevel=READ_UNCOMMITTED) (kafka
.server.ReplicaFetcherThread)
java.io.IOException: Connection to 102 was disconnected before the response was read
        at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:95)
        at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:96)
        at kafka.server.ReplicaFetcherThread.fetch(ReplicaFetcherThread.scala:205)
        at kafka.server.ReplicaFetcherThread.fetch(ReplicaFetcherThread.scala:41)
        at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:149)
        at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:64)
[2018-02-03 16:23:33,404] INFO [ReplicaFetcherManager on broker 101] Removed fetcher for partitions xxxx-video-0,spark-cdr-0,xxxx-callrouter-0,xxxx-webservice-0,xxxx-video-0,xxxx-webservice-0,xxxx-session-0 (kafka.server.ReplicaFetcherManager)
[2018-02-03 16:23:33,404] INFO [Partition xxxx-callrouter-0 broker=101] xxxx-callrouter-0 starts at Leader Epoch 60 from offset 3426398. Previous Leader Epoch was: 59 (kafka.clust
er.Partition)
[2018-02-03 16:23:33,405] INFO [Partition xxxx-video-0 broker=101] xxxx-video-0 starts at Leader Epoch 64 from offset 0. Previous Leader Epoch was: 63 (kafka.cluster.Partition)
[2018-02-03 16:23:33,406] INFO [Partition xxxx-session-0 broker=101] xxxx-session-0 starts at Leader Epoch 60 from offset 4997048. Previous Leader Epoch was: 59 (kafka.cluster.Partition)
[2018-02-03 16:23:33,406] INFO [Partition xxxx-video-0 broker=101] xxxx-video-0 starts at Leader Epoch 62 from offset 2314566. Previous Leader Epoch was: 61 (kafka.cluster.Partition)
[2018-02-03 16:23:33,406] INFO [Partition xxxx-webservice-0 broker=101] xxxx-webservice-0 starts at Leader Epoch 65 from offset 0. Previous Leader Epoch was: 64 (kafka.cluster.Partition)
[2018-02-03 16:23:33,406] INFO [Partition xxxx-webservice-0 broker=101] xxxx-webservice-0 starts at Leader Epoch 65 from offset 1145162. Previous Leader Epoch was: 64 (kafka.cluster.Partition)
[2018-02-03 16:23:33,406] INFO [Partition xxxx-0 broker=101] xxxx-0 starts at Leader Epoch 66 from offset 0. Previous Leader Epoch was: 65 (kafka.cluster.Partition)
[2018-02-03 16:23:33,406] INFO [ReplicaFetcher replicaId=101, leaderId=102, fetcherId=0] Shutting down (kafka.server.ReplicaFetcherThread)
[2018-02-03 16:23:35,858] INFO [Partition xxxx-session-0 broker=101] Shrinking ISR from 102,101 to 101 (kafka.cluster.Partition)
[2018-02-03 16:23:35,862] INFO [Partition __consumer_offsets-13 broker=101] Shrinking ISR from 102,103,101 to 103,101 (kafka.cluster.Partition)
[2018-02-03 16:23:35,866] INFO [Partition __consumer_offsets-46 broker=101] Shrinking ISR from 102,103,101 to 103,101 (kafka.cluster.Partition)
[2018-02-03 16:23:35,869] INFO [Partition __consumer_offsets-9 broker=101] Shrinking ISR from 102,103,101 to 103,101 (kafka.cluster.Partition)
[2018-02-03 16:23:35,872] INFO [Partition __consumer_offsets-42 broker=101] Shrinking ISR from 102,103,101 to 103,101 (kafka.cluster.Partition)
[2018-02-03 16:23:35,877] INFO [Partition xxxx-callrouter-0 broker=101] Shrinking ISR from 102,101 to 101 (kafka.cluster.Partition)
[2018-02-03 16:23:35,879] INFO [Partition xxxx-hsi-0 broker=101] Shrinking ISR from 102,101 to 101 (kafka.cluster.Partition)
...
[2018-02-03 16:24:50,211] INFO [Partition __consumer_offsets-15 broker=101] Expanding ISR from 103,101 to 103,101,102 (kafka.cluster.Partition)
[2018-02-03 16:24:57,419] INFO [ReplicaFetcherManager on broker 101] Removed fetcher for partitions __consumer_offsets-22,__consumer_offsets-30,__consumer_offsets-8,__consumer_offsets-21,__consumer_offsets-4,__consumer_offsets-27,__consumer_offsets-7,__consumer_offsets-9,generic-0,__consumer_offsets-25,__consumer_offsets-35,__consumer_offsets-41,__consumer_offsets-33,__consumer_offsets-23,__consumer_offsets-49,__consumer_offsets-47,__consumer_offsets-16,__consumer_offsets-28,__consumer_offsets-31,__consumer_offsets-36,__consumer_offsets-42,ivr-cdr-0,__consumer_offsets-3,__consumer_offsets-18,__consumer_offsets-37,__consumer_offsets-15,__consumer_offsets-24,__consumer_offsets-38,__consumer_offsets-17,__consumer_offsets-48,spark-cdr-0,__consumer_offsets-19,__consumer_offsets-11,__consumer_offsets-13,__consumer_offsets-2,__consumer_offsets-6,xxxx-callrouter-0,__consumer_offsets-14,xxxx-session-0,xxxx-webservice-0,xxxx-hsi-0,__consumer_offsets-20,__consumer_offsets-0,__consumer_offsets-44,__consumer_offsets-39,xxxx-phone-0,xxxx-video-0,__consumer_offsets-12,__consumer_offsets-45,__consumer_offsets-1,__consumer_offsets-5,__consumer_offsets-26,__consumer_offsets-29,__consumer_offsets-34,__consumer_offsets-10,__consumer_offsets-32,__consumer_offsets-40 (kafka.server.ReplicaFetcherManager)
[2018-02-03 16:24:57,419] INFO [Partition __consumer_offsets-0 broker=101] __consumer_offsets-0 starts at Leader Epoch 60 from offset 0. Previous Leader Epoch was: 59 (kafka.cluster.Partition)
[2018-02-03 16:24:57,420] INFO [Partition xxxx-callrouter-0 broker=101] xxxx-callrouter-0 starts at Leader Epoch 69 from offset 0. Previous Leader Epoch was: 68 (kafka.cluster.Partition)
```

**Comment by hyperlink** [comment]
2.4.1 is published.

`KafkaClient` will try to request metadata to a available broker before we yield requests with `BrokerNotAvailableError` so refreshing manually may not be necessary.

**Comment by deitch** [comment]
> 2.4.1 is published

Nice! I see it on npm.

> KafkaClient will try to request metadata to a available broker before we yield requests with BrokerNotAvailableError so refreshing manually may not be necessary

So all my code will just go away? That would be a pleasure. What if no brokers are available, or the leader isn't, and the kafka cluster is electing a new topic leader? What happens during that time, and how many retries / how long between retries?

**Comment by hyperlink** [comment]
Retries are based on the options passed into the the `ConsumerGroup`. The default values are

```
{
  retries: 10,
  retryFactor: 1.8,
  retryMinTimeout: 1000
}
```

The idea is any `BrokerNotAvailableError` should trigger a refresh of the metadata and if that metadata is out of date then the retries should also fail with `BrokerNotAvailableError` again and get another set of metadata and so on until things are back to normal.

**Comment by deitch** [comment]
Ah, so those retry options would apply not just to initial connections, but all followups when suddenly `BrokerNotAvailable`? I like it. I think it fits with the flow.

I think we can close out this issue. Let me just ask a few questions:

1. Would it handle all of those, including `LeaderNotAvailable`? Is that just a subset of `BrokerNotAvailable`?
2. Can I set the retries to infinite? I guess I can just put a really high number?
3. What happens when it hits its limit? 
4. Is there any way I can be notified (without turning on debug logging) of lost connection and retries? We have once-per-minute status/statistics logging, would like to be able to redo what we have above, query if it is connected and how many retries it has made if not connected.
5. Would it effectively replace the logic I have above? Or do I need to keep anything? We rely on that "catch an error and retry" as crucial, so want to make sure I got it covered. Copying the logic here:

```js
      consumerGroup.on('error', (err) => {
        log.error(`error on consumerGroup ${groupName}`);
        log.error(err);
        // we can handle a broker not available error or a timeout error
        if (err && ((err.name === "BrokerNotAvailableError" && !reconnecting) || err.name === "TimeoutError")) {
          log.error("attempting reconnect");
          reconnecting = true;
          reconnectAttempts++;
          consumerGroup.client.refreshMetadata(consumerGroup.topics, (err) => {
            if (err != null) {
              log.error(`error refreshing metadata for consumer group: ${err}`);
              log.error(err.stack);
            } else {
              log.error(`reconnect successful`);
              reconnectAttempts = 0;
            }
            reconnecting = false;
          });
        }
      });
      consumerGroup.on('connect', () => {
        reconnectAttempts = 0;
        log.info(`Connected consumerGroup ${groupName}`);
      });
```

Thanks again for this great lib.
