### ISSUE TITLE
Browserified nodejs modules using kafka-node not working

### ISSUE THREAD

**Issue by daana81** [SOHU-Co/kafka-node#872]
Browserified nodejs modules built using kafka-node does not work .

Error 
Error: Cannot find module './lib/BufferMaker'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)

Environment:Local(Nodejs app) & AWS(Kafka alone)
Node version: V8.7.0
* Kafka-node version:2.4.1
* Kafka version:0.11.0.0

**Comment by hyperlink** [comment]
Unfortunately, this module does not work in the browser.
