### ISSUE TITLE
can able to connect to my kafka server

### ISSUE THREAD

**Issue by sugir93** [SOHU-Co/kafka-node#894]
{ Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 }

**Comment by ahmdichsan** [comment]
have you solve this problem? @sugir93
