### ISSUE TITLE
"Callback was already called" in KafkaClient.wrapTimeoutIfNeeded

### ISSUE THREAD

**Issue by thomaslee** [SOHU-Co/kafka-node#902]
## Bug Report

Having a hard time getting a simple repro case on this one, but taking this stack trace from the CI builds of one of our services:

```
2018-02-12T06:05:28.824Z - error: [aaa.bbb] uncaughtException: Callback was already called.
column=32, file=/path/to/app/node_modules/async/dist/async.js, function=null, line=955, method=null, native=false, 
column=5, file=/path/to/app/node_modules/kafka-node/lib/kafkaClient.js, function=Timeout.setTimeout [as _onTimeout], line=389, method=setTimeout [as _onTimeout], native=false, 
column=11, file=timers.js, function=ontimeout, line=469, method=null, native=false, 
column=5, file=timers.js, function=tryOnTimeout, line=304, method=null, native=false, 
column=5, file=timers.js, function=Timer.listOnTimeout, line=264, method=listOnTimeout, native=false
```

Seems like some callbacks passed to functions like `async.mapValues`, `async.doWhilst`, `async.waterfall` used in kafkaClient.js get wrapped in an `async.onlyOnce` (an internal implementation detail of the `async` lib), which seems to be the thing throwing the exception. I suspect we're somehow calling an "unwrapped" onlyOnce callback, then somehow hitting the "wrapped" timeout logic as well. The logic inside wrapTimeoutIfNecessary looks solid to me & I can't see how this bug would happen if all calls to the callback went via the "wrapped" callback.

Haven't entirely ruled out our code yet, but thought I might raise a ticket here in case something leaps out at you folks. Will follow up as we learn more.

### Environment

* Node version: 8.x
* Kafka-node version: 2.4.1
* Kafka version: 1.0.0

### For specific cases also provide
* Number of Brokers: 1 (part of an integration test)
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

Unavailable for now.

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Unavailable for now.

**Comment by thomaslee** [comment]
Also worth noting that we've seen this error occur in KafkaClient instances backing both consumers and producers.

**Comment by sfrooster** [comment]
Having a seemingly similar issue. Node versions 6.x, 8.x or 9.x, Kafka-Node 2.4.1, Kafka version 0.10.0.2.  First, seeing the following when running npm install:
```
> snappy@6.0.1 install /Users/mhaan/AppDev/ot-eda-node/node_modules/snappy
> node-gyp rebuild

  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:37:17: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      callback->Call(2, argv);
                ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:65:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:103:17: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      callback->Call(2, argv);
                ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
3 warnings generated.
  SOLINK_MODULE(target) Release/binding.node
```

Then, when running (we use the async npm):
```
[INFO   ] 2018-03-20T07:53:24.666Z Client connected [engtech_test-reso-changed_04788]
[INFO   ] 2018-03-20T07:53:25.379Z caught exit
[INFO   ] 2018-03-20T07:53:25.379Z shutting down
/Users/mhaan/AppDev/ot-eda-node/node_modules/async/dist/async.js:955
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /Users/mhaan/AppDev/ot-eda-node/node_modules/async/dist/async.js:955:32
    at Immediate._onImmediate (/Users/mhaan/AppDev/ot-eda-node/lib/Bus.js:632:21)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
Possibly related?  This all worked last week...

**Comment by thomaslee** [comment]
@sfrooster not ruling it out, but I'm not seeing kafkaClient.js anywhere in your stack trace -- since the underlying error's originating in the `async` library (which seems to be pretty popular), it's pretty easy to imagine similar messages showing up in all sorts of odd places.

**Comment by sfrooster** [comment]
Understandable - I've been on this for 10 or so hours now, so I got a little curt with details.  To clarify:
- snappy is being installed as a dependency of kafka-node
- all those "deprecated" warnings started occurring today (but I haven't done a fresh build in probably a week or so)
- the run output is showing the kafka client connecting to the cluster and *immediately* failing inside an async.queue block (which is where we handle polling, message handling and offset commits)

It's possible we've run into *two* issues, one which happens to be related to yours and a separate one having to do with snappy, but it's also possible the snappy issue is surfacing the other.

In fact, here's our stack trace:
```
Error: Snappy codec is not installed
    at Object.unavailableCodec (/Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/codec/snappy.js:9:11)
    at Object.<anonymous> (/Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/protocol/protocol.js:214:17)
    at Object.self.tap (/Users/mhaan/AppDev/ot-eda-node/node_modules/binary/index.js:248:12)
    at decodeMessageSet (/Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/protocol/protocol.js:174:8)
    at Object.<anonymous> (/Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/protocol/protocol.js:124:26)
    at Object.self.tap (/Users/mhaan/AppDev/ot-eda-node/node_modules/binary/index.js:248:12)
    at Object.decodePartitions (/Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/protocol/protocol.js:118:8)
    at Object.self.loop (/Users/mhaan/AppDev/ot-eda-node/node_modules/binary/index.js:267:16)
    at Object.<anonymous> (/Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/protocol/protocol.js:56:8)
    at Object.self.loop (/Users/mhaan/AppDev/ot-eda-node/node_modules/binary/index.js:267:16)
    at _decodeFetchResponse (/Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/protocol/protocol.js:109:6)
    at /Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/protocol/protocol.js:84:12
    at KafkaClient.Client.handleReceivedData (/Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/client.js:769:20)
    at Socket.<anonymous> (/Users/mhaan/AppDev/ot-eda-node/node_modules/kafka-node/lib/kafkaClient.js:618:10)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
```

**Comment by thomaslee** [comment]
A little more info on this one: the last thing in the logs is an attempted consumer rebalance:

First, a `rebalancing` event fires.

Next, in the logs we see a failed rebalance:

```
2018-04-04T19:58:59.164Zapp  kafka-node:ConsumerGroupRecovery tryToRecoverFrom +2m connect { GroupCoordinatorNotAvailable
2018-04-04T19:58:59.164Zapp    at new GroupCoordinatorNotAvailable (/var/www/myservice/node_modules/kafka-node/lib/errors/GroupCoordinatorNotAvailableError.js:4:9)
2018-04-04T19:58:59.164Zapp    at createGroupError (/var/www/myservice/node_modules/kafka-node/lib/protocol/protocol.js:95:13)
2018-04-04T19:58:59.164Zapp    at Object.<anonymous> (/var/www/myservice/node_modules/kafka-node/lib/protocol/protocol.js:759:18)
2018-04-04T19:58:59.164Zapp    at Object.self.tap (/var/www/myservice/node_modules/binary/index.js:248:12)
2018-04-04T19:58:59.164Zapp    at decodeGroupCoordinatorResponse (/var/www/myservice/node_modules/kafka-node/lib/protocol/protocol.js:757:6)
2018-04-04T19:58:59.164Zapp    at KafkaClient.Client.handleReceivedData (/var/www/myservice/node_modules/kafka-node/lib/client.js:769:20)
2018-04-04T19:58:59.164Zapp    at Socket.<anonymous> (/var/www/myservice/node_modules/kafka-node/lib/kafkaClient.js:618:10)
2018-04-04T19:58:59.164Zapp    at emitOne (events.js:115:13)
2018-04-04T19:58:59.164Zapp    at Socket.emit (events.js:210:7)
2018-04-04T19:58:59.164Zapp    at addChunk (_stream_readable.js:252:12)
2018-04-04T19:58:59.164Zapp    at readableAddChunk (_stream_readable.js:239:11)
2018-04-04T19:58:59.164Zapp    at Socket.Readable.push (_stream_readable.js:197:10)
2018-04-04T19:58:59.164Zapp    at TCP.onread (net.js:589:20) message: 'Kafka Error Code: 15', errorCode: 15 }
```

This "error" is actually normal in our case, because we're running against a pristine Kafka cluster in a CI build -- the the initial fetch fails but initiates creation of __consumer_offsets and the associated consumer group. _Most of the time_ we recover on the next retry via `ConsumerGroupRecovery.tryToRecover`'s call to `ConsumerGroup.scheduleReconnect` -- but sometimes there's a 30s delay and we get the dreaded "Callback was already called" error instead.

**Comment by thomaslee** [comment]
I modified `internal/onlyOnce.js` in the `async` lib backing kafka-node to look like this:

```
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.default = onlyOnce;
let nextId = 1
function onlyOnce(fn) {
    const id = nextId++
    console.log(`onlyOnce cb ${id} created at`, (new Error()).stack.replace(/^Error:? ?/, ''))
    return function () {
        if (fn === null) {
          console.log(`onlyOnce cb ${id} called multiple times at`, (new Error()).stack.replace(/^Error:? ?/, ''))
          throw new Error("Callback was already called.");
        }
        console.log(`first call to onlyOnce cb ${id} at`, (new Error()).stack.replace(/^Error:? ?/, ''))
        var callFn = fn;
        fn = null;
        callFn.apply(this, arguments);
    };
}
module.exports = exports["default"];
```

Then managed to reproduce this issue again with those changes in place. I'm no less confused:

```
onlyOnce cb 2 created at
    at onlyOnce (/var/www/myapp/node_modules/async/internal/onlyOnce.js:10:50)
    at nextTask (/var/www/myapp/node_modules/async/waterfall.js:15:42)
    at Object.exports.default [as waterfall] (/var/www/myapp/node_modules/async/waterfall.js:26:5)
    at ConsumerGroup.connect (/var/www/myapp/node_modules/kafka-node/lib/consumerGroup.js:439:9)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at KafkaClient.emit (events.js:207:7)
    at loadMetadataForTopics (/var/www/myapp/node_modules/kafka-node/lib/kafkaClient.js:143:14)
    at KafkaClient.wrappedFn (/var/www/myapp/node_modules/kafka-node/lib/kafkaClient.js:379:14)
    at KafkaClient.Client.handleReceivedData (/var/www/myapp/node_modules/kafka-node/lib/client.js:770:60)
    at Socket.<anonymous> (/var/www/myapp/node_modules/kafka-node/lib/kafkaClient.js:618:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)

first call to onlyOnce cb 2 at
    at /var/www/myapp/node_modules/async/internal/onlyOnce.js:16:60
    at KafkaClient.wrappedFn (/var/www/myapp/node_modules/kafka-node/lib/kafkaClient.js:379:14)
    at KafkaClient.Client.handleReceivedData (/var/www/myapp/node_modules/kafka-node/lib/client.js:770:36)
    at Socket.<anonymous> (/var/www/myapp/node_modules/kafka-node/lib/kafkaClient.js:618:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)

onlyOnce cb 2 called multiple times at
    at /var/www/myapp/node_modules/async/internal/onlyOnce.js:13:70
    at Timeout.setTimeout [as _onTimeout] (/var/www/myapp/node_modules/kafka-node/lib/kafkaClient.js:389:5)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

And immediately after the "called multiple times" notice we get the "Callback was already called" error.

The `wrappedFn()` call _should_ be calling `clearTimeout` on the timer returned by `setTimeout`, and I added diagnostics to confirm that wrappedFn is calling clearTimeout on the same timer that triggers the error here. So that timer code should never fire. Bizarre.

@aikar @hyperlink don't know if anything sticks out to you guys, but if there's an obvious bug here I'm not seeing it. I'm at a point where I think I need to add some diagnostic logging to Node's standard library / bindings to get more info.

**Comment by thomaslee** [comment]
Ugh, sorry guys, false alarm -- this ended up being third-party test libraries hijacking `clearTimeout` (prime suspects are lolex/sinon). I guess there must be some timing/ordering issue in the way we're hooking that junk up that only causes this to manifest sometimes.

Huge pain in the butt. Each repro could take anywhere between 10 minutes to 3+ hours, totally random. Spent a day or two of trying to get my head around the possible paths we could be taking through clearTimeout's internals & what we expected to happen to the Timeout struct returned by setTimeout, then verifying that everything was in the state we expected it to be on the kafka-node side -- lots of debug info indicating that everything should be fine & no indication that it shouldn't work. It just kinda ... _didn't_ sometimes.

Out of desperation I dumped the source code for clearTimeout at runtime upon detecting the bug had occurred & finally "got it":

```
clearTimeout source code: function () {^M
    return clock[method].apply(clock, arguments);^M
}
```

So ... that's just great. 😭 Anyway -- nothing wrong with kafka-node here. 👍

@sfrooster fyi -- doubt it's related to your issue, but thought I'd ping you in case it's helpful.

**Comment by thomaslee** [comment]
@sfrooster actually, the trick I used to really pin down the line of code where things were going awry (modifying `async/internal/onlyOnce.js`) might be useful to your issue RE: the "Callback was already called" error.

**Comment by sfrooster** [comment]
Thanks Tom. I'm actually in the process of migrating to Blizzard so the
whole issue is likely moot.

**Comment by HansonHH** [comment]
@hyperlink @aikar Perhaps we need to take another look at this? I'm still seeing this issue using `kafka-node` 4.0.1 and `Kafka` 2.0.0. Some logs:

```
2019-03-18 16:43:55.042 Consumer is rebalanced
2019-03-18 16:44:25.807 Error: Callback was already called.\n    at /opt/neti/node_modules/async/dist/async.js:966:32\n    at /opt/neti/node_modules/kafka-node/lib/baseClient.js:267:27\n    at Timeout.setTimeout (/opt/neti/node_modules/kafka-node/lib/kafkaClient.js:487:5)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)
2019-03-18 16:44:25.809 TimeoutError: Request timed out after 30000ms\n    at new TimeoutError (/opt/neti/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)\n    at Timeout.setTimeout (/opt/neti/node_modules/kafka-node/lib/kafkaClient.js:487:14)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)
```
In my scenario, I have three Kafka brokers in the cluster. I want to let consumers from a new consumer groups continue subscribing messages from a deprecated consumer group's committed offsets. When a consumer is rebalanced, it initializes an `Admin` client to call `describeGroups` and get assigned partitions and then initializes an `Offset` client to fetch topic offsets by both using the KafkaClient object from ConsumerGroup object. The error sometimes occurs during a rolling upgrade of Kafka cluster. Am I doing something wrong? Or if the root cause is from `async` module that we use, should we upgrade it to its latest version which is 3.0.1-0 and we are using 2.6.2?
