### ISSUE TITLE
Exception: CONNECTION_LOSS[-4] crashing node app

### ISSUE THREAD

**Issue by mozrat** [SOHU-Co/kafka-node#960]
I am experiencing constant exceptions with a simple setup running in different docker containers on my development machine

I believe the error is thrown during the consumption of messages, my code is below.

Starting from hardly any experience of Kafka, so any thoughts welcome

### Environment

* Node version: node:6.10.1
* Kafka-node version: ^2.6.1
* Kafka version: spotify/kafka docker image

### Consumer code
```js
/* istanbul ignore next */
'use strict';

const kafka = require('kafka-node');
const Client = kafka.KafkaClient;
const Consumer = kafka.Consumer;
const log = require('./Logger');
const path = require('path');
const Promise = require('bluebird');
let client, consumer, consumerReady;
let mdb = require('./MDB');

let closeClient = function () {
  client.close();
};

let hostname = process.env.NODE_ENV === 'development' ? '192.168.99.100:2181' : 'service-kafka:2181';
let connectedMode = process.env.KAFKA_CONNECT !== 'false';

let bindListeners = function () {
  consumer.on('error', function (err) {
    console.log(`MessageConsumer ERROR: ${err.message}`);
    closeClient();
  });
  consumer.on('SIGTERM', function () {
    closeClient();
  });
  consumer.on('message', function (message) {
    processMessage(message);
  });
  consumerReady = new Promise(function (resolve, reject) {
    consumer.on('ready', function () {
      resolve(consumer);
    });
  });
};

let initializeClient = function () {
  client = new Client({kafkaHost: hostname});

  let topics = [];

  let topicList = require(path.join(process.cwd(), 'package.json')).kafkaConfig.consume;

  topicList.forEach(topic => {
    topics.push({topic: topic, partition: 0});
  });

  log.info(`MessageConsumer: Listening on topics: ${JSON.stringify(topics)}`);

  let options = {autoCommit: false, fetchMaxWaitMs: 1000, fetchMaxBytes: 1024 * 1024};
  consumer = new Consumer(client, topics, options);
  bindListeners();
};

let MessageConsumer = function () {
  this.mdb = mdb;
  if (connectedMode) {
    initializeClient();
  }
};



/* istanbul ignore next */
let processMessage = function (msg) { /** write message to database */}


MessageConsumer.prototype.getConsumer = function () {

  return new Promise((resolve, reject) => {

    if (!connectedMode) {
      return resolve();
    }
    consumerReady.then((consumer) => {
      return resolve(consumer);
    });
  });
};

module.exports = MessageConsumer;

```

### Kafka Dockerfile
```
FROM spotify/kafka

ENV KAFKA_ADVERTISED_HOST_NAME service-kafka
ENV KAFKA_PORT 9092
ENV KAFKA_HOST_NAME service-kafka
ENV KAFKA_CREATE_TOPICS "auth:1:1,datastore:1:1,transactions:1:1"
ENV AUTO_CREATE_TOPICS true
```

### Node crash message

2018-04-29T21:33:35.934Z - error: uncaughtException: Exception: CONNECTION_LOSS[-4] date=Sun Apr 29 2018 21:33:35 GMT+0000 (UTC), pid=30, uid=0, gid=0, cwd=/opt/app, execPath=/usr/local/bin/node, version=v6.10.1, argv=[/usr/local/bin/node, /opt/app/service.js], rss=77074432, heapTotal=62566400, heapUsed=51444608, external=21747563, loadavg=[20.21630859375, 11.82373046875, 10.51171875], uptime=148629, trace=[column=28, file=/opt/app/node_modules/node-zookeeper-client/lib/ConnectionManager.js, function=ConnectionManager.queue, line=720, method=queue, native=false, column=36, file=/opt/app/node_modules/node-zookeeper-client/index.js, function=null, line=799, method=null, native=false, column=13, file=/opt/app/node_modules/node-zookeeper-client/index.js, function=async.whilst.args, line=125, method=args, native=false, column=13, file=/opt/app/node_modules/node-zookeeper-client/node_modules/async/lib/async.js, function=Object.async.whilst, line=619, method=whilst, native=false, column=23, file=/opt/app/node_modules/node-zookeeper-client/node_modules/async/lib/async.js, function=Timeout._onTimeout, line=623, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=380, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=244, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=214, method=listOnTimeout, native=false], stack=[CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4],     at ConnectionManager.queue (/opt/app/node_modules/node-zookeeper-client/lib/ConnectionManager.js:720:28),     at /opt/app/node_modules/node-zookeeper-client/index.js:799:36,     at async.whilst.args (/opt/app/node_modules/node-zookeeper-client/index.js:125:13),     at Object.async.whilst (/opt/app/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:619:13),     at Timeout._onTimeout (/opt/app/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:623:23),     at ontimeout (timers.js:380:14),     at tryOnTimeout (timers.js:244:5),     at Timer.listOnTimeout (timers.js:214:5)]

**Comment by hyperlink** [comment]
Using `KafkaClient` you should connect to your  kafka host instead of zookeeper. By default port 2181 is zookeeper and 9092 is kafka.

**Comment by mozrat** [comment]
Hi @hyperlink - good spot, thank you.

I changed the port and restarted my stack of microservices. I still had a service fail with the same exception so changing the connection port doesn't seem to make a big difference for me.

**Comment by hyperlink** [comment]
Are you still getting `CONNECTION_LOSS`? This is a zookeeper specific error. Since `KafkaClient` does not use zookeeper very unlikely from KafkaClient.

**Comment by mozrat** [comment]
Yes - same error.

2018-04-30T17:11:10.207Z - error: uncaughtException: Exception: CONNECTION_LOSS[-4] date=Mon Apr 30 2018 17:11:10 GMT+0000 (UTC), pid=30, uid=0, gid=0, cwd=/opt/app, execPath=/usr/local/bin/node, version=v6.10.1, argv=[/usr/local/bin/node, /opt/app/service.js], rss=82726912, heapTotal=75198464, heapUsed=55006696, external=18132699, loadavg=[19.1826171875, 10.517578125, 9.81787109375], uptime=153288, trace=[column=28, file=/opt/app/node_modules/node-zookeeper-client/lib/ConnectionManager.js, function=ConnectionManager.queue, line=720, method=queue, native=false, column=36, file=/opt/app/node_modules/node-zookeeper-client/index.js, function=null, line=799, method=null, native=false, column=13, file=/opt/app/node_modules/node-zookeeper-client/index.js, function=async.whilst.args, line=125, method=args, native=false, column=13, file=/opt/app/node_modules/node-zookeeper-client/node_modules/async/lib/async.js, function=Object.async.whilst, line=619, method=whilst, native=false, column=23, file=/opt/app/node_modules/node-zookeeper-client/node_modules/async/lib/async.js, function=Timeout._onTimeout, line=623, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=380, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=244, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=214, method=listOnTimeout, native=false], stack=[CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4],     at ConnectionManager.queue (/opt/app/node_modules/node-zookeeper-client/lib/ConnectionManager.js:720:28),     at /opt/app/node_modules/node-zookeeper-client/index.js:799:36,     at async.whilst.args (/opt/app/node_modules/node-zookeeper-client/index.js:125:13),     at Object.async.whilst (/opt/app/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:619:13),     at Timeout._onTimeout (/opt/app/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:623:23),     at ontimeout (timers.js:380:14),     at tryOnTimeout (timers.js:244:5),     at Timer.listOnTimeout (timers.js:214:5)]

I changed the port in the code in my original post - this is my Producer code

```
/* istanbul ignore next */
'use strict';

let kafka = require('kafka-node');
let Promise = require('bluebird');
let retry = require('retry');
let client, producer, producerReady;

let closeClient = function () {
  client.close();
};

let hostname = process.env.NODE_ENV === 'development' ? '192.168.99.100:9092' : 'service-kafka:9092';
let connectedMode = process.env.KAFKA_CONNECT !== 'false';


let bindListeners = function () {
  producer.on('error', function (err) {
    console.log(`MessageProducer ERROR: ${err.message}`);
    closeClient();
  });
  producer.on('SIGTERM', function () {
    closeClient();
  });
  producerReady = new Promise(function (resolve, reject) {
    producer.on('ready', function () {
      resolve(producer);
    });
  });
};

let initializeClient = function () {
  client = new kafka.Client(hostname, 'kafka-broker');
  producer = new kafka.HighLevelProducer(client, {});
  bindListeners();
};

let messageHandler = function (err, data) {
  if (err) {
    console.log(err);
  } else {
    console.log(data);
  }
  closeClient();
};

let MessageProducer = function () {
  if (connectedMode) {
    initializeClient();
  }

};

MessageProducer.prototype.sendMessage = function (payload, topic) {

  if (!connectedMode) {
    return;
  }

  let operation = retry.operation({
    // See https://github.com/tim-kos/node-retry for config options
  });
  // eslint-disable-next-line no-unused-vars
  operation.attempt(function (currentAttempt) {

    let jsonMessage;

    try {
      jsonMessage = JSON.stringify(payload);
    } catch (ex) {
      console.log('MessageProducer: Error JSON stringify');
      return;
    }

    const record = [
      {
        topic: topic,
        messages: jsonMessage,
        attributes: 1 /* Use GZip compression for the payload */
      }
    ];

    producerReady.then(function (producer) {

      console.log(`MessageProducer: Sent message to topic ${topic}`);
      producer.send(record, function (err, data) {

        if (err) {
          operation.retry(err);
          return;
        }

        return messageHandler(err, data);
      });
    });
  });
};

module.exports = MessageProducer;

```

Thanks for looking at it. I don't understand why zookeeper is giving this error.

**Comment by mozrat** [comment]
I think I found a contributing factor. I had made a mistake in resolving the kafka broker address based on my environmental variables and so was sending all connections to the external IP of my Docker swarm rather than the internal name

Keeping connection traffic inside the swarm has reduced these errors down to almost none. Sorry for a boneheaded bug report.

**Comment by hyperlink** [comment]
ok np. glad it worked out for you.
