### ISSUE TITLE
Consumer Group Unknown Error (-1)

### ISSUE THREAD

**Issue by AmazingTurtle** [SOHU-Co/kafka-node#962]
I'm using the ConsumerGroupStream as follows

```
                this._kafkaConsumer = new ConsumerGroupStream({
                    kafkaHost: await this.getKafkaHost(),
                    groupId: '***',
                    outOfRangeOffset: 'latest'
                }, [
                    ***
                ]);
                this._kafkaConsumer.on('error', error => {
                    log(error, undefined, LogSeverity.WARN);
                });
                this._kafkaConsumer.on('data', this.onMessageReceived.bind(this));
                this._kafkaConsumer.resume();
```

The error event is emitted in an infinite loop. The error is the following

```
{ topic: '***',
  partition: 0,
  message: 'Unknown' }
```
and
```
{ topic: '***',
  partition: 1,
  message: 'Unknown' }
```

I searched for Error 'Unknown'. It's error code -1. According to https://kafka.apache.org/protocol#protocol_error_codes it's more specifically a server side error.

So this is what I got from the server:

```
[2018-05-02 11:55:39,348] ERROR [KafkaApi-0] Error when handling request {replica_id=-1,max_wait_time=100,min_bytes=1,topics=[{topic=***,partitions=[{partition=0,fetch_offset=95,max_bytes=1048576},{partition=1,fetch_offset=97,max_bytes=1048576}]}]} (kafka.server.KafkaApis)
java.lang.IllegalArgumentException: Magic v1 does not support record headers
    at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:385)
    at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:568)
    at org.apache.kafka.common.record.AbstractRecords.convertRecordBatch(AbstractRecords.java:117)
    at org.apache.kafka.common.record.AbstractRecords.downConvert(AbstractRecords.java:98)
    at org.apache.kafka.common.record.FileRecords.downConvert(FileRecords.java:245)
    at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$convertedPartitionData$1$1$$anonfun$apply$5.apply(KafkaApis.scala:523)
    at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$convertedPartitionData$1$1$$anonfun$apply$5.apply(KafkaApis.scala:521)
    at scala.Option.map(Option.scala:146)
```

**Comment by IMRFeng** [comment]
I have the same issue, at last, I changed the producer output headerMode to raw as a workaround. It would be nice and great to have the feature to be supported. @hyperlink Do you have any updates on this issue? I would appreciate if you could give some feedback.

**Comment by tonyisid** [comment]
I have the same issue too. I am using kafka 1.0.0. I am wondering how to work around in client?

**Comment by hyperlink** [comment]
We don't have support for the new record batch message format available in 0.11.

PR's welcome!

You can workaround this by setting `log.message.format.version` to something like 0.10.2 which is what we do in our test.

https://github.com/SOHU-Co/kafka-node/blob/6b718869c05d11b6d65c84f07b99b7ec1fabdfdf/docker/docker-compose.0.11.yml#L6

**Comment by ivomirra** [comment]
Any news regarding this issue?

**Comment by rohit-rapido** [comment]
Is there any update on this.
@hyperlink  Do we know how this occurs and if we can control it.

**Comment by rohit-rapido** [comment]
@hyperlink for us there was an issue with 
[https://docs.instana.io/core_concepts/tracing/#trace-continuity](https://docs.instana.io/core_concepts/tracing/#trace-continuity)
Instana does not support kafka-node. This was the reason, the consumer started failing with unknown error.
I think we can put some effort to get this fixed and start supporting the headers.
