### ISSUE TITLE
kafka consumerGroup retries

### ISSUE THREAD

**Issue by menglecho** [SOHU-Co/kafka-node#967]
## Bug Report
consumerGroup retries doesn't work as expected, it should retries 4 times instead 6 times
### Environment

* Node version: 8.11.1
* Kafka-node version: 2.5.0
* Kafka version: 1.1.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior
var kafka = require('kafka-node');
var topic = ["AlarmStateIndication"];

var options = {
    host: 'zookeeper:2181',
    kafkaHost: 'localhost:9092',
    groupId: 'adpalarmsnmpnbi',
    sessionTimeout: 15000,
    fromOffset: 'latest',
    retries: 4
};

var consumerGroup = new kafka.ConsumerGroup(options, topic);

consumerGroup.on('message', function (message) {
    console.log("kafka receive message!!");
    console.log(message);
});

consumerGroup.on('error', function (err) {
    console.error("Kafka server not ready " + err);
});

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

emeglig@elxa991pq72:~/work/repo/adp-gs-alarm-snmp-nbi/src/kafka-client$ node alarmConsumer.js 
  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +2ms
  kafka-node:KafkaClient Socket Error { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +5ms
  kafka-node:KafkaClient failed to connect because of  { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +2ms
  kafka-node:KafkaClient Connect attempt 2 +1s
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +0ms
  kafka-node:KafkaClient Socket Error { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +2ms
  kafka-node:KafkaClient failed to connect because of  { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +0ms
  kafka-node:KafkaClient Connect attempt 3 +2s
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +1ms
  kafka-node:KafkaClient Socket Error { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +1ms
  kafka-node:KafkaClient failed to connect because of  { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +0ms
  kafka-node:KafkaClient Connect attempt 4 +6s
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +0ms
  kafka-node:KafkaClient Socket Error { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +1ms
  kafka-node:KafkaClient failed to connect because of  { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +0ms
  kafka-node:KafkaClient Connect attempt 5 +8s
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +1ms
  kafka-node:KafkaClient Socket Error { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +1ms
  kafka-node:KafkaClient failed to connect because of  { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +0ms
  kafka-node:KafkaClient Connect attempt 6 +22s
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +0ms
  kafka-node:KafkaClient Socket Error { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +1ms
  kafka-node:KafkaClient failed to connect because of  { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +1ms
  kafka-node:KafkaClient exhausted retries. Main error { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +1ms
  kafka-node:ConsumerGroup Error from kafka-node-client { Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9092 } +0ms
Kafka server not ready Error: connect ECONNREFUSED 127.0.0.1:9092
emeglig@elxa991pq72:~/work/repo/adp-gs-alarm-snmp-nbi/src/kafka-client$ cd ..

Thanks for your contribution!

**Comment by hyperlink** [comment]
You're running into the client retries since it never made it's initial connection to kafka. Take a look at `connectRetryOptions` in the `KafkaClient`.

**Comment by menglecho** [comment]
@hyperlink Do you means if I connected to the kafka first, then if the connection breaks, it will retries 4 times?

**Comment by hyperlink** [comment]
There are several types of retries in the module. If the socket connection breaks and that socket hasn't been idle then it will reconnect indefinitely. There's a mechanism in KafkaClient for the initial connection to discover the broker metadata. And then in ConsumerGroup, there is retry/recover for group related errors.
