### ISSUE TITLE
Consumer recovery for partition unavailble

### ISSUE THREAD

**Issue by thspinto** [SOHU-Co/kafka-node#970]
I found a corner case that makes the consumer hang until there a change on the coordinator broker for it's group.

## Bug Report
I created cluster with 3 brokers and a `TestTopic` with one partition and replication factor 1. Initially, the leader for partition 0 is broker 3.

When I kill broker 3 wait a few seconds and bring it back on, the consumer takes a long time to recover. It only recovers when there is a change on the group coordinator broker.

I think there should be some periodic check to see if it's safe to start fetching data again. Maybe  #887 could fix this problem.

### Environment

* Node version: 6.11.3
* Kafka-node version: 2.6.1
* Kafka version: 1.0.0
* kafkaHost (config): contains all available brokers

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 1
* Replication: 1

### Output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on
Logs after I kill broker 3.

```
  kafka-node:ConsumerGroup kafka-node-client Heartbeat error: { BrokerNotAvailableError: Broker not available
    at new BrokerNotAvailableError (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.Client.sendGroupRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:311:15)
    at KafkaClient.Client.sendHeartbeatRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:331:8)
    at Heartbeat.send (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroupHeartbeat.js:14:17)
    at ConsumerGroup.sendHeartbeat (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroup.js:625:13)
    at Timeout.heartbeatInterval.setInterval [as _onTimeout] (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroup.js:587:24)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Broker not available' } +1ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom heartbeat { BrokerNotAvailableError: Broker not available
    at new BrokerNotAvailableError (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.Client.sendGroupRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:311:15)
    at KafkaClient.Client.sendHeartbeatRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:331:8)
    at Heartbeat.send (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroupHeartbeat.js:14:17)
    at ConsumerGroup.sendHeartbeat (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroup.js:625:13)
    at Timeout.heartbeatInterval.setInterval [as _onTimeout] (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroup.js:587:24)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Broker not available' } +2ms
  kafka-node:ConsumerGroupRecovery RECOVERY from heartbeat: kafka-node-client retrying in 1000 ms { BrokerNotAvailableError: Broker not available
    at new BrokerNotAvailableError (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.Client.sendGroupRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:311:15)
    at KafkaClient.Client.sendHeartbeatRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:331:8)
    at Heartbeat.send (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroupHeartbeat.js:14:17)
    at ConsumerGroup.sendHeartbeat (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroup.js:625:13)
    at Timeout.heartbeatInterval.setInterval [as _onTimeout] (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroup.js:587:24)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Broker not available' } +3ms
  kafka-node:KafkaClient updating metadatas +36ms
  kafka-node:ConsumerGroup brokersChanged refreshing metadata +202ms
  kafka-node:Client refresh metadata currentAttempt 1 +3ms
  kafka-node:KafkaClient updating metadatas +8ms
  kafka-node:ConsumerGroup trying to reconnect if needed +2ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +1ms
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +1ms
  kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: 'kb1.local.thsp.tech',
  coordinatorPort: 19092,
  coordinatorId: 1 } +10ms
  kafka-node:ConsumerGroup joinGroupResponse {"members":[{"subscription":["TestTopic"],"version":0,"id":"kafka-node-client-d514f1fa-c260-48f8-bfc6-f40fde156763"}],"generationId":100,"groupProtocol":"roundrobin","leaderId":"kafka-node-client-d514f1fa-c260-48f8-bfc6-f40fde156763","memberId":"kafka-node-client-d514f1fa-c260-48f8-bfc6-f40fde156763"} from kafka-node-client +20ms
  kafka-node:ConsumerGroup Assigning Partitions to members [ { subscription: [ 'TestTopic' ],
    version: 0,
    userData: undefined,
    id: 'kafka-node-client-d514f1fa-c260-48f8-bfc6-f40fde156763' } ] +0ms
  kafka-node:ConsumerGroup Using group protocol roundrobin +2ms
  kafka-node:ConsumerGroup loadingMetadata for topics: [ 'TestTopic' ] +0ms
  kafka-node:ConsumerGroup mapTopicToPartitions { TestTopic: [] } +8ms
  kafka-node:Roundrobin topicPartition: {"TestTopic":[]} +0ms
  kafka-node:Roundrobin groupMembers: [{"subscription":["TestTopic"],"version":0,"id":"kafka-node-client-d514f1fa-c260-48f8-bfc6-f40fde156763"}] +1ms
  kafka-node:Roundrobin members [ 'kafka-node-client-d514f1fa-c260-48f8-bfc6-f40fde156763' ] +0ms
  kafka-node:Roundrobin subscribers { 'kafka-node-client-d514f1fa-c260-48f8-bfc6-f40fde156763': [ 'TestTopic' ] } +1ms
  kafka-node:Roundrobin round robin on topic partition pairs:  [] +1ms
  kafka-node:ConsumerGroup SyncGroup Request from kafka-node-client-d514f1fa-c260-48f8-bfc6-f40fde156763 +1ms
  kafka-node:ConsumerGroup SyncGroup Response +89ms
  kafka-node:ConsumerGroup generationId 100 +0ms
  kafka-node:ConsumerGroup startFetch is false +0ms
  kafka-node:ConsumerGroup kafka-node-client started heartbeats at every 5000 ms +0ms
```

Recovery logs
```
kafka-node:ConsumerGroup kafka-node-client Heartbeat error: { NotCoordinatorForGroup: Kafka Error Code: 16
    at new NotCoordinatorForGroup (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/errors/NotCoordinatorForGroupError.js:4:9)
    at createGroupError (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/protocol/protocol.js:113:13)
    at Object.<anonymous> (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/protocol/protocol.js:763:14)
    at Object.self.tap (/home/thiagopinto/workspace/node-kafka/node_modules/binary/index.js:248:12)
    at decodeGroupHeartbeatResponse (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/protocol/protocol.js:762:87)
    at KafkaClient.Client.handleReceivedData (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:783:20)
    at Socket.<anonymous> (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/kafkaClient.js:641:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) message: 'Kafka Error Code: 16', errorCode: 16 } +4m
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom heartbeat { NotCoordinatorForGroup: Kafka Error Code: 16
    at new NotCoordinatorForGroup (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/errors/NotCoordinatorForGroupError.js:4:9)
    at createGroupError (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/protocol/protocol.js:113:13)
    at Object.<anonymous> (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/protocol/protocol.js:763:14)
    at Object.self.tap (/home/thiagopinto/workspace/node-kafka/node_modules/binary/index.js:248:12)
    at decodeGroupHeartbeatResponse (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/protocol/protocol.js:762:87)
    at KafkaClient.Client.handleReceivedData (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:783:20)
    at Socket.<anonymous> (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/kafkaClient.js:641:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) message: 'Kafka Error Code: 16', errorCode: 16 } +3ms
  kafka-node:ConsumerGroupRecovery RECOVERY from heartbeat: kafka-node-client retrying in 1000 ms { NotCoordinatorForGroup: Kafka Error Code: 16
    at new NotCoordinatorForGroup (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/errors/NotCoordinatorForGroupError.js:4:9)
    at createGroupError (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/protocol/protocol.js:113:13)
    at Object.<anonymous> (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/protocol/protocol.js:763:14)
    at Object.self.tap (/home/thiagopinto/workspace/node-kafka/node_modules/binary/index.js:248:12)
    at decodeGroupHeartbeatResponse (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/protocol/protocol.js:762:87)
    at KafkaClient.Client.handleReceivedData (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:783:20)
    at Socket.<anonymous> (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/kafkaClient.js:641:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) message: 'Kafka Error Code: 16', errorCode: 16 } +0ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +1s
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +0ms
  kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: 'kb3.local.thsp.tech',
  coordinatorPort: 39092,
  coordinatorId: 3 } +5ms
  kafka-node:KafkaClient found 1 connected broker(s) +4ms
  kafka-node:ConsumerGroupRecovery tryToRecoverFrom connect { BrokerNotAvailableError: Broker not available
    at new BrokerNotAvailableError (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.Client.sendGroupRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:311:15)
    at KafkaClient.Client.sendJoinGroupRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:323:8)
    at /home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroup.js:497:21
    at nextTask (/home/thiagopinto/workspace/node-kafka/node_modules/async/dist/async.js:5310:14)
    at next (/home/thiagopinto/workspace/node-kafka/node_modules/async/dist/async.js:5317:9)
    at /home/thiagopinto/workspace/node-kafka/node_modules/async/dist/async.js:958:16
    at KafkaClient.wrappedFn (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/kafkaClient.js:397:14)
    at KafkaClient.Client.handleReceivedData (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:784:60)
    at Socket.<anonymous> (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/kafkaClient.js:641:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) message: 'Broker not available' } +4ms
  kafka-node:ConsumerGroupRecovery RECOVERY from connect: kafka-node-client retrying in 1000 ms { BrokerNotAvailableError: Broker not available
    at new BrokerNotAvailableError (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at KafkaClient.Client.sendGroupRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:311:15)
    at KafkaClient.Client.sendJoinGroupRequest (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:323:8)
    at /home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/consumerGroup.js:497:21
    at nextTask (/home/thiagopinto/workspace/node-kafka/node_modules/async/dist/async.js:5310:14)
    at next (/home/thiagopinto/workspace/node-kafka/node_modules/async/dist/async.js:5317:9)
    at /home/thiagopinto/workspace/node-kafka/node_modules/async/dist/async.js:958:16
    at KafkaClient.wrappedFn (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/kafkaClient.js:397:14)
    at KafkaClient.Client.handleReceivedData (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/client.js:784:60)
    at Socket.<anonymous> (/home/thiagopinto/workspace/node-kafka/node_modules/kafka-node/lib/kafkaClient.js:641:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) message: 'Broker not available' } +4ms
  kafka-node:KafkaClient updating metadatas +72ms
  kafka-node:ConsumerGroup brokersChanged refreshing metadata +203ms
  kafka-node:Client refresh metadata currentAttempt 1 +1ms
  kafka-node:KafkaClient updating metadatas +12ms
  kafka-node:ConsumerGroup trying to reconnect if needed +2ms
  kafka-node:ConsumerGroup Connecting kafka-node-client +0ms
  kafka-node:ConsumerGroupStream commit ignored. no commits to make. +1ms
  kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: 'kb3.local.thsp.tech',
  coordinatorPort: 39092,
  coordinatorId: 3 } +4ms
  kafka-node:KafkaClient Sending versions request to kb3.local.thsp.tech:39092 +21ms
  kafka-node:ConsumerGroup joinGroupResponse {"members":[{"subscription":["TestTopic"],"version":0,"id":"kafka-node-client-7e057c8c-00ae-4cb9-8ac9-425f33209161"}],"generationId":105,"groupProtocol":"roundrobin","leaderId":"kafka-node-client-7e057c8c-00ae-4cb9-8ac9-425f33209161","memberId":"kafka-node-client-7e057c8c-00ae-4cb9-8ac9-425f33209161"} from kafka-node-client +72ms
  kafka-node:ConsumerGroup Assigning Partitions to members [ { subscription: [ 'TestTopic' ],
    version: 0,
    userData: undefined,
    id: 'kafka-node-client-7e057c8c-00ae-4cb9-8ac9-425f33209161' } ] +2ms
  kafka-node:ConsumerGroup Using group protocol roundrobin +1ms
  kafka-node:ConsumerGroup loadingMetadata for topics: [ 'TestTopic' ] +0ms
  kafka-node:KafkaClient Received versions response from kb3.local.thsp.tech:39092 +2ms
  kafka-node:KafkaClient setting api support to {"21":{"min":0,"max":0,"usable":false},"22":{"min":0,"max":0,"usable":false},"23":{"min":0,"max":0,"usable":false},"24":{"min":0,"max":0,"usable":false},"25":{"min":0,"max":0,"usable":false},"26":{"min":0,"max":0,"usable":false},"27":{"min":0,"max":0,"usable":false},"28":{"min":0,"max":0,"usable":false},"29":{"min":0,"max":0,"usable":false},"30":{"min":0,"max":0,"usable":false},"31":{"min":0,"max":0,"usable":false},"32":{"min":0,"max":1,"usable":false},"33":{"min":0,"max":0,"usable":false},"34":{"min":0,"max":0,"usable":false},"35":{"min":0,"max":0,"usable":false},"36":{"min":0,"max":0,"usable":false},"37":{"min":0,"max":0,"usable":false},"38":{"min":0,"max":0,"usable":false},"39":{"min":0,"max":0,"usable":false},"40":{"min":0,"max":0,"usable":false},"41":{"min":0,"max":0,"usable":false},"42":{"min":0,"max":0,"usable":false},"produce":{"min":0,"max":5,"usable":2},"fetch":{"min":0,"max":7,"usable":2},"offset":{"min":0,"max":2,"usable":0},"metadata":{"min":0,"max":5,"usable":0},"leader":{"min":0,"max":1,"usable":false},"stopReplica":{"min":0,"max":0,"usable":false},"updateMetadata":{"min":0,"max":4,"usable":false},"controlledShutdown":{"min":0,"max":1,"usable":false},"offsetCommit":{"min":0,"max":3,"usable":2},"offsetFetch":{"min":0,"max":3,"usable":1},"groupCoordinator":{"min":0,"max":1,"usable":0},"joinGroup":{"min":0,"max":2,"usable":0},"heartbeat":{"min":0,"max":1,"usable":0},"leaveGroup":{"min":0,"max":1,"usable":0},"syncGroup":{"min":0,"max":1,"usable":0},"describeGroups":{"min":0,"max":1,"usable":0},"listGroups":{"min":0,"max":1,"usable":0},"saslHandshake":{"min":0,"max":1,"usable":false},"apiVersions":{"min":0,"max":1,"usable":0},"createTopics":{"min":0,"max":2,"usable":false},"deleteTopics":{"min":0,"max":1,"usable":false}} +0ms
  kafka-node:ConsumerGroup mapTopicToPartitions { TestTopic: [ '0' ] } +10ms
  kafka-node:Roundrobin topicPartition: {"TestTopic":["0"]} +0ms
  kafka-node:Roundrobin groupMembers: [{"subscription":["TestTopic"],"version":0,"id":"kafka-node-client-7e057c8c-00ae-4cb9-8ac9-425f33209161"}] +0ms
  kafka-node:Roundrobin members [ 'kafka-node-client-7e057c8c-00ae-4cb9-8ac9-425f33209161' ] +0ms
  kafka-node:Roundrobin subscribers { 'kafka-node-client-7e057c8c-00ae-4cb9-8ac9-425f33209161': [ 'TestTopic' ] } +0ms
  kafka-node:Roundrobin round robin on topic partition pairs:  [ { topic: 'TestTopic', partition: '0' } ] +1ms
  kafka-node:ConsumerGroup SyncGroup Request from kafka-node-client-7e057c8c-00ae-4cb9-8ac9-425f33209161 +3ms
  kafka-node:ConsumerGroup SyncGroup Response +120ms
  kafka-node:ConsumerGroup kafka-node-client owns topics:  { TestTopic: [ 0 ] } +0ms
  kafka-node:ConsumerGroup kafka-node-client fetchOffset Response: {"TestTopic":{"0":370}} +10ms
  kafka-node:ConsumerGroup Has saved offsets +0ms
  kafka-node:ConsumerGroup generationId 105 +0ms
  kafka-node:ConsumerGroup startFetch is true +0ms
  kafka-node:KafkaClient checking payload topic/partitions has leaders +0ms
  kafka-node:KafkaClient found leaders for all +0ms
  kafka-node:KafkaClient grouped requests by 1 brokers ["3"] +0ms
  kafka-node:KafkaClient missing apiSupport waiting until broker is ready... +2ms
  kafka-node:ConsumerGroup kafka-node-client started heartbeats at every 5000 ms +0ms
  kafka-node:KafkaClient Sending versions request to kb3.local.thsp.tech:39092 +5ms
  kafka-node:KafkaClient Received versions response from kb3.local.thsp.tech:39092 +2ms
```

**Comment by Vijendra07Kulhade** [comment]
I am also getting similar issue. Do we have any workaround for it?

**Comment by hyperlink** [comment]
This should not be an issue anymore since ConsumerGroup leader now periodically checks for new topic/partitions in #1057
